---
alias: areas_hall_downstairs_frontdoor_lights
description: Turns the frontdoor light on/off based on sunset and sunrise
mode: single
id: a2c1f562-ff56-43e8-a2bc-9fcaaaf490ed

trigger:
  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    below: 0
  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    above: 0
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded

action:
  - choose:
      conditions:
        - condition: numeric_state
          entity_id:
            - sensor.sun_elevation
          below: 0
      sequence:
        - service: switch.turn_on
          data:
            entity_id: switch.fibaro_frontdoor
    default:
      - service: switch.turn_off
        data:
          entity_id: switch.fibaro_frontdoor
