---
alias: areas_hall_downstairs_frontdoor_lights
description: Turns the frontdoor light on/off based on sunset and sunrise
mode: restart
id: a2c1f562-ff56-43e8-a2bc-9fcaaaf490ed

variables:
  current_light_scene: >-
    scene.frontdoor_lights_{{ states("input_select.current_light_schedule") }}
  anchors:
    - &condition_is_dark
      condition: state
      entity_id: binary_sensor.g4_doorbell_is_dark
      state: "on"

    - &condition_is_presence_detected
      condition: state
      entity_id: binary_sensor.g4_doorbell_motion
      state: "on"

    - &condition_no_presence_detected
      alias: "No presence has been detected for a while"
      condition: state
      entity_id: binary_sensor.g4_doorbell_motion
      state: "off"
      for:
        seconds: 60

    - &condition_light_schedule_change
      alias: "Check if the automation got triggered by a light schedule change"
      condition: trigger
      id: light_schedule_change

    - &turn_on
      action: scene.turn_on
      alias: "Turn the hall lights on"
      data:
        transition: 1

    - &turn_off
      action: light.turn_off
      alias: "Turn the hall lights off"
      data:
        entity_id: light.voordeur
        transition: 5

trigger:
  - trigger: state
    entity_id:
      - binary_sensor.g4_doorbell_is_dark

  - trigger: state
    entity_id:
      - binary_sensor.g4_doorbell_motion
    to: "on"

  - trigger: state
    entity_id:
      - binary_sensor.g4_doorbell_motion
    to: "off"
    for:
      seconds: 60

  - trigger: state
    entity_id: input_select.current_light_schedule
    id: light_schedule_change

  - trigger: homeassistant
    event: start

  - trigger: event
    event_type: automation_reloaded

action:
  - choose:
      - alias: "Very subtly change the lights when a light schedule change is detected."
        conditions:
          - *condition_is_dark
          - *condition_light_schedule_change
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"
            data:
              transition: 120

      - alias: "Turn the light to a dedicated brighter scene when presence has been detected."
        conditions:
          - *condition_is_presence_detected
          - *condition_is_dark
        sequence:
          - <<: *turn_on
            target:
              entity_id: "scene.frontdoor_lights_lezen"

      - alias: "Turn the light to the scheduled scene"
        conditions:
          - *condition_no_presence_detected
          - *condition_is_dark
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"

    default:
      - *turn_off
