---
alias: areas_hall_downstairs_frontdoor_lights
description: Turns the frontdoor light on/off based on sunset and sunrise
mode: single

trigger:
  - platform: sun
    event: sunset
    offset: "-00:45:00"
  - platform: sun
    event: sunrise
    offset: "00:15:00"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded

action:
  - choose:
      conditions:
        - condition: time
          before: '00:00:00'
          after: '16:00:00'
      sequence:
        - service: switch.turn_on
          data:
            entity_id: switch.fibaro_frontdoor
    default:
      - service: switch.turn_off
        data:
          entity_id: switch.fibaro_frontdoor