---
alias: areas_hall_downstairs_frontdoor_lights
description: Turns the frontdoor light on/off based on sunset and sunrise
mode: single

trigger:
  - platform: state
    entity_id:
      - variable.livingroom_darklight
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded

action:
  - choose:
      conditions:
        - condition: state
          entity_id: variable.livingroom_darklight
          state: 'dark'
      sequence:
        - service: switch.turn_on
          data:
            entity_id: switch.fibaro_frontdoor
    default:
      - service: switch.turn_off
        data:
          entity_id: switch.fibaro_frontdoor