---
alias: areas_hall_downstairs_lights
description: Turns the hallway lights on when motion has been detected
mode: queued
id: 797b07af-7b1f-4c4f-bd8f-be9708c64e63

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_hall_downstairs
    to: "on"
  - platform: state
    entity_id: binary_sensor.presence_hall_downstairs
    to: "off"
    for:
      seconds: 40
  - platform: state
    entity_id: input_select.livingroom_current_lights_scene
    to: "movie"
    id: "movie"

condition:
  - condition: state
    alias: "Check if we can automate the lights"
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - condition: trigger
            alias: "Check if we started watching a movie"
            id: "movie"

        sequence:
          - &lights_turn_off
            service: light.turn_off
            alias: "Turn the hall lights off"
            data:
              entity_id: light.fibaro_hall_downstairs
              transition: 5

      - conditions:
          - &presence
            condition: state
            alias: "Presence is detected"
            entity_id: binary_sensor.presence_hall_downstairs
            state: "on"
          - &dark
            condition: state
            alias: "It is dark in the hall"
            entity_id: binary_sensor.hall_is_dark
            state: "on"
          - condition: numeric_state
            alias: "If the sun has set a fair bit"
            entity_id:
              - sensor.sun_elevation
            below: -3
          - condition: time
            alias: "And it is after 7pm"
            after: "19:00:00"

        sequence:
          - service: scene.turn_on
            alias: "Turn the hall lights to dim scene"
            data:
              entity_id: scene.halldownstairs_lights_dim

      - conditions:
          - *presence
          - *dark
          - condition: state
            alias: "If it is dark in the living room, meaning lights are on there"
            entity_id:
              - binary_sensor.livingroom_is_dark
            state: "on"

        sequence:
          - service: scene.turn_on
            alias: "Turn the hall lights to normal scene"
            data:
              entity_id: scene.halldownstairs_lights_normal

      - conditions:
          - *presence
          - *dark

        sequence:
          - service: scene.turn_on
            alias: "Turn the hall lights to bright scene"
            data:
              entity_id: scene.halldownstairs_lights_bright

    default:
      - *lights_turn_off
