---
alias: areas_hall_downstairs_lights_off
description: Turns the hallway lights on when motion has been detected or when we go to sleep
mode: single
id: 9912e78c-8eef-4fa4-ad11-dda6f93078b7

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_hall_downstairs
    to: 'off'
    for: 
      seconds: 80
  - platform: state
    entity_id:
      - sensor.marvin_status
      - sensor.laura_status
    to: 'Slaapt'
  - platform: state
    entity_id: input_select.livingroom_current_scene
    to: 'movie'

condition:
  - condition: state
    entity_id: light.fibaro_hall_downstairs
    state: 'on'
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: 'off'
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.presence_hall_downstairs
        state: 'off'
        for:
          seconds: 80
      - condition: state
        entity_id: sensor.marvin_status
        state: 'Slaapt'
      - condition: state
        entity_id: sensor.laura_status
        state: 'Slaapt'
      - condition: state
        entity_id: input_select.livingroom_current_scene
        state: 'movie'

action:
  - service: light.turn_off
    data:
      entity_id: light.fibaro_hall_downstairs