---
alias: areas_hall_downstairs_lights_on
description: Turns the hallway lights on when motion has been detected
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_hall_downstairs
condition:
  - condition: state
    entity_id: binary_sensor.presence_hall_downstairs
    state: 'on'
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: 'off'
  - condition: state
    entity_id: variable.hall_downstairs_darklight
    state: 'dark'
action:
  - service: script.sunlight
    data:
      entities:
        - light.fibaro_hall_downstairs
      turn_on: true