---
description: "Set a variable to light to keep track of whether it is light or dark"
alias: areas_hall_downstairs_set_to_light
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_hall_downstairs_luminance") | int > 20 and is_state("light.fibaro_hall_downstairs", "off") and is_state("light.fibaro_wc", "off") }}'
    for:
      seconds: 60
condition:
  - '{{ states("sensor.pir_hall_downstairs_luminance") | int > 20 and is_state("light.fibaro_hall_downstairs", "off") and is_state("light.fibaro_wc", "off") }}'
action:
  service: variable.set_variable
  data:
    variable: hall_downstairs_darklight
    value: 'light'