---
description: "Set a variable to dark to keep track of whether it is light or dark"
alias: areas_hall_downstairs_set_to_dark
mode: queued
id: 0077470e-fa74-44b8-ace2-35acc4b17807

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_hall_downstairs_luminance") | int < 20 and is_state("light.fibaro_hall_downstairs", "off")  }}'
    for:
      seconds: 60

condition:
  - '{{ states("sensor.pir_hall_downstairs_luminance") | int < 20 and is_state("light.fibaro_hall_downstairs", "off")  }}'

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.hall_downstairs_darklight
      option: 'dark'