---
alias: areas_hallway_lights_on
description: Turns the hallway lights on when motion has been detected
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.pir_hallway
condition:
  - condition: state
    entity_id: binary_sensor.pir_hallway
    state: 'on'
  - condition: state
    entity_id: input_boolean.manual_lights
    state: 'off'
  - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
  - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
  - condition: state
    entity_id: variable.hallway_darklight
    state: 'dark'
action:
  - service: script.sunlight
    data:
      entities:
        - light.fibaro_hallway
      turn_on: true
  # - service: switch.turn_on
  #   data:
  #     entity_id:
  #       - switch.circadian_lighting_hall
  # - service: light.turn_on
  #   data:
  #     transition: 2
  #     entity_id: 
  #       - light.fibaro_hallway
  #     brightness_pct: >-
  #       {{ state_attr('switch.circadian_lighting_hall', 'brightness') | int }}