---
description: "Set a variable to dark to keep track of whether it is light or dark"
alias: areas_hall_set_to_dark
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_hallway_luminance") | int < 20 and is_state("light.fibaro_hallway", "off")  }}'
    for:
      seconds: 60
condition:
  - '{{ states("sensor.pir_hallway_luminance") | int < 20 and is_state("light.fibaro_hallway", "off")  }}'
action:
  service: variable.set_variable
  data:
    variable: hallway_darklight
    value: 'dark'