---
description: Turn my bed flat again based on iOS actions
alias: system_ios_actions_chill_to_flat
mode: single
id: d7a4be36-b17a-45dd-b16a-d84ea4383573

trigger:
  platform: event
  event_type: ios.action_fired
  event_data:
      actionName: bed_chill_to_flat

action:
  service: rest_command.bed_chill_to_flat