---
description: Set everyone to awake based on iOS actions
alias: system_ios_actions_everyone_awake
mode: single
id: 49385e33-7d72-4c30-b6fc-efd2e0b2b9d0

trigger:
  platform: event
  event_type: ios.action_fired
  event_data:
    actionName: everyone_awake

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.laura_sleep_status_dropdown
      option: 'Wakker'
  - service: input_select.select_option
    data:
      entity_id: input_select.marvin_sleep_status_dropdown
      option: 'Wakker'