---
description: Silence the alarm based on an iOS action
alias: system_ios_actions_silence_alarm
mode: single
id: f1203985-f3a1-4b3e-934e-1b10c3d59d77

trigger:
  platform: event
  event_type: ios.action_fired
  event_data:
      actionName: alarm_off

action:
  service: script.alarm_off