---
# A binary sensor indicating whether the sun is shining directly
# at our windows on the south side of the house. This input is used
# for automating our blinds
binary_sensor:
  - name: sun_at_south_windows
    unique_id: c06b4166-47ef-4f27-9c0d-8a30f10c2b80
    state: >
      {%-
        if states("sensor.sun_azimuth") | int >= 85
        and states("sensor.sun_azimuth") | int <= 270
        and states("sensor.sun_elevation") | int >= 1
      -%}
        on
      {%- else -%}
        off
      {%- endif -%}
