---
# A binary sensor based on our solar panels indicating
# whether the sun is intensly shining. Using this in
# combination with the sun_at_south_windows to control
# the blinds
binary_sensor:
  - name: sun_hot
    unique_id: 9fd20f87-052a-4a50-9990-553144b9c807
    state: >
      {%- if states("sensor.power_production") | float > 1.350 -%}
        on
      {%- else -%}
        off
      {%- endif -%}
