---
sensor:
  - name: daily_energy_produced
    unit_of_measurement: kWh
    device_class: energy
    state_class: measurement
    attributes:
      last_reset: "1970-01-01T00:00:00+00:00"
    state: >
      {{ states('sensor.solar_production_daily') | float(0) | round(1) }}
