---
# Season
#
# The season sensor provides the current astronomical or meteorological
# season (Spring, Summer, Autumn, Winter).
#
# https://www.home-assistant.io/integrations/season/
#
sensor:
  - platform: season
    name: "Season"
    type: astronomical
