---
alias: areas_garden_sunscreen
description: >
  Control the sunscreen based on:
    - The sun angle / whether it's hot
    - Heavy wind detected (todo)
    - Manual override detected (todo)
mode: queued
max_exceeded: silent
id: 028db081-471a-4fee-8373-844eca4943a9

trigger:
  - trigger: homeassistant
    event: start

  - trigger: event
    event_type: automation_reloaded

  - trigger: state
    entity_id:
      - binary_sensor.sun_should_close_south_blinds
    from: ~

  - trigger: state
    entity_id:
      - binary_sensor.weather_can_close_sunscreen

  - trigger: numeric_state
    entity_id:
      - sensor.sun_azimuth
    above: 285
    id: "sun_gone"

variables:
  anchors:
    - &sunscreen_up
      alias: "Open the sunscreen"
      action: scene.turn_on
      target:
        entity_id:
          - scene.garden_cover_open

    - &sunscreen_down
      alias: "Close the sunscreen"
      action: scene.turn_on
      target:
        entity_id:
          - scene.garden_cover_sunblock

    - &manual_control_on
      alias: "Set manual control to on, so the sunscreen stays closed"
      action: input_boolean.turn_on
      target:
        entity_id: input_boolean.sunscreen_manual_control

    - &manual_control_off
      alias: "Reset manual control, so the sunscreen stay closed"
      action: input_boolean.turn_off
      target:
        entity_id: input_boolean.sunscreen_manual_control

action:
  - choose:
      - alias: "Close sunscreen when sun is gone or wind / rain is detected"
        conditions:
          - or:
              - condition: trigger
                id: "sun_gone"
              - condition: state
                entity_id:
                  - binary_sensor.weather_can_close_sunscreen
                state: "off"
        sequence:
          *sunscreen_up

      - alias: "Keep the dinner state active"
        conditions:
          - condition: state
            entity_id:
              - input_select.garden_current_cover_scene
            state: "dinner"
        sequence: []

      - alias: "Close the screen when it is hot"
        conditions:
          - condition: state
            entity_id:
              - binary_sensor.sun_should_close_south_blinds
            state: "on"
        sequence:
          - *sunscreen_down

    default:
      - *sunscreen_up

  # Prevent race condition
  - delay:
      seconds: 10
