---
alias: areas_livingroom_blinds_gardendoor
description: >
  Control the blinds in the living room (which are facing south) by using
   - Sun elevation and azimuth
   - The solar panels (indicating a hot day)
   - Whenever we wake up
   - Fibaro switch on the wall
   - Whether we are watching TV
mode: queued
max_exceeded: silent
id: 3290a52e-cd7b-435b-8d43-7295bd0de3f3

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.sun_should_close_south_blinds
      - input_boolean.setting_manual_blinds
      - input_boolean.livingroom_cover_manual_control
      - binary_sensor.house_mode_everyone_asleep
      - binary_sensor.house_mode_someone_awake
      - binary_sensor.house_mode_someone_just_awake
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    below: -9

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    above: 0

  - platform: state
    entity_id: switch.nspanel_woonkamer_relay_1
    id: "garden_door_switch"
    from:
      - "on"
      - "off"
    to:
      - "on"
      - "off"

  - platform: state
    entity_id:
      - binary_sensor.garden_door_open
    to: "on"
    id: "garden_door_open"

  - platform: state
    entity_id:
      - binary_sensor.garden_door_open
    to: "off"

  - platform: state
    entity_id: media_player.apple_tv
    to:
      - idle
      - standby
      - paused
    for:
      minutes: 8

  - platform: state
    entity_id:
      - scene.gardendoor_cover_closed
      - scene.gardendoor_cover_halfclosed
      - scene.gardendoor_cover_halfopen
      - scene.gardendoor_cover_open
    id: gardendoor_blinds

  - platform: time
    at: "00:03:00"
    id: "reset"

variables:
  anchors:
    - &cover_closed
      alias: "Close the blinds"
      service: scene.turn_on
      target:
        entity_id:
          - scene.gardendoor_cover_closed

    - &cover_half_closed
      alias: "Close the blinds halfway"
      service: scene.turn_on
      target:
        entity_id:
          - scene.gardendoor_cover_halfclosed

    - &cover_half_open
      alias: "Open the blinds half way"
      service: scene.turn_on
      target:
        entity_id:
          - scene.gardendoor_cover_halfopen

    - &manual_control_on
      alias: "Set manual control to on, so the blinds stay closed"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

    - &manual_control_off
      alias: "Reset manual control, so the blinds stay closed"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      - alias: "Respond to garden door switch"
        conditions:
          - condition: trigger
            id: "garden_door_switch"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id:
                      - input_select.gardendoor_current_cover_scene
                    state: "halfopen"
                sequence:
                  - *cover_closed
            default:
              - *cover_half_open

      - alias: "Open garden door blinds when door is open"
        conditions:
          - condition: state
            entity_id: binary_sensor.garden_door_open
            state: "on"
        sequence:
          - *cover_half_open

      - alias: "Check if we manually changed the blinds"
        conditions:
          - condition: trigger
            id: gardendoor_blinds
        sequence:
          - choose:
              - conditions:
                  - alias: "It was changed by a user"
                    condition: template
                    value_template: "{{ trigger.to_state.context.user_id != None }}"
                sequence:
                  - *manual_control_on

      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off

      - alias: "Stop automating the blinds when manual control is on"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.livingroom_cover_manual_control
            state: "on"
        sequence:
          - stop: "Gardendoor blinds are manually controlled"

      - alias: "Fully close blinds when we go to sleep or it is a hot day"
        conditions:
          - condition: or
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.house_mode_everyone_asleep
                    state:
                      - "on"
                  - condition: state
                    entity_id: binary_sensor.house_mode_someone_just_awake
                    state:
                      - "on"
              - condition: state
                entity_id:
                  - binary_sensor.sun_should_close_south_blinds
                state: "on"
              - condition: and
                conditions:
                  - condition: state
                    entity_id:
                      - media_player.apple_tv
                    state: "playing"
                  - condition: state
                    entity_id:
                      - input_select.gardendoor_current_cover_scene
                    state: "closed"
        sequence:
          - *cover_closed

      - alias: "Set to half closed when sun has set"
        conditions:
          - condition: numeric_state
            entity_id:
              - sensor.sun_adjusted_elevation
            below: -9
        sequence:
          - *cover_half_closed

    default:
      - *cover_half_open
