---
alias: areas_livingroom_blinds_gardendoor
description: >
  Control the blinds in the living room (which are facing south) by using
   - Sun elevation and azimuth
   - The solar panels (indicating a hot day)
   - Whenever we wake up
   - Fibaro switch on the wall
   - Whether we are watching TV
mode: queued
max_exceeded: silent
id: 3290a52e-cd7b-435b-8d43-7295bd0de3f3
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.sun_should_close_south_blinds
      - input_boolean.setting_manual_blinds
      - input_boolean.livingroom_cover_manual_control
      - binary_sensor.is_hot_day
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"

  - platform: state
    entity_id:
      - input_select.livingroom_room_mode

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    below: -9

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    above: 4

  - platform: state
    entity_id: input_button.gardendoor_nspanel
    id: "garden_door_switch"

  - platform: state
    entity_id:
      - binary_sensor.garden_door_open
    to: "on"
    id: "garden_door_open"

  - platform: state
    entity_id:
      - binary_sensor.garden_door_open
    to: "off"

  - platform: state
    entity_id: media_player.living_room_android
    to: "off"
    for:
      minutes: 1

  - platform: state
    entity_id:
      - scene.gardendoor_cover_closed
      - scene.gardendoor_cover_halfclosed
      - scene.gardendoor_cover_halfopen
      - scene.gardendoor_cover_open
      - scene.gardendoor_cover_sun
    id: gardendoor_blinds

  - platform: time
    at: "00:03:00"
    id: "reset"

variables:
  anchors:
    - &cover_closed
      alias: "Close the blinds"
      service: scene.turn_on
      target:
        entity_id:
          - scene.gardendoor_cover_closed

    - &cover_half_closed
      alias: "Close the blinds halfway"
      service: scene.turn_on
      target:
        entity_id:
          - scene.gardendoor_cover_halfclosed

    - &cover_half_open
      alias: "Open the blinds half way"
      service: scene.turn_on
      target:
        entity_id:
          - scene.gardendoor_cover_halfopen

    - &cover_sun
      alias: "Block out the sun on a hot day"
      service: scene.turn_on
      target:
        entity_id:
          - scene.gardendoor_cover_sun

    - &manual_control_on
      alias: "Set manual control to on, so the blinds stay closed"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

    - &manual_control_off
      alias: "Reset manual control, so the blinds stay closed"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      - alias: "Respond to garden door switch"
        conditions:
          - condition: trigger
            id: "garden_door_switch"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id:
                      - input_select.gardendoor_current_cover_scene
                    state: "halfopen"
                sequence:
                  - *cover_closed
            default:
              - *cover_half_open

      - alias: "Open garden door blinds when door is open"
        conditions:
          - condition: trigger
            id: garden_door_open
          - condition: state
            entity_id:
              - input_select.gardendoor_current_cover_scene
            state:
              - "closed"
              - "halfclosed"
              - "halfopen"
        sequence:
          - *cover_half_open

      - alias: "Check if we manually changed the blinds"
        conditions:
          - condition: trigger
            id: gardendoor_blinds
        sequence:
          - choose:
              - conditions:
                  - alias: "It was changed by a user"
                    condition: template
                    value_template: "{{ trigger.to_state.context.user_id != None }}"
                  - alias: "It wasn't an NS panel button press"
                    condition: template
                    value_template: >
                      "{{
                          trigger.to_state.context.user_id
                          != '98b8473f95de49ecbb11a513a51df542' }}"
                sequence:
                  - *manual_control_on

      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off

      - alias: "Stop automating the blinds when manual control is on"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.livingroom_cover_manual_control
            state: "on"
        sequence:
          - stop: "Gardendoor blinds are manually controlled"

      - alias: "Keep blinds closed when we are watching TV and closed the blinds"
        conditions:
          - condition: state
            entity_id:
              - media_player.living_room_android
            state: "on"
          - condition: state
            entity_id:
              - input_select.gardendoor_current_cover_scene
            state: "closed"
        sequence:
          - *cover_closed

      - alias: "Close the blinds a bit more a hot day"
        conditions:
          - condition: state
            entity_id:
              - binary_sensor.sun_should_close_south_blinds
            state: "on"
          - or:
              - alias: Keep the heat out of the house on hot days
                condition: state
                entity_id:
                  - binary_sensor.is_hot_day
                state: "on"
              - alias: It's hot but we cannot close the sunscreen
                condition: state
                entity_id:
                  - binary_sensor.weather_can_close_sunscreen
                state: "off"
        sequence:
          - *cover_sun

      - alias: "Set to half closed when sun has set"
        conditions:
          - or:
              - and:
                  - condition: numeric_state
                    entity_id:
                      - sensor.sun_adjusted_elevation
                    below: -9
                  - condition: time
                    after: "16:00:00"
              - and:
                  - condition: numeric_state
                    entity_id:
                      - sensor.sun_adjusted_elevation
                    below: 4
                  - condition: time
                    before: "12:00:00"
              - and:
                  - condition: state
                    entity_id: input_select.livingroom_room_mode
                    state:
                      - "Net wakker"
                  - condition: state
                    entity_id:
                      - input_select.livingroom_current_cover_scene
                    state: "halfclosed"
        sequence:
          - *cover_half_closed

    default:
      - *cover_half_open
