---
alias: areas_livingroom_blinds_livingroom
description: >
  Control the blinds in the living room (which are facing south) by using
   - Sun elevation and azimuth
   - The solar panels (indicating a hot day)
   - Whenever we wake up
   - Whether we are watching TV
mode: queued
max_exceeded: silent
id: 3b9ac19f-e963-4f1d-9ef8-a6fd0c4ebc5c

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.sun_should_close_south_blinds
      - input_boolean.setting_manual_blinds
      - input_boolean.livingroom_cover_manual_control
      - binary_sensor.house_mode_everyone_asleep
      - binary_sensor.house_mode_someone_awake
      - binary_sensor.house_mode_someone_just_awake
      - input_boolean.livingroom_cover_manual_control
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    below: -9

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    above: 0

  - platform: state
    entity_id: media_player.apple_tv
    to:
      - idle
      - paused
      - standby
    for:
      minutes: 8

  - platform: state
    entity_id:
      - scene.livingroom_cover_closed
      - scene.livingroom_cover_halfclosed
      - scene.livingroom_cover_halfopen
      - scene.livingroom_cover_open
    id: livingroom_blinds

  - platform: time
    at: "00:03:00"
    id: "reset"

variables:
  anchors:
    - &cover_closed
      alias: "Close the blinds"
      service: scene.turn_on
      target:
        entity_id:
          - scene.livingroom_cover_closed

    - &cover_half_closed
      alias: "Close the blinds halfway"
      service: scene.turn_on
      target:
        entity_id:
          - scene.livingroom_cover_halfclosed

    - &cover_half_open
      alias: "Open the blinds half way"
      service: scene.turn_on
      target:
        entity_id:
          - scene.livingroom_cover_halfopen

    - &manual_control_on
      alias: "Set manual control to on, so the blinds stay closed"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

    - &manual_control_off
      alias: "Reset manual control, so the blinds stay closed"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      - alias: "Check if we manually changed the blinds"
        conditions:
          - condition: trigger
            id: livingroom_blinds
        sequence:
          - choose:
              - conditions:
                  - alias: "It was changed by a user"
                    condition: template
                    value_template: "{{ trigger.to_state.context.user_id != None }}"
                sequence:
                  - *manual_control_on

      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off

      - alias: "Stop automating the blinds when manual control is on"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.livingroom_cover_manual_control
            state: "on"
        sequence:
          - stop: "Living room blinds are manually controlled"

      - alias: "Fully close the blinds when we go to sleep or when it is hot"
        conditions:
          - condition: or
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.house_mode_everyone_asleep
                    state:
                      - "on"
                  - and:
                      - condition: state
                        entity_id: binary_sensor.house_mode_someone_just_awake
                        state:
                          - "on"
                      - condition: state
                        entity_id:
                          - input_select.livingroom_current_cover_scene
                        state: "closed"
              - condition: state
                entity_id:
                  - binary_sensor.sun_should_close_south_blinds
                state: "on"
              - condition: and
                conditions:
                  - condition: state
                    entity_id:
                      - media_player.apple_tv
                    state: "playing"
                  - condition: state
                    entity_id:
                      - input_select.livingroom_current_cover_scene
                    state: "closed"
        sequence:
          - *cover_closed

      - alias: "Cover half closed when sun is down"
        conditions:
          - condition: numeric_state
            entity_id:
              - sensor.sun_adjusted_elevation
            below: -9
        sequence:
          - *cover_half_closed

    default:
      - *cover_half_open
