---
alias: areas_livingroom_blinds_livingroom
description: >
  Control the blinds in the living room (which are facing south) by using
   - Sun elevation and azimuth
   - The solar panels (indicating a hot day)
   - Whenever we wake up
   - Whether we are watching TV
mode: queued
max_exceeded: silent
id: 3b9ac19f-e963-4f1d-9ef8-a6fd0c4ebc5c

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      # Include auto-shut blinds on hot days
      - binary_sensor.sun_should_close_south_blinds
      - input_boolean.setting_manual_blinds
      - input_boolean.livingroom_cover_manual_control
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"
  - platform: state
    entity_id:
      # Whether we just woke up / gone to sleep
      - binary_sensor.house_mode_everyone_asleep
      - binary_sensor.house_mode_someone_awake
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"
  # Sun
  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    below: -10
  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    above: 0
  # Sync blinds 10m after finish wathing TV
  - platform: state
    entity_id: media_player.apple_tv
    to:
      - idle
      - paused
      - standby
    for:
      minutes: 8
  - platform: state
    entity_id:
      - sensor.zoey_status
    to: "Slaapt beneden"
    id: "zoey_sleeps_downstairs"
  - platform: state
    entity_id:
      - sensor.zoey_status
    to:
      - "Wakker"
      - "Slaapt boven"
    id: "zoey_awake"

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      - alias: "Zoey sleeps downstairs"
        conditions:
          - condition: trigger
            id: "zoey_sleeps_downstairs"
        sequence:
          - &cover_closed
            alias: "Close the blinds"
            service: scene.turn_on
            target:
              entity_id:
                - scene.livingroom_cover_closed

          - alias: "Set manual control to on, so the blinds stay closed"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.livingroom_cover_manual_control

      - alias: "Zoey wakes up"
        conditions:
          - condition: trigger
            id: "zoey_awake"
        sequence:
          - alias: "Reset manual control to on, so the blinds stay closed"
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.livingroom_cover_manual_control

      - alias: "Stop automating the blinds when manual control is on"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.livingroom_cover_manual_control
            state: "on"
        sequence: []

      # Fully closed
      - conditions:
          - condition: or
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.house_mode_everyone_asleep
                    state:
                      - "on"
                  - condition: state
                    entity_id: binary_sensor.house_mode_someone_just_awake
                    state:
                      - "on"
              - condition: state
                entity_id:
                  - binary_sensor.sun_should_close_south_blinds
                state: "on"
              - condition: and
                conditions:
                  - condition: state
                    entity_id:
                      - media_player.apple_tv
                    state: "playing"
                  - condition: state
                    entity_id:
                      - input_select.livingroom_current_cover_scene
                    state: "closed"
        sequence:
          - *cover_closed

      # Half closed
      - conditions:
          - condition: numeric_state
            entity_id:
              - sensor.sun_adjusted_elevation
            below: -10
        sequence:
          - service: scene.turn_on
            target:
              entity_id:
                - scene.livingroom_cover_halfclosed
    # Half open
    default:
      - service: scene.turn_on
        target:
          entity_id:
            - scene.livingroom_cover_halfopen
