---
alias: areas_livingroom_blinds_livingroom
description: >
  Control the blinds in the living room (which are facing south) by using
   - Sun elevation and azimuth
   - The solar panels (indicating a hot day)
   - Whenever we wake up
   - Whether we are watching TV
mode: queued
max_exceeded: silent
id: 3b9ac19f-e963-4f1d-9ef8-a6fd0c4ebc5c

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.sun_should_close_south_blinds
      - input_boolean.setting_manual_blinds
      - input_boolean.livingroom_cover_manual_control
      - binary_sensor.is_hot_day
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"

  - platform: state
    entity_id:
      - input_select.livingroom_room_mode

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    below: -9

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    above: 4

  - platform: state
    entity_id: media_player.apple_tv
    to:
      - idle
      - paused
      - standby
    for:
      minutes: 8

  - platform: state
    entity_id:
      - scene.livingroom_cover_closed
      - scene.livingroom_cover_halfclosed
      - scene.livingroom_cover_halfopen
      - scene.livingroom_cover_open
      - scene.livingroom_cover_ventilatingnight
    id: livingroom_blinds

  - platform: time
    at: "03:00:00"
    id: "reset"

variables:
  anchors:
    - &cover_closed
      alias: "Close the blinds"
      service: scene.turn_on
      target:
        entity_id:
          - scene.livingroom_cover_closed

    - &cover_half_closed
      alias: "Close the blinds halfway"
      service: scene.turn_on
      target:
        entity_id:
          - scene.livingroom_cover_halfclosed

    - &cover_half_open
      alias: "Open the blinds half way"
      service: scene.turn_on
      target:
        entity_id:
          - scene.livingroom_cover_halfopen

    - &manual_control_on
      alias: "Set manual control to on, so the blinds stay closed"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

    - &manual_control_off
      alias: "Reset manual control, so the blinds stay closed"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.livingroom_cover_manual_control

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      - alias: "Check if we manually changed the blinds"
        conditions:
          - condition: trigger
            id: livingroom_blinds
        sequence:
          - choose:
              - conditions:
                  - alias: "It was changed by a user"
                    condition: template
                    value_template: "{{ trigger.to_state.context.user_id != None }}"
                sequence:
                  - *manual_control_on

      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off

      - alias: "Keep blinds at ventilating mode during sleeping hours"
        conditions:
          - condition: state
            entity_id:
              - input_select.livingroom_current_cover_scene
            state: "ventilatingnight"
          - condition: state
            entity_id:
              - input_select.livingroom_room_mode
            state: "Slaap"
        sequence:
          - stop: "Keep blinds at ventilating night mode"

      - alias: "Stop automating the blinds when manual control is on"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.livingroom_cover_manual_control
            state: "on"
        sequence:
          - stop: "Living room blinds are manually controlled"

      - alias: "Fully close the blinds when we watch TV with the blinds closed or when it is hot"
        conditions:
          - condition: or
            conditions:
              - and:
                  - condition: state
                    entity_id:
                      - binary_sensor.sun_should_close_south_blinds
                    state: "on"
                  - or:
                      - alias: Keep the heat out of the house on hot days
                        condition: state
                        entity_id:
                          - binary_sensor.is_hot_day
                        state: "on"
                      - alias: It's hot but we cannot close the sunscreen
                        condition: state
                        entity_id:
                          - binary_sensor.weather_can_close_sunscreen
                        state: "off"
              - and:
                  - condition: state
                    entity_id:
                      - media_player.living_room_android
                    state: "on"
                  - condition: state
                    entity_id:
                      - input_select.livingroom_current_cover_scene
                    state: "closed"
        sequence:
          - *cover_closed

      - alias: "Cover half closed when sun is down"
        conditions:
          - or:
              - and:
                  - condition: numeric_state
                    entity_id:
                      - sensor.sun_adjusted_elevation
                    below: -9
                  - condition: time
                    after: "16:00:00"
              - and:
                  - condition: numeric_state
                    entity_id:
                      - sensor.sun_adjusted_elevation
                    below: 4
                  - condition: time
                    before: "12:00:00"
              - and:
                  - condition: state
                    entity_id: input_select.livingroom_room_mode
                    state:
                      - "Net wakker"
                  - condition: state
                    entity_id:
                      - input_select.livingroom_current_cover_scene
                    state: "halfclosed"
        sequence:
          - *cover_half_closed

    default:
      - *cover_half_open
