---
alias: areas_christmas_tree
description: Turns the christmas tree lights on when motion has been detected
mode: queued
id: 574a675b-2297-4a77-8d0b-2fd69e6f777a

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.house_mode_everyone_at_home_working
  - platform: state
    entity_id:
      - binary_sensor.house_mode_someone_just_awake
      - binary_sensor.house_mode_someone_just_home
      - binary_sensor.everyone_left_home
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.house_mode_everyone_asleep
    from: "off"
    to: "on"
    id: "everyone_asleep"

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Turn the christmas lights off when we go to sleep"
        conditions:
          - condition: or
            conditions:
              - alias: "Everyone has gone to sleep"
                condition: trigger
                id: "everyone_asleep"
              - alias: "Everyone at home is working from home"
                condition: state
                entity_id:
                  - binary_sensor.house_mode_everyone_at_home_working
                state: "on"

        sequence:
          - &turn_off
            alias: "Turn the christmas lights off"
            service: switch.turn_off
            target:
              entity_id:
                - switch.christmas_tree

      - conditions:
          - condition: numeric_state
            entity_id: sensor.num_people_at_home
            above: 0
          - condition: or
            conditions:
              - condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_just_awake
                state: "on"
              - condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_awake
                state: "on"

        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.christmas_tree

    default:
      - *turn_off
