---
alias: areas_livingroom_demo
description: Turns the livingroom lights on when motion has been detected
mode: queued
id: f5bf70aa-1a19-4c6e-bbe4-0aed2ea349ee
trace:
  stored_traces: 25

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom_couch

action:
  - choose:
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_livingroom_couch
          state: "on"
      sequence:
        - service: light.turn_on
          entity_id: light.corner_couch
          data:
            brightness_pct: 100
    default:
      - service: light.turn_off
        entity_id: light.corner_couch
