---
alias: areas_livingroom_demo
description: Turns the livingroom lights on when motion has been detected
mode: queued
id: 713ca969-625c-4616-bbde-017c3f618f61
trace:
  stored_traces: 25

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom_rest

action:
  - choose:
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_livingroom_rest
          state: "on"
      sequence:
        - service: light.turn_on
          entity_id: light.fibaro_livingroom
          data:
            brightness_pct: 100
    default:
      - service: light.turn_off
        entity_id: light.fibaro_livingroom
