---
alias: areas_livingroom_dinner_on_off
description: Our dinner lights don't have a physical switch. Automatically turn on/off the dinner light when the living room ceiling lights turns off
mode: single
id: 252f8722-9081-41c5-858e-9ef673224806

trigger:
  - platform: state
    entity_id: light.fibaro_livingroom

action:
  choose:
    - conditions:
        - condition: state
          entity_id: light.fibaro_livingroom
          state: 'on'
      sequence:
        - service: light.turn_on
          entity_id: light.dinner
  default:
    - service: light.turn_off
      entity_id: light.dinner


  