---
alias: areas_livingroom_dinner_off
description: Our dinner lights don't have a physical switch. Automatically turn off the dinner light when the living room ceiling lights turns off
mode: single

trigger:
  - platform: state
    entity_id: light.fibaro_livingroom
    to: 'off'

action:
  - service: light.turn_off
    entity_id: light.dinner