---
alias: areas_livingroom_doorbell_chime
description: Plays a chime sound in the living room when someone presses the doorbell
mode: queued
id: 7da19a0f-9273-4492-948b-bad8e83539ba

variables:
  sonos_entity: media_player.sonos_livingroom

trigger:
  - platform: state
    entity_id:
      - binary_sensor.doorbell_g4_doorbell
    to: "on"

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: switch.doorbell_chime
        state: "off"
      - condition: state
        entity_id:
          - media_player.sonos_livingroom
        state: "playing"

action:
  - service: sonos.snapshot
    data:
      entity_id: "{{ sonos_entity }}"
  - service: sonos.unjoin
    data:
      entity_id: "{{ sonos_entity }}"
  - service: media_player.volume_set
    data:
      entity_id: "{{ sonos_entity }}"
      volume_level: 0.25
  - service: media_player.play_media
    data:
      entity_id: "{{ sonos_entity }}"
      media_content_id: !secret doorbell_chime_url
      media_content_type: music
  - delay:
      seconds: 4
  - service: sonos.restore
    data:
      entity_id: "{{ sonos_entity }}"
