---
alias: areas_livingroom_lights
description: Turns the livingroom lights on when motion has been detected
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: 
      - input_boolean.setting_manual_lights
      - variable.livingroom_darklight
      - sensor.num_people_at_home
      - sensor.marvin_status
      - sensor.laura_status
  - platform: state
    entity_id: binary_sensor.everyone_in_bed
    to: 'on'
    for:
      seconds: 30

condition:  
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: 'off'  

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.everyone_in_bed
            state: 'off'
          - condition: state
            entity_id: variable.livingroom_darklight
            state: 'dark'
          - condition: numeric_state
            entity_id: sensor.num_people_at_home
            above: 0
          - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
          - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.livingroom_normal
            data:
              transition: 3
    default:
      - service: light.turn_off
        entity_id: group.living_room_lights
        data:
          transition: 5
