---
alias: areas_livingroom_lights
description: Turns the livingroom lights on when motion has been detected
mode: queued
id: c2c13dd9-a81c-4b44-a20e-990c460f9347
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.setting_manual_lights

  - platform: state
    entity_id:
      - binary_sensor.livingroom_is_dark
    from: ~
    for:
      seconds: 2
    id: light_dark_change

  - platform: state
    entity_id: input_select.current_light_schedule
    id: light_schedule_change

  - platform: state
    entity_id:
      - binary_sensor.livingroom_is_media_playing
    for:
      seconds: 10

  - platform: state
    entity_id:
      - media_player.living_room_android
    to: "off"

  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom
    to: "off"
    for:
      minutes: 10

  - platform: time
    at: "00:03:00"
    id: "reset"

variables:
  current_light_scene: >
    scene.livingroom_lights_{{ states("input_select.current_light_schedule") }}
  anchors:
    - &condition_is_presence_detected
      alias: "Is there presence in the room?"
      condition: not
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_livingroom
          state: "off"
          for:
            minutes: 10

    - &condition_is_dark
      alias: "Is it dark in the living room?"
      condition: state
      entity_id: binary_sensor.livingroom_is_dark
      state: "on"

    - &condition_watching_tv
      alias: "Check if we are watching a movie or series"
      condition: state
      entity_id: binary_sensor.livingroom_is_media_playing
      state: "on"

    - &condition_first_turn_on
      alias: "Gradually turn the lights on when it gets dark"
      condition: trigger
      id: light_dark_change

    - &condition_light_schedule_change
      alias: "Check if the automation got triggered by a light schedule change"
      condition: trigger
      id: light_schedule_change

    - &turn_off
      alias: "Turn the lights off"
      service: light.turn_off
      target:
        entity_id:
          - light.livingroom
          - light.kitchen
      data:
        transition: 5

    - &turn_on
      alias: "Turn on the lights"
      service: scene.turn_on
      data:
        transition: 2

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: >
          "Toggle movie scene when somethings starts playing"
        conditions:
          - *condition_is_dark
          - *condition_is_presence_detected
          - *condition_watching_tv
        sequence:
          - <<: *turn_on
            target:
              entity_id: scene.livingroom_lights_movie

      - alias: "Gradually turn on the lights the first time."
        conditions:
          - *condition_is_dark
          - *condition_is_presence_detected
          - *condition_first_turn_on
        sequence:
          - <<: *turn_on
            target:
              entity_id: '{{ current_light_scene }}'
            data:
              transition: 10

      - alias: "Very subtly change the lights when a light schedule change is detected."
        conditions:
          - *condition_is_dark
          - *condition_is_presence_detected
          - *condition_light_schedule_change
        sequence:
          - <<: *turn_on
            target:
              entity_id: '{{ current_light_scene }}'
            data:
              transition: 120

      - alias: "Just turn on the lights."
        conditions:
          - *condition_is_dark
          - *condition_is_presence_detected
        sequence:
          - <<: *turn_on
            target:
              entity_id: '{{ current_light_scene }}'

    default:
      - *turn_off
