---
alias: areas_livingroom_lights
description: Turns the livingroom lights on when motion has been detected
mode: queued
id: c2c13dd9-a81c-4b44-a20e-990c460f9347
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.setting_manual_lights
      - binary_sensor.livingroom_is_dark
      - input_select.livingroom_room_mode
    from: ~
    for:
      seconds: 2

  - platform: state
    entity_id:
      - media_player.apple_tv
    to: "playing"
    for:
      seconds: 10

  - platform: state
    entity_id:
      - media_player.apple_tv
    to:
      - "paused"
      - "idle"
    for:
      seconds: 10

  - platform: state
    entity_id:
      - media_player.apple_tv
    to:
      - "standby"

  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom
    to: "off"
    for:
      minutes: 10

  - platform: device
    device_id: 063e0720e7172ed87824f117033874a5
    domain: hue
    type: short_release
    subtype: 1
    unique_id: a9f5c750-a2cb-4924-b041-022f32291224
    id: "hue_dimmer_on_press"

  - platform: device
    device_id: 063e0720e7172ed87824f117033874a5
    domain: hue
    type: short_release
    subtype: 4
    unique_id: fd5ce233-c55e-449a-9c81-d55fc8078f03
    id: "hue_dimmer_off_press"

  - platform: device
    device_id: 063e0720e7172ed87824f117033874a5
    domain: hue
    type: long_press
    subtype: 1
    unique_id: a9f5c750-a2cb-4924-b041-022f32291224
    id: "hue_dimmer_on_long_press"

  - platform: device
    device_id: 063e0720e7172ed87824f117033874a5
    domain: hue
    type: long_press
    subtype: 4
    unique_id: fd5ce233-c55e-449a-9c81-d55fc8078f03
    id: "hue_dimmer_off_long_press"

  - platform: time
    at: "00:03:00"
    id: "reset"

variables:
  anchors:
    - &condition_is_presence_detected
      alias: "Is there presence in the room?"
      condition: not
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_livingroom
          state: "off"
          for:
            minutes: 10

    - &condition_is_dark
      alias: "Is it dark in the living room?"
      condition: state
      entity_id: binary_sensor.livingroom_is_dark
      state: "on"

    - &condition_is_remote_quickly_pressed
      alias: "Did we manually press the button?"
      condition: trigger
      id:
        - "hue_dimmer_on_press"
        - "hue_dimmer_off_press"

    - &condition_is_remote_long_pressed
      alias: "Did we manually long press the button?"
      condition: trigger
      id:
        - "hue_dimmer_on_long_press"
        - "hue_dimmer_off_long_press"

    - &condition_is_current_scene
      alias: "Check the current light scene"
      condition: state
      entity_id: input_select.livingroom_current_lights_scene

    - &condition_watching_tv
      alias: "Check if we are watching a movie or series"
      and:
        - condition: state
          entity_id: media_player.apple_tv
          attribute: app_id
          state:
            - "com.amazon.aiv.AIVApp"
            - "com.netflix.Netflix"
            - "com.firecore.infuse"
            - "com.plexapp.plex"
            - "nl.omroep.uitzendinggemist"
        - condition: state
          entity_id: media_player.apple_tv
          state: "playing"

    - &turn_off
      alias: "Turn the lights off"
      service: light.turn_off
      target:
        entity_id:
          - light.livingroom
          - light.kitchen
      data:
        transition: 5

    - &turn_on
      alias: "Turn on the lights"
      service: scene.turn_on
      data:
        transition: 5

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Reset active scene to 'normal' during reset"
        conditions:
          - condition: trigger
            id: "reset"
        sequence:
          - service: input_select.select_option
            entity_id: input_select.livingroom_current_lights_scene
            data:
              option: normal

      - alias: "Toggle Philips Hue Sync Box on long press"
        conditions:
          - *condition_is_remote_long_pressed
        sequence:
          - if:
              - condition: state
                entity_id:
                  - switch.sync_box_light_sync
                  - switch.sync_box_power
                match: any
                state: "off"
            then:
              - service: switch.turn_on
                entity_id: switch.sync_box_power
              - service: switch.turn_on
                entity_id: switch.sync_box_light_sync
              - <<: *turn_on
                target:
                  entity_id: scene.livingroom_lights_movie
                data:
                  transition: 3
            else:
              - service: switch.turn_off
                entity_id: switch.sync_box_light_sync

      - alias: "Toggle movie scene on single button press."
        conditions:
          - *condition_is_remote_quickly_pressed
          - *condition_is_dark
        sequence:
          - if:
              - <<: *condition_is_current_scene
                state: "movie"
            then:
              - <<: *turn_on
                target:
                  entity_id: scene.livingroom_lights_natuurlijklicht
            else:
              - <<: *turn_on
                target:
                  entity_id: scene.livingroom_lights_movie

      - alias: "Turn on the movie scene when we are watching a movie or series."
        conditions:
          - *condition_is_dark
          - *condition_is_presence_detected
          - *condition_watching_tv
        sequence:
          - <<: *turn_on
            target:
              entity_id: scene.livingroom_lights_movie
            data:
              transition: 3

      - alias: "Just turn on the lights."
        conditions:
          - *condition_is_dark
          - *condition_is_presence_detected
        sequence:
          - <<: *turn_on
            target:
              entity_id: scene.livingroom_lights_natuurlijklicht

    default:
      - *turn_off
