---
alias: areas_livingroom_lights
description: Turns the livingroom lights on when motion has been detected
mode: queued
id: c2c13dd9-a81c-4b44-a20e-990c460f9347

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - input_boolean.setting_manual_lights
      - input_select.livingroom_darklight
      - sensor.marvin_status
      - sensor.laura_status
  - platform: state
    entity_id: binary_sensor.everyone_in_bed
    to: "on"
    for:
      seconds: 30

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"
  - "{{ not is_state('media_player.apple_tv', 'playing') }}"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.everyone_in_bed
            state: "off"
          - condition: state
            entity_id: input_select.livingroom_darklight
            state: "dark"
          - condition: numeric_state
            entity_id: sensor.num_people_at_home
            above: 0
          - condition: not
            conditions:
              - condition: state
                entity_id:
                  - sensor.marvin_status
                  - sensor.laura_status
                state: "Slaapt"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.livingroom_lights_normal
            data:
              transition: 4
    default:
      - service: light.turn_off
        entity_id: group.living_room_lights
        data:
          transition: 5
