---
alias: areas_livingroom_lights
description: Turns the livingroom lights on when motion has been detected
mode: queued
id: c2c13dd9-a81c-4b44-a20e-990c460f9347
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.setting_manual_lights
      - input_boolean.livingroom_manual_control
      - binary_sensor.livingroom_is_dark
      - input_select.current_light_schedule
      - binary_sensor.presence_livingroom_couch
      - binary_sensor.presence_livingroom_dinner
      - binary_sensor.presence_livingroom_rest
      - binary_sensor.presence_kitchen
    from: ~

  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.presence_livingroom
    to: "off"
    for:
      minutes: 10

  - platform: time
    at: "19:00:00"

  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "dd93f7c049eb8e103af97459fb7aae53"
      command: "on"
    id: "hue_dimmer_on_press"

  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "dd93f7c049eb8e103af97459fb7aae53"
      command: "off_with_effect"
    id: "hue_dimmer_off_press"

  - platform: time
    at: "00:03:00"
    id: "reset"

variables:
  anchors:
    - &is_presence_detected
      alias: "Is there presence in the room?"
      condition: not
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_livingroom
          state: "off"
          for:
            minutes: 10

    - &is_presence_couch_only
      alias: "Are we just sitting in the couch area of the room?"
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_livingroom_couch
          state: "on"
        - condition: state
          entity_id: binary_sensor.presence_livingroom_dinner
          state: "off"
        - condition: state
          entity_id: binary_sensor.presence_livingroom_rest
          state: "off"
        - condition: state
          entity_id: binary_sensor.presence_kitchen
          state: "off"

    - &is_remote_pressed
      alias: "Did we manually press the button?"
      condition: trigger
      id:
        - "hue_dimmer_on_press"
        - "hue_dimmer_off_press"

    - &is_light_schedule
      alias: "Check current light schedule"
      condition: state
      entity_id: input_select.current_light_schedule

    - &is_current_scene
      alias: "Check the current light scene"
      condition: state
      entity_id: input_select.livingroom_current_lights_scene

    - &manual_control_off
      alias: "Turn manual control off"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.livingroom_manual_control

    - &manual_control_on
      alias: "Set lights downstairs as manually controlled"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.livingroom_manual_control

    - &turn_off
      alias: "Turn the lights off"
      service: light.turn_off
      target:
        entity_id:
          - light.livingroom
          - light.kitchen
      data:
        transition: 5

    - &turn_on
      alias: "Turn on the lights"
      service: scene.turn_on
      data:
        transition: 4

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Reset active scene to 'normal' during reset"
        conditions:
          - condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off
          - service: input_select.select_option
            entity_id: input_select.livingroom_current_lights_scene
            data:
              option: normal

      - alias: "Set lights as manually controlled when someone changes them"
        conditions:
          - alias: "It was changed by a user"
            condition: template
            value_template: "{{ trigger.to_state.context.user_id != None }}"
        sequence:
          - *manual_control_on

      - alias: >
          Stop automating the lights if any of the lights are manually controlled or if
          we are watching a movie.
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id:
                  - input_boolean.livingroom_manual_control
                state: "on"
              - <<: *is_current_scene
                state: "movie"
          - condition: not
            conditions:
              - *is_remote_pressed
        sequence:
          - stop: "Living room lights are manually controlled"

      - alias: "Determine if we need to turn on the lights at all"
        conditions:
          - alias: "Is it dark?"
            condition: state
            entity_id: binary_sensor.livingroom_is_dark
            state: "on"
          - *is_presence_detected
        sequence:
          - choose:
              - alias: >
                  When we press the remote and the current scene is not movie
                conditions:
                  - *is_remote_pressed
                  - not:
                      - <<: *is_current_scene
                        state: "movie"
                sequence:
                  - <<: *turn_on
                    target:
                      entity_id: scene.livingroom_lights_movie

              - alias: "When the sun has been down for a while."
                conditions:
                  - <<: *is_light_schedule
                    state: "dim"
                sequence:
                  - choose:
                      - conditions:
                          - *is_presence_couch_only
                        sequence:
                          - <<: *turn_on
                            target:
                              entity_id: scene.livingroom_lights_dim_couch_only
                    default:
                      - <<: *turn_on
                        target:
                          entity_id: scene.livingroom_lights_dim

              - alias: "When it is night"
                conditions:
                  - <<: *is_light_schedule
                    state: "night"
                sequence:
                  - <<: *turn_on
                    target:
                      entity_id: scene.livingroom_lights_night

            default:
              - choose:
                  - conditions:
                      - *is_presence_couch_only
                    sequence:
                      - <<: *turn_on
                        target:
                          entity_id: scene.livingroom_lights_normal_couch_only
                default:
                  - <<: *turn_on
                    target:
                      entity_id: scene.livingroom_lights_normal

    default:
      - *turn_off
