---
alias: areas_livingroom_lights
description: Turns the livingroom lights on when motion has been detected
mode: queued
id: c2c13dd9-a81c-4b44-a20e-990c460f9347

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - input_boolean.setting_manual_lights
      - binary_sensor.livingroom_is_dark
  - platform: state
    entity_id:
      - binary_sensor.someone_just_awake
      - binary_sensor.someone_just_home
      - binary_sensor.everyone_left_home
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.everybody_asleep
    from: "off"
    to: "on"
    id: "everyone_asleep"
  - platform: state
    entity_id:
      - light.fibaro_livingroom
      - light.fibaro_kitchen
      - light.dinner
    id: "lights"
    to: "on"
  - platform: event
    event_type: call_service
    event_data:
      domain: scene
      service: turn_on
      service_data:
        entity_id: scene.livingroom_lights_normal
    id: "scene_normal"
  # - platform: state
  #   entity_id: media_player.apple_tv
  #   to:
  #     - "paused"
  #     - "idle"
  #   for:
  #     seconds: 10
  #   id: "apple_tv_off"
  # - platform: state
  #   entity_id: media_player.apple_tv
  #   to: "playing"
  #   for:
  #     seconds: 10
  #   id: "apple_tv_on"

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Set lights as manually controlled when someone changes them"
        conditions:
          - alias: "Lights have changed"
            condition: trigger
            id: "lights"
          - alias: "It was changed by a user"
            condition: template
            value_template: "{{ trigger.to_state.context.user_id != None }}"

        sequence:
          - alias: "Set lights downstairs as manually controlled"
            service: adaptive_lighting.set_manual_control
            data:
              entity_id:
                - switch.adaptive_lighting_kitchen
                - switch.adaptive_lighting_dinner
                - switch.adaptive_lighting_living_room

      - alias: "Turn the light off when we go to sleep, even if it is manually controlled"
        conditions:
          - alias: "Everyone has gone to sleep"
            condition: trigger
            id: "everyone_asleep"

        sequence:
          - &turn_off
            alias: "Turn the lights off"
            service: light.turn_off
            data:
              entity_id: light.livingroom
              transition: 5

      - alias: "Reset manual control when the normal scene is activated"
        conditions:
          - alias: "Scene normal is activated"
            condition: trigger
            id: "scene_normal"

        sequence:
          - alias: "Set lights downstairs as not-manually controlled"
            service: adaptive_lighting.set_manual_control
            data:
              entity_id:
                - switch.adaptive_lighting_kitchen
                - switch.adaptive_lighting_dinner
                - switch.adaptive_lighting_living_room
              manual_control: false

      - alias: "Stop automating the lights if any of the lights are manually controlled"
        conditions:
          - condition: or
            conditions:
              - "{{ state_attr('switch.adaptive_lighting_dinner', 'manual_control') | length > 0 }}"
              - "{{ state_attr('switch.adaptive_lighting_kitchen', 'manual_control') | length > 0 }}"
              - "{{ state_attr('switch.adaptive_lighting_living_room', 'manual_control') | length > 0 }}"

        sequence: []

      - conditions:
          - condition: state
            entity_id: binary_sensor.livingroom_is_dark
            state: "on"
          - condition: numeric_state
            entity_id: sensor.num_people_at_home
            above: 0
          - condition: or
            conditions:
              - condition: state
                entity_id:
                  - binary_sensor.someone_just_awake
                state: "on"
              - condition: state
                entity_id:
                  - binary_sensor.someone_awake
                state: "on"
          # - condition: or
          #   conditions:
          #     - condition: state
          #       entity_id:
          #         - media_player.apple_tv
          #       state:
          #         - "paused"
          #         - "idle"
          #         - "unknown"
          #         - "off"
          #     - condition: and
          #       conditions:
          #         - condition: state
          #           entity_id:
          #             - media_player.apple_tv
          #           state: "playing"
          #         - condition: state
          #           entity_id:
          #             - media_player.apple_tv
          #           attribute: "app_name"
          #           state:
          #             - "YouTube"
          #             - "CanalDigitaal"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.livingroom_lights_normal
            data:
              transition: 4

      - conditions:
          - condition: trigger
            id: "apple_tv_on"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.livingroom_lights_movie
            data:
              transition: 4

    default:
      - *turn_off
