---
alias: areas_livingroom_music_off
description: Automatically stop the music when everyone has left
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.everyone_left_home
    to: 'on'
action:
  - service: media_player.media_pause
    data:
      entity_id: media_player.sonos_livingroom