---
alias: areas_livingroom_play_music
description: Ask to play music based on several triggers
mode: single
id: 6650b4da-9774-4b59-8157-492a21704636

trigger:
  - platform: state
    entity_id: sensor.marvin_status
    from: 'Weg'
    to: 'Net thuis'
  - platform: state
    entity_id: sensor.marvin_work_status
    to: 'Niet aan het werk'

condition:
  - condition: state
    entity_id: sensor.marvin_work_status
    state: 'Niet aan het werk'
  - condition: time
    before: '22:00:00'
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.workday
        state: 'off'
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday
            state: 'on'
          - condition: time
            after: '16:30:00'

action:
  - service: script.cn_play_music