---
description: >
  Automatically play music in the living room
alias: areas_livingroom_play_music
id: bdbbd6e8-fb02-4777-980e-dffd9865995c
mode: single
trace:
  stored_traces: 25

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_house
    to: "on"

  - platform: state
    entity_id:
      - input_select.livingroom_room_mode

  - platform: state
    entity_id:
      - media_player.living_room_android
    to: "off"
    for:
      minutes: 7

  - platform: state
    entity_id: binary_sensor.presence_house
    to: "off"
    for:
      seconds: 900

  - platform: state
    entity_id:
      - media_player.living_room_android
    to: "on"
    id: "tv_input_selected"

  - platform: homeassistant
    event: start

  - platform: state
    entity_id:
      - input_boolean.setting_automatic_music
    id: "setting_automatic_music"

  - platform: time
    at:
      - "07:00:00"
      - "21:30:00"

variables:
  mass_entity: '{{ states("sensor.mass_media_entity") }}'
  anchors:
    - &play_media
      alias: "Start playing music on the master group"
      service: media_player.media_play
      data: {}
      target:
        entity_id: "{{ mass_entity }}"

    - &pause
      alias: "Pause the player"
      service: media_player.media_pause
      data: {}
      target:
        entity_id: "{{ mass_entity }}"

action:
  - choose:
      - conditions:
          - or:
              - condition: time
                after: "21:30:00"
              - condition: time
                before: "07:00:00"
        sequence:
          - *pause

      - conditions:
          - condition: state
            entity_id:
              - binary_sensor.presence_house
              - input_boolean.setting_automatic_music
            state: "on"
          - alias: "Time must be between reasonable hours"
            condition: time
            after: "07:00:00"
            before: "21:30:00"
          - alias: "We're not watching TV"
            condition: state
            entity_id:
              - media_player.living_room_android
            state: "off"
          - "{{ not is_state(mass_entity, 'playing') }}"
          - not:
              - condition: state
                entity_id:
                  - input_select.livingroom_room_mode
                state: "Slaap"
          - not:
              - condition: trigger
                id: "tv_input_selected"
        sequence:
          - *play_media
          - delay:
              seconds: 10

      - conditions:
          - or:
              - alias: "No presence is detected"
                condition: state
                entity_id:
                  - binary_sensor.presence_house
                state: "off"
                for:
                  seconds: 900
              - alias: "Or we switched off automatic music"
                and:
                  - condition: trigger
                    id: "setting_automatic_music"
                  - condition: state
                    entity_id:
                      - input_boolean.setting_automatic_music
                    state: "off"
              - condition: trigger
                id: "tv_input_selected"
          - "{{ not is_state(mass_entity, 'off') }}"
        sequence:
          - *pause
