---
description: >
  Automatically play music in the living room
alias: areas_livingroom_play_music
id: bdbbd6e8-fb02-4777-980e-dffd9865995c

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_house
      - binary_sensor.presence_livingroom
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_house
    to: "off"
    for:
      seconds: 900

  - platform: state
    entity_id:
      - media_player.apple_tv
    from:
      - "paused"
      - "playing"
    to:
      - "idle"
      - "standby"
      - "off"
      - "unavailable"
    for:
      minutes: 2

  - platform: state
    entity_id:
      - media_player.apple_tv
    from:
      - "playing"
    to:
      - "paused"
    for:
      minutes: 20

  - platform: homeassistant
    event: start

  - platform: state
    entity_id:
      - input_boolean.setting_automatic_music
    id: "setting_automatic_music"

variables:
  anchors:
    - &play_media
      alias: "Start playing music on the master group"
      service: media_player.media_play
      data: {}
      target:
        entity_id: media_player.mass_sonos_livingroom

    - &pause
      alias: "Pause the player"
      service: media_player.media_pause
      data: {}
      target:
        entity_id: media_player.mass_sonos_livingroom

action:
  - choose:
      - conditions:
          - condition: state
            entity_id:
              - binary_sensor.presence_house
              - input_boolean.setting_automatic_music
            state: "on"
          - alias: "Time must be between reasonable hours"
            condition: time
            after: "07:00:00"
            before: "21:00:00"
          - alias: "We are actually awake"
            condition: state
            entity_id:
              - binary_sensor.house_mode_everyone_asleep
            state: "off"
          - alias: "We're not watching TV"
            condition: or
            conditions:
              - condition: state
                entity_id: media_player.apple_tv
                state:
                  - "idle"
                  - "standby"
                  - "off"
                  - "unavailable"
                for:
                  minutes: 2
              - condition: state
                entity_id: media_player.apple_tv
                state: "paused"
                for:
                  minutes: 20
          - not:
              - condition: state
                entity_id:
                  - media_player.mass_sonos_livingroom
                state: "playing"
        sequence:
          - *play_media

      - conditions:
          - or:
              - alias: "No presence is detected"
                condition: state
                entity_id:
                  - binary_sensor.presence_house
                state: "off"
                for:
                  seconds: 900
              - alias: "Or we switched of automatic music"
                and:
                  - condition: trigger
                    id: "setting_automatic_music"
                  - condition: state
                    entity_id:
                      - input_boolean.setting_automatic_music
                    state: "off"
          - not:
              - condition: state
                entity_id:
                  - media_player.mass_sonos_livingroom
                state: "off"
        sequence:
          - *pause
