---
description: >
  Automatically play music in the living room
alias: areas_livingroom_play_music
id: bdbbd6e8-fb02-4777-980e-dffd9865995c
trace:
  stored_traces: 25

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_house
      - binary_sensor.presence_livingroom
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.house_mode_everyone_at_home_working

  - platform: state
    entity_id:
      - media_player.sony_kd_65a1
    to: "on"

  - platform: state
    entity_id:
      - media_player.sony_kd_65a1
    to: "off"
    for:
      minutes: 1

  - platform: state
    entity_id: binary_sensor.presence_house
    to: "off"
    for:
      seconds: 900

  - platform: homeassistant
    event: start

  - platform: state
    entity_id:
      - input_boolean.setting_automatic_music
    id: "setting_automatic_music"

variables:
  anchors:
    - &play_media
      alias: "Start playing music on the master group"
      service: media_player.media_play
      data: {}
      target:
        entity_id: media_player.mass_sonos_livingroom

    - &pause
      alias: "Pause the player"
      service: media_player.media_pause
      data: {}
      target:
        entity_id: media_player.mass_sonos_livingroom

action:
  - choose:
      - conditions:
          - condition: state
            entity_id:
              - binary_sensor.presence_house
              - input_boolean.setting_automatic_music
            state: "on"
          - alias: "Time must be between reasonable hours"
            condition: time
            after: "07:00:00"
            before: "21:00:00"
          - alias: "We are actually awake"
            condition: state
            entity_id:
              - binary_sensor.house_mode_everyone_asleep
            state: "off"
          - alias: "We're not watching TV"
            condition: state
            entity_id:
              - media_player.sony_kd_65a1
            state: "off"
          - alias: "No need for music when everyone is working from home"
            condition: state
            entity_id:
              - binary_sensor.house_mode_everyone_at_home_working
            state: "off"
          - or:
              - not:
                  - condition: state
                    entity_id:
                      - media_player.mass_sonos_livingroom
                    state: "playing"
              - and:
                  - condition: state
                    entity_id:
                      - media_player.mass_sonos_livingroom
                    state: "playing"
                  - condition: state
                    entity_id:
                      - media_player.mass_sonos_livingroom
                    attribute: "media_title"
                    state: "TV"
        sequence:
          - *play_media

      - conditions:
          - or:
              - alias: "No presence is detected"
                condition: state
                entity_id:
                  - binary_sensor.presence_house
                state: "off"
                for:
                  seconds: 900
              - alias: "Or we switched off automatic music"
                and:
                  - condition: trigger
                    id: "setting_automatic_music"
                  - condition: state
                    entity_id:
                      - input_boolean.setting_automatic_music
                    state: "off"
              - alias: "Or everyone at home is working"
                condition: state
                entity_id:
                  - binary_sensor.house_mode_everyone_at_home_working
                state: "on"
          - not:
              - condition: state
                entity_id:
                  - media_player.mass_sonos_livingroom
                state: "off"
        sequence:
          - *pause
