---
description: >
  Actions configured for my hue dimmer switch
alias: areas_livingroom_remote
id: e9286dec-edd9-435c-9fe1-e67dbe43e8b4

trigger:
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "dd93f7c049eb8e103af97459fb7aae53"
      command: "on_press"
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "dd93f7c049eb8e103af97459fb7aae53"
      command: "off_press"

action:
  # Switch from scene 'normal' to 'movie' or 'any scene' to 'normal'
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.livingroom_current_scene
            state: "normal"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.livingroom_lights_movie
            data:
              transition: 4
    default:
      - service: scene.turn_on
        entity_id: scene.livingroom_lights_normal
        data:
          transition: 2
