---
description: Activate movie scene
alias: areas_living_room_scene_movie
mode: single
trigger: 
  - platform: webhook
    webhook_id: flic_livingroom_single
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
  - platform: state
    entity_id: media_player.kodi
    to: 'playing'
condition:
  - condition: or
    conditions:
      # Do not automatically switch from candle scene, since it's a manual scene
      - "{{ not is_state('input_select.livingroom_current_scene', 'candle') }}"
      - "{{ trigger.platform == 'webhook' }}"
  - "{{ not is_state('input_select.livingroom_current_scene', 'movie') }}"
  - condition: or
    conditions:
      - "{{ trigger.platform == 'webhook' }}"
      - condition: and
        conditions:
          - condition: state
            entity_id: media_player.living_room_tv
            state: 'playing'
          - condition: state
            entity_id: media_player.living_room_tv
            attribute: app_name
            state: "Netflix"
      - condition: state
        entity_id: media_player.kodi
        state: 'playing'      
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_current_scene
      option: movie
