---
description: Activate candle scene
alias: areas_living_room_scene_candle
mode: single
trigger: 
  - platform: webhook
    webhook_id: flic_livingroom_candle
condition:
  - "{{ not is_state('input_select.livingroom_current_scene', 'candle') }}"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_current_scene
      option: candle
