---
description: Activate movie scene
alias: areas_living_room_scene_normal
mode: single
trigger: 
  - platform: webhook
    webhook_id: flic_livingroom_single
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    for: '00:00:03'
  - platform: state
    entity_id: media_player.kodi
    to: 'playing'
condition:
  - "{{ not is_state('variable.livingroom_current_scene', 'movie') }}"
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: media_player.living_room_tv
            state: 'playing'
          - condition: state
            entity_id: media_player.living_room_tv
            attribute: app_name
            state: "Netflix"
      - condition: state
        entity_id: media_player.kodi
        state: 'playing'      
action:
  - service: variable.set_variable
    data:
      variable: livingroom_current_scene
      value: 'movie'