---
description: Activate normal scene
alias: areas_living_room_scene_normal
mode: single
trigger: 
  - platform: webhook
    webhook_id: flic_livingroom_double
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'paused'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'standby'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'idle'
  - platform: time
    at: '14:00:00'
condition:
  - condition: or
    conditions:
      # Do not automatically switch from candle scene, since it's a manual scene, except at 14:00 (reset time) or when triggered by flic button
      - "{{ not is_state('input_select.livingroom_current_scene', 'candle') }}"
      - "{{ trigger.platform == 'webhook' }}"
      - "{{ trigger.platform == 'time' }}"
  - "{{ not is_state('input_select.livingroom_current_scene', 'normal') }}"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_current_scene
      option: normal