---
alias: areas_livingroom_scene_movie
description: Turns on the movie scene
mode: single
id: 82133d27-d001-427b-856f-92a0d4f13613

trigger:
  - platform: state
    entity_id: media_player.apple_tv
    to: "playing"
    for:
      seconds: 10

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - service: scene.turn_on
    target:
      entity_id: scene.livingroom_lights_movie
    data:
      transition: 4
