---
description: "Set a variable to light to keep track of whether it is light or dark"
alias: areas_livingroom_set_to_light
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_kitchen_luminance") | int > 20 and is_state("light.fibaro_kitchen", "off") }}'
    for:
      seconds: 60
  - platform: numeric_state
    entity_id: sensor.pir_kitchen_luminance
    above: 95

condition:
  condition: or
  conditions:
    - '{{ states("sensor.pir_kitchen_luminance") | int > 20 and is_state("light.fibaro_kitchen", "off") }}'
    - condition: numeric_state
      entity_id: sensor.pir_kitchen_luminance
      above: 95

action:
  service: variable.set_variable
  data:
    variable: livingroom_darklight
    value: 'light'