---
alias: areas_livingroom_tv_off
description: Automatically turn off the TV to save power
mode: queued
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'standby'    
    for:
      minutes: 5
action:
  - service: media_player.turn_off
    entity_id: media_player.living_room_tv