---
alias: areas_livingroom_tv_off
description: Automatically turn off the TV to save power
mode: queued
id: 62d6decd-ccf6-4379-a3b0-00239e704892

trigger:
  - platform: state
    entity_id: media_player.apple_tv
    to:
      - "standby"
      - "off"
      - "paused"
      - "idle"
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.everyone_left_home
    to: "on"

condition:
  - alias: "Do not automate when a guest is over"
    condition: state
    entity_id:
      - input_boolean.setting_guest_mode
    state: "off"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id:
              - media_player.sony_kd_65a1
            attribute: media_title
            state: "HDMI 3/ARC"
        sequence:
          - service: media_player.turn_off
            entity_id: media_player.sony_kd_65a1
