---
description: Turn on our Roborock when we have left our house or when we are working from home
alias: areas_livingroom_vacuum_on
mode: queued
id: 11f981e7-b67c-47c3-ba3b-f51ef83a9414

variables:
  hours_since_last_clean: >
    {{ (
          (
            as_timestamp(states('sensor.norby_last_cleaned')) - as_timestamp(now()) 
          ) 
          / -3600
        ) | float 
    }}

trigger:
  - platform: state
    entity_id:
      - binary_sensor.everyone_left_home
      - binary_sensor.house_mode_everyone_at_home_working

condition:
  - "{{ hours_since_last_clean > 12.0 }}"
  - condition: time
    after: "07:30:00"
    before: "22:00:00"

action:
  - service: vacuum.start
    data:
      entity_id: vacuum.norby
