---
description: >
  Turn on our Roborock when we have left our house or when we are working from home
alias: areas_livingroom_vacuum_on
mode: queued
id: 11f981e7-b67c-47c3-ba3b-f51ef83a9414

variables:
  hours_since_last_clean: >
    {{ (
          (
            as_timestamp(states('sensor.norby_last_clean_end')) - as_timestamp(now())
          )
          / -3600
        ) | float
    }}
  anchors:
    - &start
      alias: "Start cleaning"
      service: vacuum.start
      data:
        entity_id: vacuum.norby

    - &return
      alias: "Return to base"
      service: vacuum.return_to_base
      data:
        entity_id: vacuum.norby

trigger:
  - platform: state
    entity_id:
      - binary_sensor.everyone_left_home
      - binary_sensor.house_mode_everyone_at_home_working
    from: "off"
    to: "on"
    for:
      minutes: 2

  - platform: state
    entity_id:
      - binary_sensor.everyone_left_home
      - binary_sensor.house_mode_everyone_at_home_working
    from: "on"
    to: "off"

  - platform: state
    entity_id:
      - input_boolean.setting_guest_mode

action:
  - choose:
      - conditions:
          - "{{ hours_since_last_clean > 12.0 }}"
          - condition: time
            after: "07:30:00"
            before: "22:00:00"
          - condition: state
            entity_id:
              - binary_sensor.everyone_left_home
              - binary_sensor.house_mode_everyone_at_home_working
            state: "on"
            match: any
          - alias: "Do not automate when a guest is over"
            condition: state
            entity_id:
              - input_boolean.setting_guest_mode
            state: "off"
        sequence:
          - *start

      - conditions:
          - condition: state
            entity_id:
              - vacuum.norby
            state: "cleaning"
        sequence:
          - *return

    default: []
