---
description: Mark person as away 10 minutes after leaving
alias: presence_away
mode: single
id: 3fb50eae-6c01-4048-81af-429f20854158

trigger:
  - platform: state
    entity_id: input_select.marvin_status_dropdown
    to: 'Net weg'
    for:
      minutes: 10
  - platform: state
    entity_id: input_select.laura_status_dropdown
    to: 'Net weg'
    for:
      minutes: 10

action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'input_select.marvin_status_dropdown' %}
          input_select.marvin_status_dropdown
        {% else %}
          input_select.laura_status_dropdown
        {% endif %}
      option: Weg