---
description: Mark a person as Just Arrived when he/she gets home
alias: presence_just_arrived
mode: queued
trigger:
  - platform: state
    entity_id: device_tracker.ms_iphonexs
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.laura_la
    from: 'not_home'
    to: 'home'
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'device_tracker.ms_iphonexs' %}
          input_select.marvin_status_dropdown
        {% else %}
          input_select.laura_status_dropdown
        {% endif %}
      option: Net thuis