---
description: Mark a person as Just Arrived when he/she gets home
alias: presence_just_arrived
mode: queued
id: e72f181f-3840-472d-9529-db7a65ddd71b

trigger:
  - platform: state
    entity_id: person.marvin
    from: "not_home"
    to: "home"
  - platform: state
    entity_id: person.laura
    from: "not_home"
    to: "home"

action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'person.marvin' %}
          input_select.marvin_status_dropdown
        {% else %}
          input_select.laura_status_dropdown
        {% endif %}
      option: Net thuis
