---
description: Mark person as just left based on the device tracker
alias: presence_just_left
mode: single
id: 388b4902-87a3-4312-9f98-5a81fd720a9c

trigger:
  - platform: state
    entity_id: person.marvin
    from: "home"
    to: "not_home"
  - platform: state
    entity_id: person.laura
    from: "home"
    to: "not_home"

action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'person.marvin' %}
          input_select.marvin_status_dropdown
        {% else %}
          input_select.laura_status_dropdown
        {% endif %}
      option: Net weg
