---
description: Mark Laura as just awake based on flic button double click
alias: presence_laura_just_awake
mode: single
trigger: 
  - platform: webhook
    webhook_id: laura_awake
  - platform: state
    entity_id: variable.bedroom_darklight
    to: "light"
  - platform: template
    value_template: "{{ states('sensor.date_time') == (as_timestamp(states.sensor.rne_l21_volgende_alarm.state))| timestamp_custom('%Y-%m-%d, %H:%M', True) }}"
condition:
  condition: state
  entity_id: input_select.laura_sleep_status_dropdown
  state: 'Slaapt'
action:
  - choose:
      - conditions:
          - "{{ trigger.platform == 'template' }}"
        sequence:
          # Give her 5 more minutes after her alarm before the lights burn her eyes
          - delay:
              minutes: 5
          - service: input_select.select_option
            data:
              entity_id: input_select.laura_sleep_status_dropdown
              option: 'Net wakker'
    default:
      - service: input_select.select_option
        data:
          entity_id: input_select.laura_sleep_status_dropdown
          option: 'Net wakker'