---
description: Mark Laura as just awake based on flic button double click
alias: presence_laura_just_awake
mode: single
id: a8abbc27-211f-4bae-bc44-013d8735e6c9

trigger:
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "92cb556d8bab10f8b49ae0ed3e8dbe32"
      command: "hold"
    id: "button"

  - platform: state
    entity_id:
      - sensor.iphone_van_l_a_floors_ascended
      - sensor.iphone_van_l_a_floors_descended
    id: "laura_floor_activity"

  - platform: state
    entity_id:
      - sensor.iphone_van_l_a_activity
    not_to:
      - Unknown
      - Stationary
    id: "laura_activity"

variables:
  anchors:
    - &laura_just_awake
      alias: "Set Laura to just awake"
      service: input_select.select_option
      data:
        entity_id: input_select.laura_sleep_status_dropdown
        option: "Net wakker"

    - &time_check
      alias: "Check if it is within the window of waking up"
      condition: time
      after: "07:15:00"
      before: "15:00:00"

    - &laura_asleep
      alias: "Check if I am asleep, only then we want to trigger this"
      condition: state
      entity_id: input_select.laura_sleep_status_dropdown
      state: "Slaapt"

condition: []

action:
  - choose:
      - alias: "Check if the alarm triggered in the morning"
        conditions:
          - "{{ not trigger.platform }}"
          - *time_check
          - *laura_asleep
        sequence:
          - *laura_just_awake

      - alias: "Check of we pressed the bedside button"
        conditions:
          - condition: trigger
            id: "button"
          - *time_check
          - *laura_asleep
        sequence:
          - *laura_just_awake

      - alias: "Check if the phone detected activity"
        conditions:
          - or:
              - condition: trigger
                id: "laura_activity"
              - and:
                  - condition: trigger
                    id: "laura_floor_activity"
                  - or:
                      - condition: numeric_state
                        entity_id:
                          - sensor.iphone_van_l_a_floors_ascended
                        above: 0
                      - condition: numeric_state
                        entity_id:
                          - sensor.iphone_van_l_a_floors_descended
                        above: 0
          - *laura_asleep
          - *time_check
        sequence:
          - *laura_just_awake

    default: []
