---
description: Call the scripts to set us to asleep or turn the light on or off (ugly i know)
alias: presence_laura_asleep
mode: single
trigger: 
  - platform: webhook
    webhook_id: flic_bed_right
action:
  - service: script.turn_on
    entity_id: script.webhook_marvin_laura_asleep
  - service: script.turn_on
    entity_id: script.webhook_flic_right_on
  - service: script.turn_on
    entity_id: script.webhook_flic_right_off