---
description: Set Laura to 'asleep' using the bedsensor or the ikea button
alias: presence_laura_asleep
mode: single
id: 74e6a9f0-54ad-412c-9d23-1c87a9de1053

trigger:
  - platform: state
    entity_id: binary_sensor.everyone_in_bed
    to: "on"
    for:
      seconds: 60
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "92cb556d8bab10f8b49ae0ed3e8dbe32"
      command: "single"

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.laura_sleep_status_dropdown
      option: "Slaapt"
