---
description: >
  Mark Marvin as just awake based on
  - Aqara button
  - Curtains being open
alias: presence_marvin_just_awake
mode: single
id: 0069afb3-adb3-433c-beff-107c17508dbd

trigger:
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "2a93e9d147b93ca0ec5992d48dde3129"
      command: "hold"
    id: "button"

  - platform: state
    entity_id:
      - sensor.marvins_iphone_13_floors_ascended
      - sensor.marvins_iphone_13_floors_descended
    id: "marvin_floor_activity"

  - platform: state
    entity_id:
      - sensor.marvins_iphone_13_activity
    not_to:
      - Unknown
      - Stationary
    id: "marvin_activity"

variables:
  anchors:
    - &marvin_just_awake
      alias: "Set Marvin to just awake"
      service: input_select.select_option
      data:
        entity_id: input_select.marvin_sleep_status_dropdown
        option: "Net wakker"

    - &time_check
      alias: "Check if it is within the window of waking up"
      condition: time
      after: "06:00:00"
      before: "15:00:00"

    - &marvin_asleep
      alias: "Check if I am asleep, only then we want to trigger this"
      condition: state
      entity_id: input_select.marvin_sleep_status_dropdown
      state: "Slaapt"

condition: []

action:
  - choose:
      - alias: "Check if the alarm triggered in the morning"
        conditions:
          - "{{ not trigger.platform }}"
          - *time_check
          - *marvin_asleep
        sequence:
          - *marvin_just_awake

      - alias: "Check of we pressed the bedside button"
        conditions:
          - condition: trigger
            id: "button"
          - *time_check
          - *marvin_asleep
        sequence:
          - *marvin_just_awake

      - alias: "Check if the phone detected activity"
        conditions:
          - or:
              - condition: trigger
                id: "marvin_activity"
              - and:
                  - condition: trigger
                    id: "marvin_floor_activity"
                  - or:
                      - condition: numeric_state
                        entity_id:
                          - sensor.marvins_iphone_13_floors_ascended
                        above: 0
                      - condition: numeric_state
                        entity_id:
                          - sensor.marvins_iphone_13_floors_descended
                        above: 0
          - *time_check
          - *marvin_asleep
        sequence:
          - *marvin_just_awake

    default: []
