---
description: Set Marvin to 'asleep' using the bedsensor or the ikea button
alias: presence_marvin_asleep
mode: single
id: 1da4e30e-26fe-416a-ba06-aee16ec18ff3

trigger:
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "2a93e9d147b93ca0ec5992d48dde3129"
      command: "single"

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.marvin_sleep_status_dropdown
      option: "Slaapt"
  - service: input_select.select_option
    data:
      entity_id: input_select.laura_sleep_status_dropdown
      option: "Slaapt"
