---
description: >
  Mark Marvin as just awake based on
  - Ikea button
  - Curtains being open
alias: presence_marvin_just_awake
mode: single
id: 0069afb3-adb3-433c-beff-107c17508dbd

trigger: 
  - platform: webhook
    webhook_id: marvin_awake
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "17083e33c8be814f6656f6d43be15909"
      command: "move_with_on_off"

condition:
  condition: state
  entity_id: input_select.marvin_sleep_status_dropdown
  state: 'Slaapt'

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.marvin_sleep_status_dropdown
      option: 'Net wakker'