---
description: Set Marvin to 'asleep' using the bedsensor or the ikea button
alias: presence_marvin_asleep
mode: single
id: 1da4e30e-26fe-416a-ba06-aee16ec18ff3

trigger:
  - platform: state
    entity_id: binary_sensor.everyone_in_bed
    to: "on"
    for:
      seconds: 60
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "17083e33c8be814f6656f6d43be15909"
      command: "on"

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.marvin_sleep_status_dropdown
      option: "Slaapt"
  - service: input_select.select_option
    data:
      entity_id: input_select.laura_sleep_status_dropdown
      option: "Slaapt"
