---
description: Mark Marvin as just awake based on flic button double click
alias: presence_marvin_just_awake
mode: single
trigger: 
  - platform: webhook
    webhook_id: marvin_awake
  - platform: template
    value_template: '{{ states("sensor.pir_bedroom_luminance") | int > 50 and is_state("light.bedside_left", "off") }}'
    for:
      seconds: 60
condition:
  condition: state
  entity_id: input_select.marvin_sleep_status_dropdown
  state: 'Slaapt'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.marvin_sleep_status_dropdown
      option: 'Net wakker'