---
description: >
  Toggle Zoey between asleep / awake when using the NS Panel
alias: presence_zoey_sleep
mode: queued
id: 6572e77f-55a9-4e6b-a959-42748ca6e242

trigger:
  - platform: state
    entity_id:
      - switch.nspanel_master_bedroom_relay_2
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"
    id: "nspanel_right"
  - platform: state
    entity_id:
      - switch.nspanel_master_bedroom_relay_1
    from:
      - "off"
      - "on"
    to:
      - "off"
      - "on"
    id: "nspanel_left"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "nspanel_left"
        sequence:
          - service: input_select.select_option
            entity_id: input_select.zoey_sleep_status_dropdown
            data:
              option: "Slaapt boven"
          - service: scene.turn_on
            data:
              entity_id: scene.bedroom_cover_ventilatingnight

      - conditions:
          - condition: trigger
            id: "nspanel_right"
        sequence:
          - service: scene.turn_on
            data:
              entity_id: scene.bedroom_cover_halfclosed
          - delay:
              minutes: 1
          - service: input_select.select_option
            entity_id: input_select.zoey_sleep_status_dropdown
            data:
              option: "Wakker"

    default: []
