# {{  "media_player.mass_all_devices_beta"
#     if (
#       is_state("media_player.mass_all_devices", "unavailable")
#       or (
#         not is_state("media_player.mass_all_devices_beta", "unavailable")
#         and states("media_player.mass_all_devices_beta") != "unknown"
#       )
#     )
#     else "media_player.mass_all_devices" }}
---
sensor:
  - name: mass_media_entity
    state: "media_player.mass_sonos_kitchen"
