---
trigger:
  - platform: state
    entity_id: input_select.master_bedroom_room_mode
  - platform: state
    entity_id: binary_sensor.presence_master_bedroom
    to: "on"
  - platform: state
    entity_id: binary_sensor.presence_master_bedroom
    to: "off"
    for:
      seconds: 60

sensor:
  - name: nspanel_bedroom_brightness
    unique_id: a53a609c-724c-45dd-a004-c4722dad0077
    state: >
      {%-
        if not is_state("input_select.master_bedroom_room_mode", "Wakker")
        or is_state("binary_sensor.presence_master_bedroom", "off")
      -%}
      {{ 0 | int }}
      {%-
        elif is_state("binary_sensor.master_bedroom_is_dark","on")
      -%}
      {{ 50 | int }}
      {%- else -%}
      {{ 100 | int }}
      {%- endif -%}
