---
sensor:
  unique_id: sidebar
  state: template
  attributes:
    time: |
      {%- set hours = '<span>' + now().strftime('%H') + '<span>' %}
      {%- set minutes = '</span>' + now().strftime('%M') + '</span>' %}
      {{ hours }}:{{ minutes }}
    date: |
      <font color='#6a7377'><b>
      {%- if strptime(states('sensor.date'), '%Y-%m-%d').day != null %}
      {%- set days = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag'] %}
      {%- set months = ['Januari', 'Februari', 'Maart', 'April', 'Mei', 'Juni', 
      'Juli', 'Augustus', 'September', 'Oktober', 'November', 'December'] %}
        {{- days[now().weekday()] }}<br>
        {{- strptime(states('sensor.date'), '%Y-%m-%d').day }} {{ months[now().month-1] }}
      {%- endif -%}
      </b></font>
    greet: |
      <b>
      {%- set time = now().hour %}
      {%- if time <= 1 -%} Goedenacht {{'\U0001F611'}}
      {%- elif time <= 3 -%} Goedenacht {{'\U0001F62A'}}
      {%- elif time <= 5 -%} Goedenacht {{'\U0001F634'}}
      {%- elif time <= 7 -%} Goedemorgen {{'\U0001F4A9'}}
      {%- elif time <= 9 -%} Goedemorgen {{'\u2615\uFE0F'}}
      {%- elif time <= 12 -%} Goedemorgen {{'\U0001F642'}}
      {%- elif time <= 13 -%} Goedemiddag {{'\U0001F60A'}}
      {%- elif time <= 15 -%} Goedemiddag {{'\U0001F60E'}}
      {%- elif time <= 17 -%} Goedemiddag {{'\U0001F44B\U0001F3FB'}}
      {%- elif time <= 19 -%} Goedenavond {{'\U0001F44B\U0001F3FB'}}
      {%- elif time <= 22 -%} Goedenavond {{'\U0001F60C'}}
      {%- elif time <= 23 -%} Goedenavond {{'\U0001F974'}}
      {%- else %} Goedenavond {{'\U0001F974'}}
      {%- endif -%}
      </b>
    vacuum: |
      {% set entity_id = 'vacuum.norby' %}
      {%- if is_state(entity_id, 'cleaning') -%}
        <b>Norby is aan het schoonmaken</b>
      {%- elif is_state(entity_id, 'norby') -%}
        <b>Norby gaat terug naar zijn hok</b>
      {%- endif %}
