---
sensor:
  - name: sun_elevation
    unique_id: 4da7f7fc-ef16-4c6d-ae79-f7f14bf592af
    unit_of_measurement: "°"
    state_class: measurement
    availability: "{{ state_attr('sun.sun', 'elevation') is number }}"
    state: "{{ state_attr('sun.sun', 'elevation') }}"
