---
alias: areas_mancave_blinds
description: >
  Control the blinds in the mancave (which are facing south) by using 
   - Sun elevation
   - The solar panels (indicating a hot day)
mode: queued
max_exceeded: silent
id: c5bc22e2-4499-4fb6-9ff1-1985efa93118

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      # Include auto-shut blinds on hot days
      - binary_sensor.sun_should_close_south_blinds
      - binary_sensor.sun_at_south_windows
      - media_player.mancave_tv
      - input_boolean.setting_manual_blinds
      - sensor.marvin_work_status
  # Sun
  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    below: 12.0
  - platform: numeric_state
    entity_id:
      - sensor.sun_azimuth
    above: 200

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      # TV is on or sun is hot -> Fully closed
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id:
                  - binary_sensor.sun_should_close_south_blinds
                state: "on"
              - condition: state
                entity_id:
                  - media_player.mancave_tv
                state: "on"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.mancave_cover_closed

      # Sun is shining at my screen when I am working
      - conditions:
          - condition: numeric_state
            entity_id:
              - sensor.sun_elevation
            below: 15.0
          - condition: numeric_state
            entity_id:
              - sensor.sun_azimuth
            above: 200
          - condition: state
            entity_id:
              - binary_sensor.sun_at_south_windows
            state: "on"
          - condition: state
            entity_id:
              - sensor.marvin_work_status
            state: "Aan het werk"
          - condition: numeric_state
            entity_id: sensor.buienradar_irradiance
            above: 150

        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.mancave_cover_tophalfopen

      # Sun is nearly down or I am working -> Half closed
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id:
                  - sensor.sun_elevation
                below: 1.0
              - condition: state
                entity_id:
                  - sensor.marvin_work_status
                state: "Aan het werk"

        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.mancave_cover_halfclosed

    # Otherwise -> Half open
    default:
      - service: scene.turn_on
        target:
          entity_id: scene.mancave_cover_halfopen
