description: Set volume of sonos based on the music schedule
alias: areas_mancave_speakers_set_volume
mode: queued
max_exceeded: silent

variables:
  just_awake_volume: 8
  early_morning_volume: 10
  morning_volume: 11
  day_volume: 13
  evening_volume: 8
  sonos: media_player.mass_mancave_wiim_amp
  mass_entity_suffix: |
    {{ "" if is_state("media_player.mass_all_devices", "unavailable") else "" }}
  mass_entity: "{{ sonos + mass_entity_suffix }}"
  music_schedule: |
    {{ states('input_select.current_music_schedule') }}

triggers:
  - trigger: state
    entity_id:
      - input_select.current_music_schedule
      - input_boolean.setting_automatic_music

conditions:
  - alias: Only control the volume when we are automating the music
    condition: state
    entity_id: input_boolean.setting_automatic_music
    state: "on"
  - condition: and
    conditions: []

actions:
  - variables:
      schedule_volume: |
        {% if music_schedule == "just_awake" %}
          {{ just_awake_volume }}
        {% elif music_schedule == "early_morning" %}
          {{ early_morning_volume }}
        {% elif music_schedule == "morning" %}
          {{ morning_volume }}
        {% elif music_schedule == "day" %}
          {{ day_volume }}
        {% elif music_schedule == "evening" %}
          {{ evening_volume }}
        {% else %}
          0
        {% endif %}
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ false }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ \"is_volume_muted\" in states[mass_entity].attributes }}"
            then:
              - action: media_player.volume_mute
                target:
                  entity_id: "{{ mass_entity }}"
                data:
                  is_volume_muted: true
            else:
              - action: media_player.volume_set
                target:
                  entity_id: "{{ mass_entity }}"
                data:
                  volume_level: 0
      - conditions:
          - condition: template
            value_template: "{{ schedule_volume | int > 0 }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ \"is_volume_muted\" in states[mass_entity].attributes }}"
            then:
              - action: media_player.volume_mute
                target:
                  entity_id: "{{ mass_entity }}"
                data:
                  is_volume_muted: false
          - action: media_player.volume_set
            target:
              entity_id: "{{ mass_entity }}"
            data:
              volume_level: "{{ schedule_volume | int / 100.0 }}"