---
alias: areas_hall_upstairs_lights_off
description: Turns the hallway lights on when motion has been detected or when we go to sleep
mode: single

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_hall_upstairs
    to: 'off'
    for: 
      seconds: 120
  - platform: state
    entity_id:
      - sensor.marvin_status
      - sensor.laura_status
    to: 'Slaapt'

condition:
  - condition: state
    entity_id: light.fibaro_hall_upstairs
    state: 'on'
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: 'off'
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.presence_hall_upstairs
        state: 'off'
        for:
          seconds: 120
      - condition: state
        entity_id: sensor.marvin_status
        state: 'Slaapt'
      - condition: state
        entity_id: sensor.laura_status
        state: 'Slaapt'

action:
  - service: light.turn_off
    data:
      entity_id: light.fibaro_hall_upstairs