---
alias: areas_hall_upstairs_lights
description: Turns the hallway lights on when motion has been detected
mode: queued
id: 1bc47338-f273-4ec5-b45f-ca05d19434d5

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_hall_upstairs
    to: "on"
  - platform: state
    entity_id: binary_sensor.presence_hall_upstairs
    to: "off"
    for:
      seconds: 60
  - platform: state
    entity_id:
      - input_select.current_light_schedule

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - &presence
            condition: state
            entity_id: binary_sensor.presence_hall_upstairs
            state: "on"
          - &dark
            condition: state
            entity_id: binary_sensor.hall_upstairs_is_dark
            state: "on"
          - condition: state
            entity_id: input_select.current_light_schedule
            state: "dim"

        sequence:
          - service: scene.turn_on
            alias: "Turn the hall lights to dim scene"
            data:
              entity_id: scene.hallupstairs_lights_dim

      - conditions:
          - *presence
          - *dark
          - condition: state
            entity_id: input_select.current_light_schedule
            state: "normal"
          - condition: state
            alias: "If it is dark in the living room, meaning lights are on there"
            entity_id:
              - binary_sensor.livingroom_is_dark
            state: "on"

        sequence:
          - service: scene.turn_on
            alias: "Turn the hall lights to normal scene"
            data:
              entity_id: scene.hallupstairs_lights_normal

    default:
      - service: light.turn_off
        data:
          entity_id: light.fibaro_hall_upstairs
          transition: 5
