---
alias: areas_hall_upstairs_lights
description: Turns the hallway lights on when motion has been detected
mode: queued
id: 1bc47338-f273-4ec5-b45f-ca05d19434d5

variables:
  anchors:
    - &presence_detected
      condition: state
      entity_id: binary_sensor.presence_hall_upstairs
      state: "on"

    - &is_dark
      condition: state
      entity_id: binary_sensor.hall_upstairs_is_dark
      state: "on"

    - &is_light_schedule
      alias: "Check current light schedule"
      condition: state
      entity_id: input_select.current_light_schedule

    - &zoey_door_closed
      alias: "Is Zoey's door closed?"
      or:
        - condition: state
          entity_id: binary_sensor.smallbedroom_door_open
          state: "off"
        - condition: state
          entity_id: binary_sensor.smallbedroom_door_open
          state: "on"
          for:
            minutes: 2

    - &nobody_asleep
      alias: "Nobody is sleeping"
      not:
        condition: state
        entity_id:
          - input_select.hall_upstairs_room_mode
        state: "Slaap"

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id: binary_sensor.presence_hall_upstairs
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_hall_upstairs
    to: "off"
    for:
      seconds: 60

  - platform: state
    entity_id:
      - input_select.current_light_schedule

  - platform: state
    entity_id:
      - binary_sensor.smallbedroom_door_open
    to: "off"

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - *presence_detected
          - *is_dark
          - <<: *is_light_schedule
            state: "dim"
          - *nobody_asleep
          - *zoey_door_closed
        sequence:
          - service: scene.turn_on
            alias: "Turn the hall lights to dim scene"
            data:
              entity_id: scene.hallupstairs_lights_dim

      - conditions:
          - *presence_detected
          - *is_dark
          - <<: *is_light_schedule
            state: "normal"
          - *nobody_asleep
          - *zoey_door_closed
        sequence:
          - service: scene.turn_on
            alias: "Turn the hall lights to normal scene"
            data:
              entity_id: scene.hallupstairs_lights_normal

    default:
      - service: light.turn_off
        data:
          entity_id: light.fibaro_hall_upstairs
          transition: 5
