---
alias: areas_hall_upstairs_lights_on
description: Turns the hallway lights on when motion has been detected
mode: queued
id: 1bc47338-f273-4ec5-b45f-ca05d19434d5

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_hall_upstairs

condition:
  - condition: state
    entity_id: binary_sensor.presence_hall_upstairs
    state: "on"
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"
  - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
  - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
  - condition: state
    entity_id: input_select.hall_upstairs_darklight
    state: "dark"

action:
  - service: light.turn_on
    data:
      entity_id: light.fibaro_hall_upstairs
      transition: 2
