---
alias: areas_hall_upstairs_room_mode_staleness
description: Reset stale room modes in the upstairs hall
mode: single
id: 6a211846-c272-49aa-b32c-11a03100ab1b

trigger:
  - platform: time_pattern
    minutes: "/30"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.hall_upstairs_room_mode
            state: "Slaap"
          - condition: state
            entity_id: input_select.master_bedroom_room_mode
            state: "Wakker"
        sequence:
          - action: input_select.select_option
            entity_id: input_select.hall_upstairs_room_mode
            data:
              option: "Wakker"

    default: []
