---
description: "Set a variable to dark to keep track of whether it is light or dark"
alias: areas_hall_upstairs_set_to_dark
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_hall_upstairs_luminance") | int < 20 and is_state("light.fibaro_hall_upstairs", "off")  }}'
    for:
      seconds: 60

condition:
  - '{{ states("sensor.pir_hall_upstairs_luminance") | int < 20 and is_state("light.fibaro_hall_upstairs", "off")  }}'

action:
  service: variable.set_variable
  data:
    variable: hall_upstairs_darklight
    value: 'dark'