---
description: Group the Office sonos to the living room when it gets connected
alias:  areas_office_group_sonos
id: 2265740c-7078-4d0c-82ca-34e433958380

trigger:
  - platform: state
    entity_id: media_player.office
    from: 'unavailable'
    to: 'paused'
  - platform: state
    entity_id: media_player.office
    from: 'unavailable'
    to: 'idle'

condition:
  condition: and
  conditions:
  - condition: state
    entity_id: media_player.living_room
    state: 'playing'
  - '{{ states.media_player.living_room.attributes.source != "TV" }}'

action:
  - service: sonos.join
    data:
      master: media_player.living_room
      entity_id: media_player.office
  - service: media_player.volume_set
    data:
      entity_id: media_player.office
      volume_level: 0.15    
