---
alias: areas_wc_lights
description: Turns the wc lights on when motion has been detected
mode: single
id: 722db137-6291-4fb6-b244-12edfbf9c6e4

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.presence_wc
    to: "on"
  - platform: state
    entity_id: binary_sensor.presence_wc
    to: "off"
    for:
      seconds: 80

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.presence_wc
            state: "off"
            for:
              seconds: 80

        sequence:
          - service: light.turn_off
            data:
              entity_id: light.fibaro_wc
              transition: 5

    default:
      - service: light.turn_on
        data:
          entity_id: light.fibaro_wc
          transition: 2
