---
alias: areas_wc_lights
description: Turns the wc lights on when motion has been detected
mode: single
id: 722db137-6291-4fb6-b244-12edfbf9c6e4

variables:
  anchors:
    - &presence_detected
      condition: state
      entity_id: binary_sensor.presence_wc
      state: "on"

    - &is_light_schedule
      alias: "Check current light schedule"
      condition: state
      entity_id: input_select.current_light_schedule

    - &select_scene
      service: scene.turn_on
      alias: "Turn the hall lights to appropriate scene"

    - &lights_turn_off
      service: light.turn_off
      alias: "Turn the hall lights off"
      data:
        entity_id: light.fibaro_wc
        transition: 5

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id: binary_sensor.presence_wc
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_wc
    to: "off"
    for:
      seconds: 80

condition:
  - condition: state
    alias: "Check if we can automate the lights"
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - *presence_detected
          - <<: *is_light_schedule
            state: "dim"
        sequence:
          - <<: *select_scene
            data:
              entity_id: scene.wc_lights_dim
              transition: 2

      - conditions:
          - *presence_detected
          - <<: *is_light_schedule
            state: "normal"
        sequence:
          - <<: *select_scene
            data:
              entity_id: scene.wc_lights_normal
              transition: 2

      - conditions:
          - *presence_detected
          - <<: *is_light_schedule
            state: "night"
        sequence:
          - <<: *select_scene
            data:
              entity_id: scene.wc_lights_night
              transition: 2

    default:
      - *lights_turn_off
