---
alias: areas_wc_lights_on
description: Turns the wc lights on when motion has been detected
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.pir_wc
  # Also apply circadian values when someone is still asleep and light has been manually turned on
  - platform: state
    entity_id: light.fibaro_wc
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.manual_lights
    state: 'off'
  - condition: state
    entity_id: binary_sensor.pir_wc
    state: 'on'
  - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
  - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
action:
  - service: script.sunlight
    data:
      entities:
        - light.fibaro_wc
      turn_on: true