---
alias: areas_wc_lights
description: Turns the wc lights on when motion has been detected
mode: queued
id: 722db137-6291-4fb6-b244-12edfbf9c6e4

variables:
  current_light_scene: 'scene.wc_lights_{{ states("input_select.current_light_schedule") }}'
  anchors:
    - &condition_is_presence_detected
      condition: state
      entity_id: binary_sensor.presence_wc
      state: "on"

    - &condition_light_schedule_change
      alias: "Check if the automation got triggered by a light schedule change"
      condition: trigger
      id: light_schedule_change

    - &turn_on
      service: scene.turn_on
      alias: "Turn the wc lights on"
      data:
        transition: 1

    - &turn_off
      service: light.turn_off
      alias: "Turn the hall lights off"
      data:
        entity_id: light.wc
        transition: 5

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id: input_select.current_light_schedule
    id: light_schedule_change

  - platform: state
    entity_id: binary_sensor.presence_wc
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_wc
    to: "off"
    for:
      seconds: 90

condition:
  - condition: state
    alias: "Check if we can automate the lights"
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Very subtly change the lights when a light schedule change is detected."
        conditions:
          - *condition_is_presence_detected
          - *condition_light_schedule_change
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"
            data:
              transition: 120

      - conditions:
          - *condition_is_presence_detected
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"

    default:
      - *turn_off
