---
alias: areas_wc_lights_on
description: Turns the wc lights on when motion has been detected
mode: queued
id: 85bc93f8-5e09-4a13-8960-0ad9c569e0c7

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_wc

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"
  - condition: state
    entity_id: binary_sensor.presence_wc
    state: "on"

action:
  - service: light.turn_on
    data:
      entity_id: light.fibaro_wc
      transition: 2
