 # https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/global.html
 
global:
  language: nl
  weather: weather.buienradar # Configure a weather entity see HA docs for more info.
  # outside_temperature: sensor.dark_sky_temperature # Configure a sensor here!
  # outside_humidity: sensor.dark_sky_humidity # Configure a sensor here!
  alarm: alarm_control_panel.alarm #Alarm panel entity.
  inside_temperature: sensor.pir_hallway_temperature #Can be 'climate.' or an 'sensor.' entity.

  # favorites_homepage: 'true' #Uncomment this line if you want the house information favorites on your homepage.