# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/scenes.html

scenes:
  - entity: script.scene_living_room_normal
    icon: mdi:sofa
    icon_color: '#ffffff'
    background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'
  - entity: script.scene_living_room_movie
    icon: fas:film
    icon_color: '#ffffff'
    background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'
  - entity: script.play_random_music_living_room
    icon: fas:music
    icon_color: '#ffffff'
    background: 'linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)'