blueprint:
  name: Cover control with Tradfri open/close remote
  description: 'Control a cover with an Ikea Tradfri open/close button remote over
    ZHA


    Short press on ☼ button will open the cover.

    Short press on ☰ button will close the cover.

    Long press on ☼ or ☰  will stop the cover.

    '
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA open/close remote to use
      selector:
        device:
          integration: zha
          manufacturer: "\x02KE"
          model: TRADFRI open/close remote
    cover:
      name: Cover
      description: The cover to control
      selector:
        target:
          entity:
            domain: cover
  source_url: https://community.home-assistant.io/t/zha-ikea-open-close-switch-for-covers-e-g-kadrilj-fyrtur/258904
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'remote'
action:
- choose:
  - conditions:
    - '{{ trigger.event.data.command == "up_open" }}'
    sequence:
    - service: cover.open_cover
      target: !input 'cover'
  - conditions:
    - '{{ trigger.event.data.command == "down_close" }}'
    sequence:
    - service: cover.close_cover
      target: !input 'cover'
  - conditions:
    - '{{ trigger.event.data.command in ("stop", "stop_opening", "stop_closing") }}'
    sequence:
    - service: cover.stop_cover
      target: !input 'cover'
mode: restart
