---
description: >
  Automatically display dashboard pages on the NS Panel Pro
alias: areas_livingroom_nspanel
id: 5b09a806-78d6-40bf-b463-06144cb5d2dd

trigger:
  - platform: state
    entity_id:
      - media_player.mass_sonos_kitchen

variables:
  mass_entity: '{{ states("sensor.mass_media_entity") }}'
  anchors:
    - &go_to_home_page
      alias: "Navigate to the home page"
      service: browser_mod.navigate
      target:
        device_id: a03bdae8b392884e72a812662eae18c4
      data:
        path: /dashboard-nspanel/home

    - &go_to_music_page
      alias: "Navigate to the music page"
      service: browser_mod.navigate
      target:
        device_id: a03bdae8b392884e72a812662eae18c4
      data:
        path: /dashboard-nspanel/music

action:
  - choose:
      - conditions:
          - "{{ is_state(mass_entity, 'playing') }}"
        sequence:
          - *go_to_music_page

    default:
      - *go_to_home_page
