---
# A binary sensor based on presence
# indicating whether everyone home is also asleep
binary_sensor:
  name: everybody_asleep
  state: >
    {%- if states("sensor.num_people_at_home_asleep") | int == states("sensor.num_people_at_home") | int 
        and states("sensor.num_people_at_home") | int > 0
    -%}
      on
    {%- else -%}
      off
    {%- endif -%}
