---
# A binary sensor based on presence
# indicating whether everyon home is also awake
binary_sensor:
  name: everybody_awake
  state: >
    {%- if states("sensor.num_people_at_home_awake") | int == states("sensor.num_people_at_home") | int 
        and states("sensor.num_people_at_home") | int > 0
    -%}
      on
    {%- else -%}
      off
    {%- endif -%}
