---
binary_sensor:
  name: everyone_in_bed
  unique_id: 2eaeeebc-f776-4d93-8513-5d0ae4d6147b
  state: >
    {{  states("sensor.num_people_in_bed") | int > 0 
        and states("sensor.num_people_in_bed") | int >= states("sensor.num_people_at_home") | int }}
