---
binary_sensor:
  - name: marvin_is_working
    unique_id: ed8ecc89-81c9-455d-9394-88e926f5fee2
    state: >
      {% set hour = as_timestamp(now()) | timestamp_custom("%H") | int  %}
      {%
        if (
          not(
            state_attr("binary_sensor.macbookwork_active", "Locked")
            or state_attr("binary_sensor.macbookwork_active", "Screen Off")
            or state_attr("binary_sensor.macbookwork_active", "Screensaver")
            or state_attr("binary_sensor.macbookwork_active", "Sleeping")
            or state_attr("binary_sensor.macbookwork_active", "Terminating")
            or state_attr("binary_sensor.macbookwork_active", "Fast User Switched")
          )
        )
        and hour >=7
        and hour < 18
      %}
      on
      {% else %}
      off
      {% endif %}
