---
# A binary sensor that is triggered when opening the door
# It triggers presence for 10sec, so that presence is not constantly
# detected when someone does not close the door
triggers:
  - trigger: state
    entity_id: binary_sensor.front_door_open
    to: "on"

binary_sensor:
  - name: presence_front_door
    unique_id: 60511aca-7bc6-462a-83c2-65cc88a44b51
    auto_off: 10
    state: "on"
