---
# A binary sensor that is triggered when opening the door
# It triggers presence for 10sec, so that presence is not constantly
# detected when someone does not close the door
trigger:
  - platform: state
    entity_id: binary_sensor.wc_door_open
    to: "on"

binary_sensor:
  - name: presence_wc_door
    auto_off: 10
    state: "on"
