---
# A binary sensor that is triggered when opening the door
# It triggers presence for 10sec, so that presence is not constantly
# detected when someone does not close the door
triggers:
  - trigger: state
    entity_id: binary_sensor.garden_door_open
    to: "on"

binary_sensor:
  - name: presence_garden_door
    unique_id: 24734a5d-6cb2-43b5-95d9-3411e87fda72
    auto_off: 10
    state: "on"
