---
# A binary sensor that is triggered when opening the door
# It triggers presence for 10sec, so that presence is not constantly
# detected when someone does not close the door
triggers:
  - trigger: state
    entity_id: binary_sensor.smallbedroom_door_open
    to: "on"

binary_sensor:
  - name: presence_smallbedroom_door
    unique_id: 96eee21a-6db4-4594-8eda-eb45c425f133
    auto_off: 10
    state: "on"
