---
binary_sensor:
  - name: presence_mancave
    unique_id: 1dc29348-5085-410a-9e76-0b67d26a220d
    state: >
      {{ is_state("binary_sensor.pir_mancave", "on")
          or is_state("binary_sensor.presence_mancave_door", "on")
          or is_state("media_player.mancave_tv", "on")
          or is_state("sensor.marvin_apple_watch", "mancave") }}
