---
description: Keep track of the currently activated scene
alias: system_events_scene_activated
mode: queued
id: f6759b16-37b1-4190-bec1-51f7f4bd3128

trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: scene
      service: turn_on

variables:
  scenes: "{{ [trigger.event.data.service_data.entity_id] if trigger.event.data.service_data.entity_id is string else trigger.event.data.service_data.entity_id }}"

action:
  # When multiple scenes are activated, the automation is triggered once with a list of entity_ids
  - repeat:
      count: "{{ scenes | length }}"
      sequence:
        - variables:
            scene: "{{ scenes[repeat.index-1] }}"
            scene_room: "{{ scene.replace('scene.', '').split('_')[0] }}"
            scene_category: "{{ scene.replace('scene.', '').split('_')[1] }}"
            scene_name: "{{ scene.replace('scene.', '').split('_')[2] }}"

        - service: input_select.select_option
          target:
            entity_id: "input_select.{{ scene_room }}_current_{{ scene_category }}_scene"
          data:
            option: "{{ scene_name }}"
