---
alias: areas_bathroom_climate
description: Manages the climate in our bathroom
id: 186b9beb-d46f-4eea-9204-f8ffc5743a6d
mode: queued

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.house_mode_everyone_asleep
      - binary_sensor.everyone_left_home
      - binary_sensor.house_mode_everyone_at_home_working
      - binary_sensor.house_mode_someone_just_awake
    from: ~

  - platform: state
    entity_id:
      - climate.bathroom
    from: unavailable

  - platform: time
    at:
      - "06:00:00"
      - "10:00:00"
      - "18:00:00"
      - "22:00:00"

variables:
  anchors:
    - &target
      target:
        entity_id: climate.bathroom

    - &turn_on
      <<: *target
      alias: "Turn on heating"
      service: climate.set_hvac_mode
      data:
        hvac_mode: "heat"

    - &turn_down
      <<: *target
      alias: "Turn down small bedroom climate"
      service: climate.set_temperature
      data:
        temperature: 15.0

    - &turn_up
      <<: *target
      alias: "Turn down small bedroom climate"
      service: climate.set_temperature
      data:
        temperature: 19.0

action:
  - choose:
      - conditions:
          - alias: "When the house is in away mode"
            condition: state
            entity_id: binary_sensor.everyone_left_home
            state: "on"
        sequence:
          - *turn_down

      - conditions:
          - alias: "When everyone at home is working"
            condition: state
            entity_id: binary_sensor.house_mode_everyone_at_home_working
            state: "on"
        sequence:
          - *turn_down

      - conditions:
          - alias: "When the house is in sleep mode"
            condition: state
            entity_id: binary_sensor.house_mode_everyone_asleep
            state: "on"
        sequence:
          - *turn_down

      - alias: "Turn up the heating in the morning"
        conditions:
          - condition: state
            entity_id: binary_sensor.house_mode_someone_just_awake
            state: "on"
          - condition: time
            after: "06:00:00"
            before: "10:00:00"
        sequence:
          - *turn_on
          - *turn_up

      - alias: "Turn up the heating in the evening"
        conditions:
          - condition: state
            entity_id: binary_sensor.house_mode_everyone_asleep
            state: "off"
          - condition: time
            after: "18:00:00"
            before: "22:00:00"
        sequence:
          - *turn_on
          - *turn_up

    default:
      - *turn_down
