---
description: Group sonos to the living room when there is music playing and motion is detected
alias:  areas_bathroom_group_sonos
mode: queued
trigger:
  - platform: state
    entity_id: binary_sensor.pir_bathroom
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
condition:
  - condition: state
    entity_id: binary_sensor.pir_bathroom
    state: 'on'
  - condition: state
    entity_id: media_player.living_room
    state: 'playing'
  - condition: or
    conditions:
      - condition: state
        entity_id: media_player.bathroom
        state: 'paused'
      - condition: state
        entity_id: media_player.bathroom
        state: 'idle'
  - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
  - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
  - '{{ states.media_player.living_room.attributes.source != "TV" }}'
action:
  - service: sonos.join
    data:
      master: media_player.living_room
      entity_id: media_player.bathroom
  - service: media_player.volume_set
    data:
      entity_id: media_player.bathroom
      volume_level: 0.25    