---
alias: areas_bathroom_lights
description: Turns the bathroom lights on when motion has been detected
mode: queued
id: 9617f5b7-0733-4877-82ea-1ab8bc5332b0

variables:
  current_light_scene: 'scene.bathroom_lights_{{ states("input_select.current_light_schedule") }}'
  anchors:
    - &condition_is_presence_detected
      alias: "There is movement in the bathroom"
      condition: state
      entity_id: binary_sensor.presence_bathroom
      state: "on"

    - &condition_is_dark
      alias: "It is dark"
      condition: state
      entity_id: binary_sensor.bathroom_is_dark
      state: "on"

    - &condition_is_room_mode
      alias: "Check the room mode"
      condition: state
      entity_id:
        - input_select.bathroom_room_mode

    - &condition_light_schedule_change
      alias: "Check if the automation got triggered by a light schedule change"
      condition: trigger
      id: light_schedule_change

    - &turn_on
      service: scene.turn_on
      alias: "Turn the bathroom lights on"
      data:
        transition: 1

    - &turn_off
      service: light.turn_off
      data:
        entity_id: light.bathroom
        transition: 5

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.presence_bathroom
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_bathroom
    to: "off"
    for:
      seconds: 240

  - platform: state
    entity_id:
      - input_select.bathroom_room_mode
      - binary_sensor.bathroom_is_dark

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Turn lights off when someone is asleep"
        conditions:
          - *condition_is_presence_detected
          - <<: *condition_is_room_mode
            state: "Slaap"
            for:
              minutes: 10
        sequence:
          - *turn_off

      - alias: "Very subtly change the lights when a light schedule change is detected."
        conditions:
          - *condition_is_presence_detected
          - *condition_is_dark
          - *condition_light_schedule_change
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"
            data:
              transition: 120

      - alias: "Turn lights on when presence is detected and we're not asleep"
        conditions:
          - *condition_is_presence_detected
          - *condition_is_dark
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"

    default:
      - *turn_off
