---
alias: areas_bathroom_lights
description: Turns the bathroom lights on when motion has been detected
mode: queued
id: 9617f5b7-0733-4877-82ea-1ab8bc5332b0

variables:
  anchors:
    - &manual_control_off
      alias: "Turn manual control off"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.bathroom_manual_control

    - &presence_detected
      alias: "There is movement in the bathroom"
      condition: state
      entity_id: binary_sensor.presence_bathroom
      state: "on"

    - &is_dark
      alias: "It is dark"
      condition: state
      entity_id: binary_sensor.bathroom_is_dark
      state: "on"

    - &is_light_schedule
      alias: "Check current light schedule"
      condition: state
      entity_id: input_select.current_light_schedule

    - &turn_off
      service: light.turn_off
      data:
        entity_id: light.bathroom
        transition: 5

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.presence_bathroom
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_bathroom
    to: "off"
    for:
      seconds: 240

  - platform: state
    entity_id:
      - input_select.bathroom_room_mode
      - binary_sensor.bathroom_is_dark

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Turn lights off when someone is asleep"
        conditions:
          - *presence_detected
          - or:
              - <<: *is_light_schedule
                state: "night"
              - alias: "Someone is sleeping"
                condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_asleep
                state: "on"
        sequence:
          - *turn_off

      - alias: "Turn lights on when presence is detected and we're not asleep"
        conditions:
          - *presence_detected
          - *is_dark
        sequence:
          - service: scene.turn_on
            data:
              entity_id: scene.bathroom_lights_natuurlijklicht

    default:
      - *turn_off
