---
alias: areas_bathroom_lights_on
description: Turns the bathroom lights on when motion has been detected
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_bathroom
condition:
  - condition: state
    entity_id: binary_sensor.presence_bathroom
    state: 'on'
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: 'off'
  - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
  - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
action:
  - service: script.sunlight
    data:
      entities:
        - light.fibaro_bathroom
      turn_on: true
      min_brightness: 70
      turn_on_transition: 1