---
alias: areas_bathroom_music_off
description: >
  Ungroup and pause the sonos when no motion has been detected for a while
mode: queued
id: 94fd7fa0-199c-4547-af34-c999a7cd7cdc

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_bathroom
    to: "off"
    for:
      seconds: 75

condition:
  - condition: state
    entity_id: binary_sensor.presence_bathroom
    state: "off"
    for:
      seconds: 75
  # Only disable if it is playing by its own, since the blueprint takes
  # care of grouped sonos
  - "{{ state_attr('media_player.sonos_bathroom', 'sonos_group') | length == 1 }}"

action:
  - service: media_player.media_pause
    data:
      entity_id: media_player.sonos_bathroom
