---
alias: areas_bathroom_music_off
description: Ungroup and pause the sonos when no motion has been detected for a while
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.pir_bathroom
    to: 'off'
    for:
      seconds: 75
condition:
  condition: state
  entity_id: binary_sensor.pir_bathroom
  state: 'off'
  for:
    seconds: 75
action:
  - service: sonos.unjoin
    data:
      entity_id: media_player.bathroom
  - delay:
      seconds: 1
  - service: media_player.media_pause
    data:
      entity_id: media_player.bathroom