---
alias: areas_bathroom_play_music
description: Play music automatically in the bathroom based on several scenarios
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_bathroom    
  - platform: state
    entity_id: binary_sensor.bathroom_flood
  - platform: state
    entity_id: sensor.marvin_status
    to: 'Net wakker'
  - platform: state
    entity_id: sensor.laura_status
    to: 'Net wakker'
condition:
  - condition: state
    entity_id: binary_sensor.presence_bathroom
    state: 'on'
  # There is no music playing already
  - condition: or
    conditions:
      - condition: state
        entity_id: media_player.sonos_bathroom
        state: 'paused'
      - condition: state
        entity_id: media_player.sonos_bathroom
        state: 'idle'  
  - condition: or
    conditions:
      # Morning routine during weekdays
      - condition: and
        conditions:
        - condition: or
          conditions:
          - condition: state
            entity_id: sensor.marvin_status
            state: 'Net wakker'
          - condition: state
            entity_id: sensor.laura_status
            state: 'Net wakker'
        - condition: state
          entity_id: binary_sensor.workday
          state: 'on'
      # Shower is on and when no music is playing already
      - condition: and
        conditions:
          - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
          - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
          - condition: time
            before: "22:00:00"
          - condition: state
            entity_id: binary_sensor.bathroom_flood
            state: 'on'
action:
  - choose:
      # Play normal music when showering
      - conditions:
          - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
          - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
          - condition: time
            before: "22:00:00"
          - condition: state
            entity_id: binary_sensor.bathroom_flood
            state: 'on'
        sequence:
          - service: script.play_random_music
            data:
              sonos_entity: media_player.sonos_bathroom
              genre: 'normal'
    # Else, play a chill morning music list
    default:
      - service: script.play_random_music
        data:
          sonos_entity: media_player.sonos_bathroom
          genre: 'morning'