---
alias: areas_bathroom_play_music
description: Play music automatically in the bathroom based on several scenarios
mode: single
id: fea11cbd-7687-4212-b771-668f5ee5e860

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_bathroom
  - platform: state
    entity_id: binary_sensor.bathroom_flood
  - platform: state
    entity_id: binary_sensor.someone_just_awake
    to: "on"

condition:
  - condition: state
    entity_id: binary_sensor.presence_bathroom
    state: "on"
  - condition: or
    alias: "There is no music playing already"
    conditions:
      - condition: state
        entity_id: media_player.sonos_bathroom
        state: "paused"
      - condition: state
        entity_id: media_player.sonos_bathroom
        state: "idle"

action:
  - choose:
      - alias: "Play morning music when we have just woken up"
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.someone_just_awake
                state: "on"
          - condition: state
            entity_id: binary_sensor.workday
            state: "on"
        sequence:
          - service: script.play_random_music
            data:
              sonos_entity: media_player.sonos_bathroom
              genre: "morning"

      - alias: "Play normal music when showering before 20:00"
        conditions:
          - condition: state
            entity_id: binary_sensor.someone_asleep
            state: "off"
          - condition: time
            before: "20:00:00"
          - condition: state
            entity_id: binary_sensor.bathroom_flood
            state: "on"
        sequence:
          - service: script.play_random_music
            data:
              sonos_entity: media_player.sonos_bathroom
              genre: "normal"

      - alias: "Play chill music when showering before 22:00"
        conditions:
          - condition: state
            entity_id: binary_sensor.someone_asleep
            state: "off"
          - condition: time
            before: "22:00:00"
          - condition: state
            entity_id: binary_sensor.bathroom_flood
            state: "on"
        sequence:
          - service: script.play_random_music
            data:
              sonos_entity: media_player.sonos_bathroom
              genre: "chill"

    # Otherwise, do not play music
    default: []
