---
description: "Set a variable to dark to keep track of whether it is light or dark"
alias: areas_bathroom_set_to_dark
mode: queued
id: D92ABC8E-CEAF-47CC-8C0D-12CE5AE6E71B

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_bathroom_luminance") | int < 15 and is_state("light.fibaro_bathroom", "off")  }}'
    for:
      seconds: 60

condition:
  - '{{ states("sensor.pir_bathroom_luminance") | int < 15 and is_state("light.fibaro_bathroom", "off")  }}'

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bathroom_darklight
      option: "dark"
