---
description: Send me a notification to sound the alarm whenever motion has been detected
alias: system_notifications_alarm
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.pir_bedroom
    to: 'on'
  - platform: state
    entity_id: binary_sensor.pir_hallway
    to: 'on'
condition:
  - condition: state
    entity_id: input_select.marvin_status_dropdown
    state: 'Weg'
  - condition: state
    entity_id: input_select.laura_status_dropdown
    state: 'Weg'
  - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
action:
  service: notify.mobile_app_marvins_iphone
  data:
    title: "INBREKER ALERT!" 
    message: "Beweging gedetecteerd terwijl er niemand thuis is!"
    data:
      push:
        category: "alarm" # Needs to match the top level identifier you used in the ios configuration      