---
description: Send me a notification when a sensor's battery gets low
alias: system_notifications_battery_low
mode: queued
id: 10d6cc7f-dabc-452d-976f-fdc683d7bbe7

trigger:
  - platform: numeric_state
    entity_id:
      - sensor.pir_wc_battery_level
      - sensor.pir_master_bedroom_battery_level
      - sensor.pir_kitchen_battery_level
      - sensor.pir_hall_upstairs_battery_level
      - sensor.pir_hall_downstairs_battery_level
      - sensor.pir_bathroom_battery_level
      - sensor.luxaflex_master_bedroom_battery_level
      - sensor.luxaflex_mancave_battery_level
      - sensor.luxaflex_living_room_battery_level
      - sensor.luxaflex_kitchen_battery_level
      - sensor.luxaflex_garden_door_battery_level
      - sensor.flood_sensor_battery_level
      - sensor.small_bedroom_battery_level
    below: 1
    id: "battery_dead"
  - platform: numeric_state
    entity_id:
      - sensor.pir_wc_battery_level
      - sensor.pir_master_bedroom_battery_level
      - sensor.pir_kitchen_battery_level
      - sensor.pir_hall_upstairs_battery_level
      - sensor.pir_hall_downstairs_battery_level
      - sensor.pir_bathroom_battery_level
      - sensor.luxaflex_master_bedroom_battery_level
      - sensor.luxaflex_mancave_battery_level
      - sensor.luxaflex_living_room_battery_level
      - sensor.luxaflex_kitchen_battery_level
      - sensor.luxaflex_garden_door_battery_level
      - sensor.flood_sensor_battery_level
      - sensor.small_bedroom_battery_level
    below: 20
    above: 0
    id: "battery_low"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "battery_dead"
        sequence:
          - service: script.send_notification
            data:
              receivers:
                - "marvin"
              message: "De batterij van de sensor {{ trigger.to_state.attributes.friendly_name }} is leeg!"
    default:
      - service: script.send_notification
        data:
          receivers:
            - "marvin"
          message: "De batterij van de sensor {{ trigger.to_state.attributes.friendly_name }} is minder dan 20%!"
