---
description: Send me a notification when a sensor's battery gets low
alias: system_notificatinos_battery_low
mode: queued
id: 7c7cd9a1-ae79-405e-9a22-1865971e82a3

trigger:
  - platform: numeric_state
    entity_id: 
      - sensor.pir_bathroom_battery_level
      - sensor.fibaro_system_fgfs101_zwave_flood_sensor_battery_level
      - sensor.pir_bedroom_battery_level
      - sensor.pir_hallway_battery_level
      - sensor.pir_livingroom_battery_level
      - sensor.pir_wc_battery_level
    below: 25
    above: 1

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
      message: "De batterij van de sensor {{ trigger.to_state.attributes.friendly_name }} is onder de 25%!"