---
description: Automatically send notification when doorbell is pressed
alias: system_notifications_doorbell
id: cb689da9-474a-48af-b945-e68e48fa6eeb

trigger:
  - trigger: event
    event_type: "ring"

variables:
  video_start: "{{ (utcnow() - timedelta(seconds=5)).isoformat() }}"
  video_end: "{{ utcnow().isoformat() }}"
  event_id: "{{ state_attr('event.g4_doorbell_doorbell', 'event_id') }}"

action:
  - choose:
      - conditions:
          - "{{ event_id is string }}"
        sequence:
          - service: script.send_notification
            data:
              receivers:
                - "marvin"
              message: >-
                🛎️ De bel gaat!
              image: >
                "{{ '/api/unifiprotect/thumbnail/5b2cd98901627e03e70003e9/'
                    + event_id }}"

    default:
      - service: script.send_notification
        data:
          receivers:
            - "marvin"
          message: >-
            🛎️ De bel gaat!
