---
description: Automatically send notification when download is finished
alias: system_notifications_download_finished_series
id: b0717cd7-d9dc-48fb-918d-aa8807a9ee93

trigger:
  - platform: webhook
    webhook_id: "download_finished"

variables:
  series: "{{ trigger.json.series.title }}"
  s: "{{ trigger.json.episodes[0].seasonNumber }}"
  e: "{{ trigger.json.episodes[0].episodeNumber }}"

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
      message: >-
        🎥 Download klaar: {{series}} - S{{s}}E{{e}}
