---
description: Automatically send notification when download is finished
alias: system_notifications_download_finished_movies
id: f097c04d-6ed3-493a-ae09-9187899d1ca2

trigger:
  - platform: webhook
    webhook_id: "download_finished_movie"

variables:
  movie: "{{ trigger.json.movie.title }}"

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
      message: >-
        🎥 Download klaar: {{movie}}
