description: Send a notification when a download has finished
alias: system_notifications_download_finished
mode: single

trigger:
  - platform: webhook
    webhook_id: "sabnzb_download_finished"

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
      message: "{{ trigger.data.download_name }} is klaar met downloaden!"