---
description: >
  Send a notification when one of our garbage cans is being picked up tomorrow
alias: notification_garbage
mode: single
id: 6488cf53-5292-4146-a44b-80ed0cf4ad7e

trigger:
  - platform: time
    at: "18:00:00"

condition:
  - condition: state
    entity_id: sensor.rmn_next_pickup_in
    state: "1"

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
        - "laura"
        - "intercom"
      message: "Morgen wordt {{ states('sensor.rmn_next_garbage_pickup') }} opgehaald!"
      intercom_devices:
        - media_player.sonos_livingroom
        - media_player.sonos_bathroom
        - media_player.sonos_master_bedroom
