---
description: Send a notification when the short window of the picnic delivery is known
alias: system_notifications_picnic_today
mode: single
id: 19f54bfb-fae0-46a2-b72c-75cbf467dfd2

trigger:
  - platform: state
    entity_id:
      - sensor.picnic_last_order_eta_start
      - sensor.picnic_last_order_eta_end
  - platform: time
    at: "18:00:00"

variables:
  days_left: "{{ as_timestamp(states('sensor.picnic_last_order_eta_start')) | timestamp_custom('%d') | int - as_timestamp(now()) | timestamp_custom('%d') | int }}"
  day_name: >-
      {% if days_left == 0 %} vandaag
      {% elif days_left == 1 %} morgen
      {% endif %}

condition:
  - "{{ days_left < 2 }}"
  - "{{ as_timestamp(states('sensor.picnic_last_order_eta_start')) > as_timestamp(now()) }}"

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
        - "laura"
      message: > 
        Picnic bezorgt {{ day_name }} tussen {{ as_timestamp(states('sensor.picnic_last_order_eta_start')) | timestamp_custom('%H:%M') }} en {{ as_timestamp(states('sensor.picnic_last_order_eta_end')) | timestamp_custom('%H:%M') }}!
