---
description: Send a notification when picnic is delivering the next day
alias: system_notifications_picnic_tomorrow
mode: single

trigger:
  - platform: time
    at: "19:00:00"

condition:
  - "{{ (as_timestamp(state_attr('sensor.picnic_delivery', 'delivery').window_start) - as_timestamp(now()) )| timestamp_custom('%H') | int < 36 }}"
  - "{{ as_timestamp(state_attr('sensor.picnic_delivery', 'delivery').window_start) > as_timestamp(now()) }}"

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
        - "laura"
      message: > 
        Picnic bezorgt morgen tussen {{ as_timestamp(state_attr('sensor.picnic_delivery', 'delivery').window_start) | timestamp_custom('%H:%M') }} en {{ as_timestamp(state_attr('sensor.picnic_delivery', 'delivery').window_end) | timestamp_custom('%H:%M') }}!
