---
description: Send a notification when the short window of the picnic delivery is known
alias: system_notifications_picnic_today
mode: single
id: 19f54bfb-fae0-46a2-b72c-75cbf467dfd2

trigger:
  - platform: state
    entity_id:
      - sensor.picnic_next_delivery_eta_start
      - sensor.picnic_next_delivery_eta_end
  - platform: time
    at: "08:30:00"

variables:
  eta_start: >
    {{ as_timestamp(states('sensor.picnic_next_delivery_eta_start')) }}
  eta_end: >
    {{ as_timestamp(states('sensor.picnic_next_delivery_eta_end')) }}
  days_left: >
    {{
      eta_start
      | timestamp_custom('%d') | int
      - as_timestamp(now()) | timestamp_custom('%d') | int }}
  day_name: >-
    {% if days_left == 0 %} vandaag
    {% elif days_left == 1 %} morgen
    {% endif %}

condition:
  - "{{ days_left < 2 }}"
  - "{{ eta_start > as_timestamp(now()) }}"

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
        - "laura"
        - "intercom"
      intercom_devices:
        - media_player.sonos_livingroom
        - media_player.sonos_bathroom
        - media_player.sonos_master_bedroom
      message: >-
        Picnic bezorgt {{ day_name }} tussen
        {{ eta_start | timestamp_custom('%H:%M') }}
        en {{ eta_end | timestamp_custom('%H:%M') }}!
