---
description: Send a notification when our vacuum starts cleaning
alias: notification_vacuum_on
mode: single
trigger:
  - platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    to: 'cleaning'
condition:
  - condition: state
    entity_id: input_select.marvin_status_dropdown
    state: 'Weg'
  - condition: state
    entity_id: input_select.laura_status_dropdown
    state: 'Weg'
action:
  - service: notify.mobile_app_rne_l21
    data: 
      message: "Norby gaat aan de slag!"
  - service: notify.mobile_app_marvins_iphone
    data: 
      message: "Norby gaat aan de slag!"