---
description: Send a notification when our vacuum starts cleaning
alias: notification_vacuum_on
mode: single
id: 96522435-829f-419b-b3c0-adfafb88b209

trigger:
  - platform: state
    entity_id: vacuum.norby
    to: 'cleaning'

condition:
  - condition: state
    entity_id: input_select.marvin_status_dropdown
    state: 'Weg'
  - condition: state
    entity_id: input_select.laura_status_dropdown
    state: 'Weg'

action:
  - service: script.send_notification
    data:
      receivers:
        - "marvin"
        - "laura"
      type: "away_only"
      message: "Norby gaat aan de slag!"