---
description: Send a notification when our vacuum starts cleaning
alias: notification_vacuum_on
mode: single
id: 96522435-829f-419b-b3c0-adfafb88b209

trigger:
  - trigger: state
    entity_id: vacuum.norby
    to: "cleaning"

condition:
  - alias: "Not notified in the last 2 hours"
    condition: template
    value_template: >
      {{ this.attributes.last_triggered is none
         or now() - this.attributes.last_triggered > timedelta(hours=2) }}

action:
  - action: script.send_notification
    data:
      receivers:
        - "marvin"
        - "laura"
      type: "away_only"
      message: "🧹 Norby gaat aan de slag!"
