---
alias: areas_master_bedroom_blinds
description: >
  Control the blinds in the master bedroom (which are facing south) by using
   - Sun elevation
   - At 19:00 and 21:15
   - The solar panels (indicating a hot day)
   - Whenever we wake up
mode: queued
max_exceeded: silent
id: aa45eaa1-b64b-4319-acf5-1d3ac0ea1d1a

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      # Include auto-shut blinds on hot days
      - binary_sensor.sun_should_close_south_blinds
      # Whenever we wake up or go to sleep
      - input_select.laura_sleep_status_dropdown
      - input_select.marvin_sleep_status_dropdown
      - input_boolean.setting_manual_blinds
  - platform: state
    id: "asleep"
    entity_id:
      - input_select.laura_sleep_status_dropdown
      - input_select.marvin_sleep_status_dropdown
    to: "Slaapt"
  # Sun
  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    below: 1.0
  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    above: 1.0
  - platform: time
    at:
      - "19:00:00"
      - "21:15:00"
  # Buttons for ventilating
  - platform: event
    id: "button_marvin_double"
    event_type: "zha_event"
    event_data:
      device_id: "2a93e9d147b93ca0ec5992d48dde3129"
      command: "double"
  - platform: event
    id: "button_laura_double"
    event_type: "zha_event"
    event_data:
      device_id: "92cb556d8bab10f8b49ae0ed3e8dbe32"
      command: "double"

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"
  - condition: or
    conditions:
      - "{{ not is_state('input_select.bedroom_current_cover_scene', 'ventilating') }}"
      - condition: trigger
        id: "asleep"

action:
  - choose:
      - alias: >
          Ventilating when desired so we can cool down our bedroom
          on hot days after opening the windows.
        conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "button_marvin_double"
              - condition: trigger
                id: "button_laura_double"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.bedroom_cover_ventilating

      - alias: >
          This nearly closes our blinds but leaves a small gap at the top for fresh air
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_just_awake
                state: "on"
              - condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_asleep
                state: "on"
              - condition: time
                after: "21:15:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.bedroom_cover_ventilatingnight

      - alias: "This fully closes the blinds on hot days"
        conditions:
          - condition: state
            entity_id:
              - binary_sensor.sun_should_close_south_blinds
            state: "on"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.bedroom_cover_closed

      - alias: "This closes the blinds half way when it gets dark"
        conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id:
                  - sensor.sun_elevation
                below: 1.0
              - condition: time
                after: "19:00:00"
                before: "21:15:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.bedroom_cover_halfclosed

    default:
      - alias: "Otherwise, open the blinds"
        service: scene.turn_on
        target:
          entity_id: scene.bedroom_cover_halfopen
