---
alias: areas_master_bedroom_blinds
description: >
  Control the blinds in the master bedroom (which are facing south) by using
   - Sun elevation
   - At 19:00 and 21:15
   - The solar panels (indicating a hot day)
   - Whenever we wake up
mode: queued
max_exceeded: silent
id: aa45eaa1-b64b-4319-acf5-1d3ac0ea1d1a
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.sun_should_close_south_blinds
      - binary_sensor.house_mode_someone_asleep
      - binary_sensor.house_mode_someone_just_awake
      - input_boolean.setting_manual_blinds
      - input_boolean.masterbedroom_cover_manual_control

  - platform: state
    id: "reset"
    entity_id:
      - binary_sensor.house_mode_someone_asleep
    to: "off"

  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    below: 1.0

  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    above: 1.0

  - platform: time
    at:
      - "19:00:00"
      - "21:15:00"

  - platform: state
    entity_id:
      - scene.bedroom_cover_ventilating
      - scene.bedroom_cover_ventilatingnight
      - scene.bedroom_cover_closed
      - scene.bedroom_cover_halfclosed
      - scene.bedroom_cover_halfopen
      - scene.bedroom_cover_open
    id: bedroom_blinds

variables:
  anchors:
    - &ventilating
      service: scene.turn_on
      target:
        entity_id: scene.bedroom_cover_ventilating

    - &ventilating_night
      service: scene.turn_on
      target:
        entity_id: scene.bedroom_cover_ventilatingnight

    - &closed
      service: scene.turn_on
      target:
        entity_id: scene.bedroom_cover_closed

    - &half_closed
      service: scene.turn_on
      target:
        entity_id: scene.bedroom_cover_halfclosed

    - &open
      alias: "Open the blinds"
      service: scene.turn_on
      target:
        entity_id: scene.bedroom_cover_halfopen

    - &manual_control_on
      alias: "Set manual control to on, so the blinds stay closed"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.masterbedroom_cover_manual_control

    - &manual_control_off
      alias: "Reset manual control, so the blinds stay closed"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.masterbedroom_cover_manual_control

condition:
  - condition: state
    entity_id:
      - input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      - alias: "Check if we manually changed the blinds"
        conditions:
          - condition: trigger
            id: bedroom_blinds
        sequence:
          - choose:
              - conditions:
                  - alias: "It was changed by a user"
                    condition: template
                    value_template: "{{ trigger.to_state.context.user_id != None }}"
                sequence:
                  - *manual_control_on

      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off

      - alias: "Stop automating the blinds when manual control is on"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.masterbedroom_cover_manual_control
            state: "on"
        sequence:
          - stop: "Master bedroom blinds are manually controlled"

      - alias: >
          This nearly closes our blinds but leaves a small gap at the top for fresh air
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_just_awake
                state: "on"
              - condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_asleep
                state: "on"
              - condition: time
                after: "21:15:00"
        sequence:
          - *ventilating_night

      - alias: "This fully closes the blinds on hot days"
        conditions:
          - condition: state
            entity_id:
              - binary_sensor.sun_should_close_south_blinds
            state: "on"
        sequence:
          - *closed

      - alias: "This closes the blinds half way when it gets dark"
        conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id:
                  - sensor.sun_elevation
                below: 1.0
              - condition: time
                after: "19:00:00"
                before: "21:15:00"
        sequence:
          - *half_closed

    default:
      - *open
