---
alias: areas_master_bedroom_lights
description: >-
  Controls the lights in the master bedroom.

  - When it is dark, the lights:
     - Turn on to bright and cool during the day
     - Turn on less bright and warmer in the evening

  - When I get in bed after 9:30pm, the ceiling light turns off and the bedside table
    lights dim, setting a nice scene for going to sleep.

  - Whenever we go to sleep, the lights stay off

  - We can still turn the bedside table lights on/off, even when we're in sleep mode

  - Manual control is used to disable automation when we override the default behaviour

mode: queued
id: e1d01b47-8989-4d64-b7c1-c1f069f622f5
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - binary_sensor.presence_master_bedroom
    to: "on"

  - platform: state
    entity_id:
      - input_select.master_bedroom_room_mode
    to: "Net wakker"
    for:
      minutes: 5

  - platform: state
    entity_id:
      - input_select.master_bedroom_room_mode
    to: "Slaap"
    id: "house_mode_someone_asleep"

  - platform: state
    entity_id: binary_sensor.presence_master_bedroom
    to: "off"
    for:
      seconds: 60

  - platform: state
    entity_id:
      - binary_sensor.master_bedroom_is_dark
      - input_select.master_bedroom_room_mode
      - input_select.bedroom_current_cover_scene

  - platform: event
    id: "button_marvin_single"
    event_type: "zha_event"
    event_data:
      device_id: "2a93e9d147b93ca0ec5992d48dde3129"
      command: "single"

  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "92cb556d8bab10f8b49ae0ed3e8dbe32"
      command: "single"
    id: "button_laura_single"

  - platform: state
    entity_id:
      - light.master_bedroom_lights
    from: "on"
    to: "off"
    id: "all_lights_off"

variables:
  anchors:
    - &manual_control_on
      alias: "Set bedside left as manually controlled"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.masterbedroom_manual_control

    - &manual_control_off
      alias: "Turn manual control off"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.masterbedroom_manual_control

    - &turn_off
      alias: "Turn the lights off"
      service: light.turn_off
      data:
        entity_id: light.master_bedroom_lights
        transition: 5

    - &select_scene
      service: scene.turn_on
      data:
        transition: 2

    - &condition_is_dark
      alias: "Is it dark in the room?"
      condition: state
      entity_id: binary_sensor.master_bedroom_is_dark
      state: "on"

    - &condition_is_presence_detected
      alias: "Is presence detected in the room?"
      condition: state
      entity_id: binary_sensor.presence_master_bedroom
      state: "on"

    - &condition_is_room_mode
      alias: "Check the room mode"
      condition: state
      entity_id:
        - input_select.master_bedroom_room_mode

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Reset manual control at the start of the day"
        conditions:
          - condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off

      - alias: "When I click the button when I am already sleeping"
        conditions:
          - condition: trigger
            id: "button_marvin_single"
          - condition: state
            entity_id:
              - input_select.master_bedroom_room_mode
            state: "Slaap"
            for:
              seconds: 2
        sequence:
          - *manual_control_on
          - alias: "Toggle the light"
            service: light.toggle
            data:
              entity_id: light.master_bedroom_left
              brightness_pct: 3
              transition: 2

      - alias: "When Laura clicks the button when she is already sleeping"
        conditions:
          - condition: trigger
            id: "button_laura_single"
          - condition: state
            entity_id:
              - input_select.master_bedroom_room_mode
            state: "Slaap"
            for:
              seconds: 2
        sequence:
          - *manual_control_on
          - alias: "Toggle the light"
            service: light.toggle
            data:
              entity_id: light.master_bedroom_right
              brightness_pct: 3
              transition: 2

      - alias: >
          Turn the light off when we go to sleep, even if it is manually controlled
        conditions:
          - alias: "Someone goes to sleep"
            condition: trigger
            id: "house_mode_someone_asleep"
        sequence:
          - *turn_off

      - alias: "Turn off manual control when all lights are turned off"
        conditions:
          - alias: "All lights are off"
            condition: trigger
            id: "all_lights_off"
        sequence:
          - *manual_control_off

      - alias: "Stop automating lights when the lights are manually controlled"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.masterbedroom_manual_control
            state: "on"
        sequence: []

      - alias: "Turn the lights off when the blinds are fully open"
        conditions:
          - condition: state
            entity_id:
              - input_select.bedroom_current_cover_scene
            state: "ventilating"
        sequence:
          - *turn_off

      - alias: "Turn lights to dim when we just woke up (overriding light schedule)"
        conditions:
          - <<: *condition_is_room_mode
            state: "Net wakker"
            for:
              minutes: 5
          - *condition_is_dark
          - *condition_is_presence_detected
        sequence:
          - <<: *select_scene
            target:
              entity_id: scene.masterbedroom_lights_rusten

      - alias: "Turn lights on according to light schedule"
        conditions:
          - <<: *condition_is_room_mode
            state: "Wakker"
          - *condition_is_dark
          - *condition_is_presence_detected
        sequence:
          - <<: *select_scene
            target:
              entity_id: scene.masterbedroom_lights_natuurlijklicht

    default:
      - *turn_off
