---
alias: areas_master_bedroom_lights
description: Controls the lights in the master bedroom
mode: queued
id: e1d01b47-8989-4d64-b7c1-c1f069f622f5

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.presence_master_bedroom
      - binary_sensor.someone_asleep
    to: "on"
  - platform: state
    entity_id: binary_sensor.presence_master_bedroom
    to: "off"
    for:
      seconds: 60
  - platform: state
    entity_id:
      - binary_sensor.master_bedroom_is_dark
  - platform: state
    entity_id:
      - binary_sensor.someone_in_bed
    to: "on"
    for:
      seconds: 15
  - platform: state
    entity_id:
      - binary_sensor.someone_in_bed
    to: "off"
    for:
      seconds: 20

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id:
              - binary_sensor.someone_asleep
            state: "off"
          - condition: state
            entity_id: binary_sensor.master_bedroom_is_dark
            state: "on"
          - condition: state
            entity_id: binary_sensor.presence_master_bedroom
            state: "on"

        sequence:
          - choose:
              - alias: "Start dimming the light when somone gets in bed, ready to go to sleep"
                conditions:
                  - condition: state
                    entity_id:
                      - binary_sensor.someone_in_bed
                    state: "on"
                    for:
                      seconds: 15
                  - condition: time
                    after: "21:30:00"
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: light.master_bedroom_bedsidetables
                      transition: 3
                      brightness_pct: 15
                  - service: light.turn_off
                    data:
                      entity_id: light.master_bedroom_ceiling
                      transition: 3

            default:
              - alias: "Just turn on the lights"
                service: light.turn_on
                data:
                  entity_id: light.master_bedroom_lights
                  transition: 1

    default:
      - alias: "Turn off the lights otherwise"
        service: light.turn_off
        data:
          entity_id: light.master_bedroom_lights
          transition: 5
