---
alias: areas_master_bedroom_lights_off
description: Turns the bedroom lights off when not motion has been detected for a while or when we go to sleep
mode: single
id: d75f8367-50e7-4959-b41c-d27d73a35471

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_master_bedroom
    to: "off"
    for:
      seconds: 60
  - platform: state
    entity_id:
      - sensor.marvin_status
      - sensor.laura_status
    to: "Slaapt"

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.presence_master_bedroom
        state: "off"
        for:
          seconds: 60
      - condition: state
        entity_id: sensor.marvin_status
        state: "Slaapt"
      - condition: state
        entity_id: sensor.laura_status
        state: "Slaapt"

action:
  - service: light.turn_off
    data:
      entity_id:
        - light.fibaro_master_bedroom
      transition: 5
