---
alias: areas_master_bedroom_lights
description: >-
  Controls the lights in the master bedroom.

  - When it is dark, the lights:
     - Turn on to bright and cool during the day
     - Turn on less bright and warmer in the evening

  - Whenever we go to sleep, the lights stay off

  - We can still turn the bedside table lights on/off, even when we're in sleep mode

  - Manual control is used to disable automation when we override the default behaviour

mode: restart
id: e1d01b47-8989-4d64-b7c1-c1f069f622f5
trace:
  stored_traces: 25

variables:
  current_light_scene: >-
     scene.masterbedroom_lights_{{ states("input_select.current_light_schedule") }}
  anchors:
    - &manual_control_on
      alias: "Set bedside left as manually controlled"
      action: input_boolean.turn_on
      target:
        entity_id: input_boolean.masterbedroom_manual_control

    - &manual_control_off
      alias: "Turn manual control off"
      action: input_boolean.turn_off
      target:
        entity_id: input_boolean.masterbedroom_manual_control

    - &turn_off
      alias: "Turn the lights off"
      action: light.turn_off
      data:
        entity_id: light.master_bedroom_lights
        transition: 5

    - &turn_on
      action: scene.turn_on
      data:
        transition: 1

    - &condition_is_dark
      alias: "Is it dark in the room?"
      condition: state
      entity_id: binary_sensor.master_bedroom_is_dark
      state: "on"

    - &condition_is_presence_detected
      alias: "Is presence detected in the room?"
      condition: state
      entity_id: binary_sensor.presence_master_bedroom
      state: "on"

    - &condition_is_room_mode
      alias: "Check the room mode"
      condition: state
      entity_id:
        - input_select.master_bedroom_room_mode

    - &condition_light_schedule_change
      alias: "Check if the automation got triggered by a light schedule change"
      condition: trigger
      id: light_schedule_change

    - &condition_someone_in_bed
      alias: "Check if someone is in bed, indicating lights need to dim"
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.someone_in_bed
          state: "on"
          for:
            seconds: 10
        - condition: time
          after: "21:00:00"

trigger:
  - trigger: homeassistant
    event: start

  - trigger: event
    event_type: automation_reloaded

  - trigger: state
    entity_id:
      - binary_sensor.presence_master_bedroom
    to: "on"

  - trigger: state
    entity_id:
      - input_select.master_bedroom_room_mode
    to: "Wakker"
    id: "house_mode_awake"

  - trigger: state
    entity_id:
      - input_select.master_bedroom_room_mode
    to:
      - "Net wakker"

  - trigger: state
    entity_id:
      - input_select.master_bedroom_room_mode
    to: "Slaap"
    id: "house_mode_someone_asleep"

  - trigger: state
    entity_id: binary_sensor.presence_master_bedroom
    to: "off"
    for:
      seconds: 60

  - trigger: state
    entity_id:
      - binary_sensor.master_bedroom_is_dark
      - input_select.bedroom_current_cover_scene

  - trigger: event
    event_type: "zha_event"
    event_data:
      device_id: "5256a27d772442b3a6065b595fc4a327"
      command: "single"
    id: "button_laura_single"

  - trigger: state
    entity_id: input_select.current_light_schedule
    id: light_schedule_change

  - trigger: state
    entity_id: binary_sensor.someone_in_bed
    to: "on"
    for:
      seconds: 10

  - trigger: state
    entity_id:
      - light.master_bedroom_lights
    from: "on"
    to: "off"
    id: "all_lights_off"

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Reset manual control at the start of the day"
        conditions:
          - or:
              - condition: trigger
                id: "reset"
              - condition: trigger
                id: "house_mode_awake"
        sequence:
          - *manual_control_off

      - alias: "When I click the button when I am already sleeping"
        conditions:
          - condition: trigger
            id: "button_marvin_single"
          - condition: state
            entity_id:
              - input_select.master_bedroom_room_mode
            state: "Slaap"
            for:
              seconds: 2
        sequence:
          - *manual_control_on
          - alias: "Toggle the light"
            action: light.toggle
            data:
              entity_id: light.master_bedroom_left
              brightness_pct: 3
              transition: 2

      - alias: "When Laura clicks the button when she is already sleeping"
        conditions:
          - condition: trigger
            id: "button_laura_single"
          - condition: state
            entity_id:
              - input_select.master_bedroom_room_mode
            state: "Slaap"
            for:
              seconds: 2
        sequence:
          - *manual_control_on
          - alias: "Toggle the light"
            action: light.toggle
            data:
              entity_id: light.master_bedroom_right
              brightness_pct: 3
              transition: 2

      - alias: >
          Turn the light off when we go to sleep, even if it is manually controlled
        conditions:
          - alias: "Someone goes to sleep"
            condition: trigger
            id: "house_mode_someone_asleep"
        sequence:
          - *turn_off

      - alias: "Turn off manual control when all lights are turned off"
        conditions:
          - alias: "All lights are off"
            condition: trigger
            id: "all_lights_off"
        sequence:
          - *manual_control_off

      - alias: "Stop automating lights when the lights are manually controlled"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.masterbedroom_manual_control
            state: "on"
        sequence: []

      - alias: "Turn the lights off when the blinds are fully open"
        conditions:
          - condition: state
            entity_id:
              - input_select.bedroom_current_cover_scene
            state: "ventilating"
        sequence:
          - *turn_off

      - alias: "Turn lights to dim when we just woke up (overriding light schedule)"
        conditions:
          - or:
              - and:
                  - <<: *condition_is_room_mode
                    state: "Net wakker"
                  - *condition_is_dark
                  - *condition_is_presence_detected
              - and:
                  - <<: *condition_is_room_mode
                    state: "Wakker"
                  - *condition_is_dark
                  - *condition_someone_in_bed
        sequence:
          - <<: *turn_on
            target:
              entity_id: scene.masterbedroom_lights_nachtlampje

      - alias: "Very subtly change the lights when a light schedule change is detected."
        conditions:
          - <<: *condition_is_room_mode
            state: "Wakker"
          - *condition_is_presence_detected
          - *condition_is_dark
          - *condition_light_schedule_change
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"
            data:
              transition: 120

      - alias: "Turn lights on according to light schedule"
        conditions:
          - <<: *condition_is_room_mode
            state: "Wakker"
          - *condition_is_dark
          - *condition_is_presence_detected
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"

    default:
      - *turn_off
