---
alias: areas_master_bedroom_room_mode
description: Determine the room mode
mode: queued
id: e153a617-7601-494d-8f23-13e6df694439

trigger:
  # Laura remote
  - platform: device
    domain: mqtt
    device_id: 7fb6275ba6053149bcde2015d9dccaa3
    type: action
    subtype: single
    id: "button_laura_one"

  - platform: device
    domain: mqtt
    device_id: 7fb6275ba6053149bcde2015d9dccaa3
    type: action
    subtype: hold
    id: "button_laura_hold"

  - platform: state
    id: "net_wakker_40m"
    entity_id:
      - input_select.master_bedroom_room_mode
    to: "Net wakker"
    for:
      minutes: 40

  - platform: state
    entity_id:
      - binary_sensor.presence_master_bedroom
    to: "off"
    for:
      minutes: 30

  - platform: time
    at:
      - "08:00:00"
      - "09:30:00"

variables:
  anchors:
    - &select_mode
      service: input_select.select_option
      entity_id: input_select.master_bedroom_room_mode

action:
  - choose:
      - conditions:
          - or:
              - condition: trigger
                id: "button_laura_one"
              - condition: trigger
                id: "button_marvin_one"
        sequence:
          - <<: *select_mode
            data:
              option: "Slaap"

      - conditions:
          - or:
              - condition: trigger
                id: "button_laura_hold"
              - condition: trigger
                id: "button_marvin_hold"
        sequence:
          - <<: *select_mode
            data:
              option: "Net wakker"

      - conditions:
          - condition: trigger
            id: "net_wakker_40m"
        sequence:
          - <<: *select_mode
            data:
              option: "Wakker"

      - conditions:
          - or:
              - and:
                  - condition: state
                    entity_id: binary_sensor.weekend
                    state: "on"
                  - condition: time
                    after: "09:30:00"
              - and:
                  - condition: state
                    entity_id: binary_sensor.weekend
                    state: "off"
                  - condition: time
                    after: "08:00:00"
          - condition: time
            before: "16:00:00"
          - condition: state
            entity_id:
              - input_select.master_bedroom_room_mode
            state: "Slaap"
          - condition: state
            entity_id:
              - binary_sensor.presence_master_bedroom
            state: "off"
            for:
              minutes: 30
        sequence:
          - <<: *select_mode
            data:
              option: "Net wakker"

    default: []
