---
description: Set volume of sonos based on motion sensor
alias: areas_master_bedroom_sonos_set_volume
mode: queued
id: c2250255-ca28-4aae-a516-721d618bd6da

trigger:
  - platform: state
    entity_id:
      - binary_sensor.presence_master_bedroom
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded

condition:
  - condition: state
    entity_id: binary_sensor.presence_master_bedroom
    state: "on"

action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.sonos_master_bedroom
      volume_level: 0.12
