---
blueprint:
  name: Auto group speakers
  description: >
    This blueprint automatically turns on media players in my 'master group',
    making sure I always have music everywhere around the house.
  domain: automation
  input:
    presence_entity:
      name: A sensor to detect presence (can be a motion sensor)
      selector:
        entity:
    target_media_player:
      name: Media player target
      description: Media player inside the master group to turn on
    no_presence_wait:
      name: Wait time
      description: Time to leave the sonos grouped after last presence is detected.
      default: 120
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    custom_conditions:
      name: Custom conditions
      default: []
      description: >
        A list of custom condititions that also have to be met before turning on
        the media player
    custom_state_triggers:
      name: Customer state triggers
      default: []
      description: >-
        A list of entities that will be used as additional state triggers for the
         automation

mode: queued
max_exceeded: silent

variables:
  target_media_player: !input target_media_player
  mass_entity: '{{ states("sensor.mass_media_entity") }}'
  anchors:
    - &turn_on
      alias: "Turn the child media player on"
      service: media_player.join
      target:
        entity_id: media_player.sonos_kitchen
      data:
        group_members:
          - !input target_media_player

    - &turn_off
      alias: "Turn the child media player off"
      service: media_player.unjoin
      data: {}
      target:
        entity_id: !input target_media_player

    - &play_media
      # Use a script with 'mode = single' to prevent race condition
      alias: "Start playing music on the master group"
      service: script.turn_on
      data:
        entity_id: script.turn_on_all_devices

trigger:
  - platform: state
    entity_id: !input presence_entity
    to: "on"

  - platform: state
    entity_id: !input custom_state_triggers

  - platform: state
    entity_id: !input presence_entity
    to: "off"
    for:
      seconds: !input no_presence_wait

  - platform: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: state
            entity_id:
              - !input presence_entity
              - input_boolean.setting_automatic_music
            state: "on"
          - "{{ is_state(mass_entity, 'playing') }}"
          - condition: and
            conditions: !input custom_conditions
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id:
                      - !input target_media_player
                    state: "playing"
            then:
              - *turn_on

      - conditions:
          - condition: state
            entity_id:
              - !input presence_entity
            state: "off"
            for:
              seconds: !input no_presence_wait
          - not:
              - condition: state
                entity_id:
                  - !input target_media_player
                state: "off"
        sequence:
          - *turn_off

      - conditions:
          - not:
              - and:
                  !input custom_conditions
        sequence:
          - *turn_off
