---
blueprint:
  name: Auto group speakers
  description: >
    This blueprint automatically turns on media players in my 'master group',
    making sure I always have music everywhere around the house.
  domain: automation
  input:
    presence_entity:
      name: A sensor to detect presence (can be a motion sensor)
      selector:
        entity:
    target_media_player:
      name: Media player target
      description: Media player inside the master group to turn on
    no_presence_wait:
      name: Wait time
      description: Time to leave the sonos grouped after last presence is detected.
      default: 120
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    custom_conditions:
      name: Custom conditions
      default: []
      description: >
        A list of custom condititions that also have to be met before turning on
        the media player
    custom_state_triggers:
      name: Customer state triggers
      default: []
      description: >-
        A list of entities that will be used as additional state triggers for the
         automation

mode: queued
max_exceeded: silent

variables:
  target_media_player: !input target_media_player
  mass_entity: '{{ states("sensor.mass_media_entity") }}'
  anchors:
    - &condition_in_group
      alias: "Check if the speaker is already part of the group"
      condition: template
      value_template: |-
        {{
          target_media_player
          in state_attr(mass_entity, 'group_members')
        }}

    - &group
      alias: "Ungroup the speaker from the target"
      action: media_player.join
      target:
        entity_id: media_player.mass_sonos_kitchen
      data:
        group_members:
          - !input target_media_player

    - &ungroup
      alias: "Group the speaker to the target"
      action: media_player.unjoin
      data: {}
      target:
        entity_id: !input target_media_player

trigger:
  - trigger: state
    entity_id: !input presence_entity
    to: "on"

  - trigger: state
    entity_id: !input custom_state_triggers

  - trigger: state
    entity_id: !input presence_entity
    to: "off"
    for:
      seconds: !input no_presence_wait

  - trigger: state
    entity_id:
      - media_player.mass_sonos_kitchen
    to: "playing"

  - trigger: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: state
            entity_id:
              - !input presence_entity
              - input_boolean.setting_automatic_music
            state: "on"
          - "{{ is_state(mass_entity, 'playing') }}"
          - condition: and
            conditions: !input custom_conditions
          - not:
            - *condition_in_group
        sequence:
          - if:
              - not:
                  - condition: state
                    entity_id:
                      - !input target_media_player
                    state: "playing"
            then:
              - *group

      - conditions:
          - condition: state
            entity_id:
              - !input presence_entity
            state: "off"
            for:
              seconds: !input no_presence_wait
          - not:
              - condition: state
                entity_id:
                  - !input target_media_player
                state: "off"
          - *condition_in_group
        sequence:
          - *ungroup

      - conditions:
          - not:
              - and:
                  !input custom_conditions
          - *condition_in_group
        sequence:
          - *ungroup

    default: []
