---
# I use circadian lighting for all the lights in my house.
# Whenever I want to manually override the brightness by using
# the mobile app or my IKEA remote, this automation sets a 
# boolean that will make sure the lights do not change back
# to the circadian value.
alias: areas_bedroom_automatic_lighting_off
mode: single
max_exceeded: silent
trigger:
  platform: event
  event_type: adaptive_lighting.manual_control
variables:
  light: "{{ trigger.event.data.entity_id }}"
  switch: "{{ trigger.entity_id }}"
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedroom_automatic_lighting
  - service: notify.mobile_app_marvins_iphone
    data_template: 
      message: "{{ light }}"