---
alias: areas_bedroom_lights_on
description: Turns the bedroom lights on when motion has been detected
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.presence_bedroom
  - platform: state
    entity_id: variable.bedroom_darklight
condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: 'off'
  - condition: state
    entity_id: binary_sensor.presence_bedroom
    state: 'on'
  - "{{ not is_state('sensor.marvin_status', 'Slaapt') }}"
  - "{{ not is_state('sensor.laura_status', 'Slaapt') }}"
  - condition: state
    entity_id: variable.bedroom_darklight
    state: 'dark'
action:
  - service: script.sunlight
    data:
      entities:
        - light.bedside_left
        - light.bedside_right
      turn_on: true