---
description: "Set a variable to dark to keep track of whether it is light or dark"
alias: areas_bedroom_set_to_dark
mode: queued
id: 8cb1564f-16e7-4eb7-8988-19ed74322689

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_bedroom_luminance") | int < 20 }}'

condition:
  - '{{ states("sensor.pir_bedroom_luminance") | int < 20 }}'

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bedroom_darklight
      option: 'dark'