---
description: "Set a variable to light to keep track of whether it is light or dark"
alias: areas_bedroom_set_to_light
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_bedroom_luminance") | int > 30 and is_state("light.bedside_left", "off") }}'
    for:
      seconds: 60
condition:
  - '{{ states("sensor.pir_bedroom_luminance") | int > 30 and is_state("light.bedside_left", "off") }}'
action:
  service: variable.set_variable
  data:
    variable: bedroom_darklight
    value: 'light'