---
description: "Set a variable to dark to keep track of whether it is light or dark"
alias: areas_bedroom_set_to_dark
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: template
    value_template: '{{ states("sensor.pir_bedroom_luminance") | int < 20 }}'
condition:
  - '{{ states("sensor.pir_bedroom_luminance") | int < 20 }}'
action:
  service: variable.set_variable
  data:
    variable: bedroom_darklight
    value: 'dark'