---
alias: areas_bedroom_small_blinds
description: >-
  Automate blinds in the small bedroom
mode: single
max_exceeded: silent
id: a63e7f88-b3fd-4628-a4d1-327070e0522b

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: d2facfeac2ccc4f9eb4da6139c01da41
      value: 14
    id: "small_bedroom_double_click"

action:
  choose:
    - conditions:
        - condition: state
          entity_id:
            - input_select.smallbedroom_current_cover_scene
          state: "closed"

      sequence:
        - service: scene.turn_on
          target:
            entity_id: scene.smallbedroom_cover_open
  default:
    - service: scene.turn_on
      target:
        entity_id: scene.smallbedroom_cover_closed
