---
alias: areas_bedroom_small_blinds
description: >-
  Automate blinds in the small bedroom
mode: single
max_exceeded: silent
id: a63e7f88-b3fd-4628-a4d1-327070e0522b

trigger:
  - platform: state
    entity_id:
      - event.hue_tap_dial_switch_small_bedroom_button_4

  - platform: state
    entity_id:
      - binary_sensor.is_hot_day
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.sun_should_close_south_blinds
    to: "on"

action:
  choose:
    - conditions:
        - condition: state
          entity_id:
            - event.hue_tap_dial_switch_small_bedroom_button_4
          attribute: "event_type"
          state: "repeat"
        - condition: state
          entity_id:
            - input_select.smallbedroom_current_cover_scene
          state: "closed"
      sequence:
        - service: scene.turn_on
          target:
            entity_id: scene.smallbedroom_cover_open

    - conditions:
        - condition: state
          match: any
          entity_id:
            - event.hue_tap_dial_switch_small_bedroom_button_1
            - event.hue_tap_dial_switch_small_bedroom_button_2
            - event.hue_tap_dial_switch_small_bedroom_button_3
            - event.hue_tap_dial_switch_small_bedroom_button_4
          attribute: "event_type"
          state: "repeat"
        - condition: state
          entity_id:
            - input_select.smallbedroom_current_cover_scene
          state: "open"
      sequence:
        - service: scene.turn_on
          target:
            entity_id: scene.smallbedroom_cover_closed

    - conditions:
        - or:
            - condition: state
              entity_id:
                - binary_sensor.sun_should_close_south_blinds
              state: "on"
            - alias: Keep the heat out of the house on hot days
              condition: state
              entity_id:
                - binary_sensor.is_hot_day
              state: "on"
      sequence:
        - service: scene.turn_on
          target:
            entity_id: scene.smallbedroom_cover_closed

  default: []
