---
alias: areas_bedroom_small_blinds
description: >-
  Automate blinds in the small bedroom
mode: single
max_exceeded: silent
id: a63e7f88-b3fd-4628-a4d1-327070e0522b

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      # There is no sensor in the small bedroom, so I use the sensor in the living room which is a pretty good approach
      # to measure when it is getting dark
      - input_select.livingroom_darklight
      # Include auto-shut blinds on hot days
      - binary_sensor.sun_should_close_south_blinds
  - platform: time
    at:
      - "08:00:00"
      - "10:00:00"
      - "19:00:00"
  # There is a weird bug in the ZHA communication where HA thinks the blinds are closing, but nothing is really happening.
  # The state then pops back to 'closed', so using this a trigger to retry the automation.
  - platform: state
    entity_id: cover.small_bedroom
    from: opening
    to: closed
  - platform: state
    entity_id: cover.small_bedroom
    from: closing
    to: open

condition:
  - condition: state
    entity_id: input_boolean.setting_guest_mode
    state: "off"

action:
  choose:
    - conditions:
        - condition: time
          before: "19:00:00"
        - condition: state
          entity_id: input_select.livingroom_darklight
          state: "light"
        - condition: or
          conditions:
            # Open: Workdays at 8am
            - condition: and
              conditions:
                - condition: time
                  after: "08:00:00"
                - condition: state
                  entity_id: binary_sensor.workday
                  state: "on"
            # Open: Weekend days and holidays at 10
            - condition: and
              conditions:
                - condition: time
                  after: "10:00:00"
                - condition: state
                  entity_id: binary_sensor.workday
                  state: "off"
        - condition: state
          entity_id:
            - binary_sensor.sun_should_close_south_blinds
          state: "off"
      sequence:
        - service: cover.open_cover
          target:
            entity_id: cover.small_bedroom
  default:
    - service: cover.close_cover
      target:
        entity_id: cover.small_bedroom
