---
# A binary indicator tracking whether it is light or dark in the room
binary_sensor:
  - name: attic_is_dark
    unique_id: e34a8c0f-3485-45b9-b99a-cdc34b8465ba
    state: >
      {%-
        if states("sensor.pir_third_floor_stairs_illuminance") | int > 8
        and is_state("light.fibaro_third_floor_stairs", "off")
      -%}
        off
      {%- else -%}
        on
      {%- endif -%}
