---
# A binary indicator tracking whether it is light or dark in the room
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.pir_hall_downstairs_illuminance
    above: 15
    for:
      seconds: 5
  - platform: numeric_state
    entity_id:
      - sensor.pir_hall_downstairs_illuminance
    above: 35
    for:
      seconds: 5
  - platform: numeric_state
    entity_id:
      - sensor.pir_hall_downstairs_illuminance
    below: 15
    for:
      seconds: 5

binary_sensor:
  - name: hall_is_dark
    unique_id: 0fb6d0aa-5179-408f-acea-b6864a7e994e
    state: >
      {%-
        if (
          states("sensor.pir_hall_downstairs_illuminance") | int > 15
          and is_state("light.wc", "off")
          and is_state("light.hall_downstairs", "off")
        )
        or states("sensor.pir_hall_downstairs_illuminance") | int > 35

      -%}
        off
      {%- else -%}
        on
      {%- endif -%}
