---
# A binary indicator tracking whether it is light or dark in the room
binary_sensor:
  - name: hall_upstairs_is_dark
    unique_id: 835f73a4-2c35-4c71-bf6a-863cadac77a6
    state: >
      {%-
        if states("sensor.pir_hall_upstairs_illuminance") | int > 18
        and is_state("light.hall_upstairs", "off")
      -%}
        off
      {%- else -%}
        on
      {%- endif -%}
