---
# A binary indicator tracking whether it is light or dark in the room
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.livingroom_luminance_fp300
    above: 8
    for:
      seconds: 5
  - platform: numeric_state
    entity_id:
      - sensor.livingroom_luminance_fp300
    above: 60
    for:
      seconds: 5
  - platform: numeric_state
    entity_id:
      - sensor.livingroom_luminance_fp300
    below: 8
    for:
      seconds: 5

binary_sensor:
  - name: livingroom_is_dark
    unique_id: 4eea3312-788b-4007-a87a-b1c68904dae3
    state: >
      {%-
        if (
          states("sensor.livingroom_luminance_fp300") | int > 8
          and is_state("light.dinner_door", "off")
          and is_state("light.kitchen_spot", "off")
          and is_state("switch.sync_box_light_sync", "off")
        )
        or states("sensor.livingroom_luminance_fp300") | int > 60
      -%}
        off
      {%- else -%}
        on
      {%- endif -%}
