---
# A binary indicator tracking whether it is light or dark in the room
binary_sensor:
  - name: livingroom_is_dark
    unique_id: 4eea3312-788b-4007-a87a-b1c68904dae3
    state: >
      {%-
        if (
          states("sensor.pir_livingroom_luminance") | int > 10
          and is_state("light.dinner", "off")
        )
        or states("sensor.pir_livingroom_luminance") | int > 25
      -%}
        off
      {%- else -%}
        on
      {%- endif -%}
