---
# A binary indicator tracking whether it is light or dark in the room
binary_sensor:
  - name: mancave_is_dark
    unique_id: bbdb9631-14dd-4337-8c15-42db62fc50f2
    state: >
      {%-
        if (
          states("sensor.pir_mancave_illuminance") | int > 20
          and is_state("light.mancave", "off")
        ) or states("sensor.pir_mancave_illuminance") | int > 75
      -%}
        off
      {%- else -%}
        on
      {%- endif -%}
