---
alias: areas_kitchen_blinds
description: >
  Control the blinds in the kitchen by using
   - Sun elevation
   - Whenever we wake up
mode: single
max_exceeded: silent
id: 38622ce4-5865-45c4-8cb8-7b3b54801280

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_select.livingroom_room_mode

  - platform: state
    entity_id:
      - input_boolean.setting_manual_blinds
      - input_boolean.kitchen_cover_manual_control

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    below: 0

  - platform: numeric_state
    entity_id:
      - sensor.sun_adjusted_elevation
    above: 0

  - platform: time
    at: "20:45:00"
    id: "time_close_kitchen"

  - platform: device
    device_id: 063e0720e7172ed87824f117033874a5
    domain: hue
    type: initial_press
    subtype: 3
    unique_id: c6db055a-584c-4e75-b9cc-9f153d5ba604
    id: "hue_dimmer_down_press"

  - platform: device
    device_id: 063e0720e7172ed87824f117033874a5
    domain: hue
    type: initial_press
    subtype: 2
    unique_id: 140cfc6c-e965-40a7-9f55-976627206e31
    id: "hue_dimmer_up_press"

  - platform: state
    entity_id:
      - scene.kitchen_cover_halfclosed
      - scene.kitchen_cover_halfopen
    id: kitchen_blinds

  - platform: time
    at: "03:00:00"
    id: "reset"

variables:
  anchors:
    - &halfclosed
      alias: "Close the blinds halfway"
      service: scene.turn_on
      target:
        entity_id: scene.kitchen_cover_halfclosed

    - &halfopen
      alias: "Open the blinds halfway"
      service: scene.turn_on
      target:
        entity_id: scene.kitchen_cover_halfopen

    - &manual_control_on
      alias: "Set manual control to on, so the blinds stay closed"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.kitchen_cover_manual_control

    - &manual_control_off
      alias: "Reset manual control to on, so the blinds are automated again"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.kitchen_cover_manual_control

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      - alias: "Close the blinds when hue remote down is pressed"
        conditions:
          - condition: trigger
            id: "hue_dimmer_down_press"
        sequence:
          - *halfclosed
          - *manual_control_on

      - alias: "Open the blinds when hue remote up is pressed"
        conditions:
          - condition: trigger
            id: "hue_dimmer_up_press"
        sequence:
          - *halfopen
          - *manual_control_off

      - alias: "Check if we manually changed the blinds"
        conditions:
          - condition: trigger
            id: kitchen_blinds
        sequence:
          - choose:
              - conditions:
                  - alias: "It was changed by a user"
                    condition: template
                    value_template: "{{ trigger.to_state.context.user_id != None }}"
                sequence:
                  - *manual_control_on

      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: "reset"
        sequence:
          - *manual_control_off

      - alias: "Stop automating the blinds when manual control is on"
        conditions:
          - condition: state
            entity_id:
              - input_boolean.kitchen_cover_manual_control
            state: "on"
        sequence:
          - stop: "Blinds are manually controlled"

      - alias: "Half closed when everyone is asleep or it is passed 8:45pm"
        conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id:
                  - sensor.sun_adjusted_elevation
                below: 0
              - condition: time
                after: "20:45:00"
              - condition: state
                entity_id: input_select.livingroom_room_mode
                state:
                  - "Slaap"
              - and:
                  - condition: state
                    entity_id: input_select.livingroom_room_mode
                    state:
                      - "Net wakker"
                  - condition: state
                    entity_id:
                      - input_select.kitchen_current_cover_scene
                    state: "halfclosed"
        sequence:
          - *halfclosed

    default:
      - *halfopen
