---
alias: areas_kitchen_blinds
description: >
  Control the blinds in the kitchen by using 
   - Sun elevation
   - Whenever we wake up
mode: single
max_exceeded: silent
id: 38622ce4-5865-45c4-8cb8-7b3b54801280

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      # Whether we just woke up / gone to sleep
      - binary_sensor.house_mode_everyone_asleep
      - binary_sensor.house_mode_someone_awake
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - input_boolean.setting_manual_blinds
  # Sun
  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    below: 1.0
  - platform: numeric_state
    entity_id:
      - sensor.sun_elevation
    above: 1.0
  # Close the kitchen blinds at 20:30, even if the sun has not set yet
  - platform: time
    at: "20:30:00"
    id: "time_close_kitchen"

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_blinds
    state: "off"

action:
  - choose:
      # Disable fully closed since the wife wants some decoration in the
      # window sill.
      # Fully closed
      # - conditions:
      #     - condition: or
      #       conditions:
      #         - condition: state
      #           entity_id: binary_sensor.house_mode_everyone_asleep
      #           state:
      #             - "on"
      #   sequence:
      #     - service: scene.turn_on
      #       target:
      #         entity_id: scene.kitchen_cover_closed

      # Half closed
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id:
                  - sensor.sun_elevation
                below: 1.0
              - condition: time
                after: "20:30:00"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.kitchen_cover_halfclosed

    # Half open
    default:
      - service: scene.turn_on
        target:
          entity_id: scene.kitchen_cover_halfopen
