---
alias: areas_kitchen_climate
description: Manages the climate in our kitchen
id: 7b9f8a4f-a43f-4e1f-b28e-fdefc8f113bb
mode: queued

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_select.livingroom_room_mode
      - binary_sensor.everyone_left_home
      - binary_sensor.house_mode_everyone_at_home_working
      - input_boolean.setting_guest_mode
    from: ~

  - platform: state
    entity_id: binary_sensor.garden_door_open
    for:
      seconds: 10

  - platform: time
    at:
      - "21:00:00"
      - "18:00:00"

variables:
  anchors:
    - &target
      target:
        entity_id: climate.kitchen

    - &turn_on
      <<: *target
      alias: "Turn on heating"
      service: climate.set_hvac_mode
      data:
        hvac_mode: "heat"

    - &turn_down
      <<: *target
      alias: "Turn down kitchen climate"
      service: climate.set_temperature
      data:
        temperature: 15.0

    - &turn_up
      <<: *target
      alias: "Turn down kitchen climate"
      service: climate.set_temperature
      data:
        temperature: 20.0

    - &turn_low
      <<: *target
      alias: "Turn down kitchen climate"
      service: climate.set_temperature
      data:
        temperature: 19.0

    - &windows_and_doors_closed
      alias: "Verify whether the doors and windows are closed"
      condition: state
      entity_id: binary_sensor.garden_door_open
      state: "off"

action:
  - choose:
      - conditions:
          - alias: "When the house is in away mode"
            condition: state
            entity_id: binary_sensor.everyone_left_home
            state: "on"
          - alias: "And there are no guests over"
            condition: state
            entity_id: input_boolean.setting_guest_mode
            state: "off"
        sequence:
          - *turn_down

      - conditions:
          - alias: "When the house is in away mode"
            condition: state
            entity_id: binary_sensor.house_mode_everyone_at_home_working
            state: "on"
          - alias: "And there are no guests over"
            condition: state
            entity_id: input_boolean.setting_guest_mode
            state: "off"
        sequence:
          - *turn_down

      - conditions:
          - alias: "When the house is in sleep mode"
            condition: state
            entity_id: input_select.livingroom_room_mode
            state: "Slaap"
        sequence:
          - *turn_down

      - alias: "Turn down the heating before bedtime"
        conditions:
          - condition: time
            after: "18:00:00"
          - condition: time
            before: "21:00:00"
        sequence:
          - *turn_low

      - alias: "Turn down the heating before bedtime"
        conditions:
          - or:
              - condition: time
                after: "21:00:00"
              - condition: time
                before: "06:00:00"
        sequence:
          - *turn_down

      - alias: "Turn up the heating in the morning"
        conditions:
          - condition: state
            entity_id: input_select.livingroom_room_mode
            state: "Wakker"
          - *windows_and_doors_closed
        sequence:
          - *turn_on
          - *turn_up
