---
alias: kitchen_cooking_mode
description: Toggle cooking mode by the press of a button
mode: queued
id: b9982ead-5320-48cb-8b44-b7df02698f32

trigger:
  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "b2bbc724616dc6968e36850327263ed8"
      command: "single"

  - platform: event
    event_type: "zha_event"
    event_data:
      device_id: "b2bbc724616dc6968e36850327263ed8"
      command: "double"

action:
  - service: input_boolean.toggle
    target:
      entity_id: input_boolean.house_mode_cooking
