---
alias: kitchen_cooking_mode
description: Toggle cooking mode by the press of a button
mode: queued
id: b9982ead-5320-48cb-8b44-b7df02698f32

trigger:
  - platform: device
    domain: mqtt
    device_id: 8a8d8e4f3443c4af9343605b2b2d67b8
    type: action
    subtype: single

  - platform: device
    domain: mqtt
    device_id: 8a8d8e4f3443c4af9343605b2b2d67b8
    type: action
    subtype: double

action:
  - service: input_boolean.toggle
    target:
      entity_id: input_boolean.house_mode_cooking
