---
alias: areas_kitchen_lights
description: Turns the hallway lights on when motion has been detected
mode: queued
id: 166a33e7-2c06-419b-b12d-147aecaa1362
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id: binary_sensor.presence_kitchen
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_kitchen
    to: "off"
    for:
      seconds: 50

  - platform: state
    entity_id: binary_sensor.presence_kitchen
    to: "off"
    for:
      seconds: 5
    id: "presence_off_5s"

  - platform: state
    entity_id: input_select.current_light_schedule
    id: light_schedule_change

  - platform: state
    entity_id: media_player.apple_tv
    to: "playing"
    id: "apple_tv_playing"

  - platform: state
    entity_id:
      - binary_sensor.kitchen_is_dark
      - input_boolean.house_mode_cooking

variables:
  current_light_scene: 'scene.kitchen_lights_{{ states("input_select.current_light_schedule") }}'
  anchors:
    - &turn_on
      alias: "Turn on the lights"
      service: scene.turn_on
      data:
        transition: 1

    - &turn_off
      alias: "Turn the lights off"
      service: light.turn_off
      data:
        entity_id: light.led_kitchen
        transition: 3

    - &is_presence_detected
      alias: "Presence is detected"
      condition: state
      entity_id: binary_sensor.presence_kitchen
      state: "on"

    - &is_dark
      alias: "It is dark in the hall"
      condition: state
      entity_id: binary_sensor.kitchen_is_dark
      state: "on"

    - &condition_light_schedule_change
      alias: "Check if the automation got triggered by a light schedule change"
      condition: trigger
      id: light_schedule_change

condition:
  - condition: state
    alias: "Check if we can automate the lights"
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Turn the lights off faster when we are watching TV."
        conditions:
          - or:
              - condition: trigger
                id: "presence_off_5s"
              - condition: trigger
                id: "apple_tv_playing"
          - condition: state
            entity_id:
              - input_select.livingroom_current_lights_scene
            state: "movie"
        sequence:
          - *turn_off

      - alias: "Turn on bright lights when cooking"
        conditions:
          - *is_presence_detected
          - *is_dark
          - condition: state
            entity_id:
              - input_boolean.house_mode_cooking
            state: "on"
        sequence:
          - <<: *turn_on
            target:
              entity_id: scene.kitchen_lights_concentreren

      - alias: "Very subtly change the lights when a light schedule change is detected."
        conditions:
          - *is_presence_detected
          - *is_dark
          - *condition_light_schedule_change
        sequence:
          - <<: *turn_on
            target:
              entity_id: '{{ current_light_scene }}'
            data:
              transition: 120

      - alias: "Just turn the lights on according to schedule"
        conditions:
          - *is_presence_detected
          - *is_dark
        sequence:
          - <<: *turn_on
            target:
              entity_id: '{{ current_light_scene }}'

      - alias: "Ignore 5s trigger when not in movie scene"
        conditions:
          - condition: trigger
            id: "presence_off_5s"
        sequence:
          - stop: "Ignore this trigger"

    default:
      - *turn_off
