---
alias: areas_kitchen_lights
description: Turns the hallway lights on when motion has been detected
mode: queued
id: 166a33e7-2c06-419b-b12d-147aecaa1362
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id: binary_sensor.presence_kitchen
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_kitchen
    to: "off"
    for:
      seconds: 50

  - platform: state
    entity_id: binary_sensor.presence_kitchen
    to: "off"
    for:
      seconds: 5
    id: "presence_off_5s"

  - platform: state
    entity_id: media_player.apple_tv
    to: "playing"
    id: "apple_tv_playing"

  - platform: state
    entity_id:
      - binary_sensor.kitchen_is_dark
      - input_boolean.house_mode_cooking
      - input_select.current_light_schedule

variables:
  anchors:
    - &lights_normal
      alias: "Turn the lights to normal scene"
      service: scene.turn_on
      data:
        entity_id: scene.kitchen_lights_normal
        transition: 3

    - &lights_dim
      alias: "Turn the lights to dim scene"
      service: scene.turn_on
      data:
        entity_id: scene.kitchen_lights_dim
        transition: 3

    - &lights_bright
      alias: "Turn the lights to bright scene"
      service: scene.turn_on
      data:
        entity_id: scene.kitchen_lights_bright
        transition: 3

    - &lights_night
      alias: "Turn the lights to bright scene"
      service: scene.turn_on
      data:
        entity_id: scene.kitchen_lights_night
        transition: 3

    - &lights_off
      alias: "Turn the lights off"
      service: light.turn_off
      data:
        entity_id: light.led_kitchen
        transition: 3

    - &is_presence_detected
      alias: "Presence is detected"
      condition: state
      entity_id: binary_sensor.presence_kitchen
      state: "on"

    - &is_dark
      alias: "It is dark in the hall"
      condition: state
      entity_id: binary_sensor.kitchen_is_dark
      state: "on"

    - &is_light_schedule
      alias: "Check current light schedule"
      condition: state
      entity_id: input_select.current_light_schedule

condition:
  - condition: state
    alias: "Check if we can automate the lights"
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - alias: "Turn the lights off faster when we are watching TV."
        conditions:
          - or:
              - condition: trigger
                id: "presence_off_5s"
              - condition: trigger
                id: "apple_tv_playing"
          - condition: state
            entity_id:
              - input_select.livingroom_current_lights_scene
            state: "movie"
        sequence:
          - *lights_off

      - conditions:
          - *is_presence_detected
          - *is_dark
          - condition: state
            entity_id:
              - input_boolean.house_mode_cooking
            state: "on"
        sequence:
          - *lights_bright

      - conditions:
          - *is_presence_detected
          - *is_dark
          - <<: *is_light_schedule
            state: "dim"
        sequence:
          - *lights_dim

      - conditions:
          - *is_presence_detected
          - *is_dark
          - <<: *is_light_schedule
            state: "normal"
        sequence:
          - *lights_normal

      - conditions:
          - *is_presence_detected
          - *is_dark
          - <<: *is_light_schedule
            state: "night"
        sequence:
          - *lights_night

      - alias: "Ignore 5s trigger when not in movie scene"
        conditions:
          - condition: trigger
            id: "presence_off_5s"
        sequence:
          - stop: "Ignore this trigger"

    default:
      - *lights_off
