---
description: >
  Automatically play music in the living room
alias: areas_kitchen_play_music
id: bdbbd6e8-fb02-4777-980e-dffd9865995c
mode: single
trace:
  stored_traces: 25

trigger:
  - trigger: state
    entity_id:
      - binary_sensor.presence_house
    to: "on"

  - trigger: state
    entity_id:
      - input_select.livingroom_room_mode
    for:
      seconds: 15

  - trigger: state
    entity_id:
      - media_player.living_room_android
    to: "off"
    for:
      minutes: 5

  - trigger: state
    entity_id: binary_sensor.presence_house
    to: "off"
    for:
      seconds: 900

  - trigger: state
    entity_id:
      - media_player.living_room_android
    to: "on"

  - trigger: homeassistant
    event: start

  - trigger: state
    entity_id:
      - input_boolean.setting_automatic_music
    id: "setting_automatic_music"
    to: "off"

  - trigger: state
    entity_id:
      - input_boolean.setting_automatic_music
    to: "on"
    for:
      seconds: 15

  - trigger: time
    at:
      - "07:00:30"
      - "21:30:00"

variables:
  mass_entity: '{{ states("sensor.mass_media_entity") }}'
  anchors:
    - &condition_watching_tv
      alias: "We're watching TV"
      condition: state
      entity_id:
        - media_player.living_room_android
      state: "on"

    - &play_media
      alias: "Start playing music on the master group"
      action: media_player.media_play
      data: {}
      target:
        entity_id: "{{ mass_entity }}"

    - &turn_on
      alias: "Ensure the media player is on"
      action: media_player.turn_on
      data: {}
      target:
        entity_id: "{{ mass_entity }}"

    - &set_shuffle
      alias: "Ensure shuffle is on"
      action: media_player.shuffle_set
      target:
        entity_id: "{{ mass_entity }}"
      data:
        shuffle: true

    - &pause
      alias: "Pause the player"
      action: media_player.media_pause
      data: {}
      target:
        entity_id: "{{ mass_entity }}"

    - &mute
      alias: "Mute the player"
      action: media_player.volume_mute
      data:
        is_volume_muted: true
      target:
        entity_id: "{{ mass_entity }}"

    - &unmute
      alias: "Unmute the player"
      action: media_player.volume_mute
      data:
        is_volume_muted: false
      target:
        entity_id: "{{ mass_entity }}"

action:
  - choose:
      - conditions:
          - or:
              - condition: time
                after: "21:30:00"
              - condition: time
                before: "07:00:00"
              - alias: "No presence is detected"
                condition: state
                entity_id:
                  - binary_sensor.presence_house
                state: "off"
                for:
                  seconds: 900
              - alias: "Or we switched off automatic music"
                condition: state
                entity_id:
                  - input_boolean.setting_automatic_music
                state: "off"
        sequence:
          - *pause

      - conditions:
          - condition: state
            entity_id:
              - binary_sensor.presence_house
              - input_boolean.setting_automatic_music
            state: "on"
          - not:
              - *condition_watching_tv
          - "{{ not is_state(mass_entity, 'playing') }}"
          - not:
              - condition: state
                entity_id:
                  - input_select.livingroom_room_mode
                state: "Slaap"
        sequence:
          - if:
              - "{{ is_state(mass_entity, 'off') }}"
            then:
              - *turn_on
          - if:
              - "{{ not is_state(mass_entity, 'playing') }}"
            then:
              - *play_media
          - if:
              - "{{ is_state_attr(mass_entity, 'is_volume_muted', true) }}"
            then: *unmute
          - delay:
              seconds: 10

      - conditions:
          - *condition_watching_tv
          - "{{ not is_state(mass_entity, 'off') }}"
        sequence:
          - *mute
