---
alias: house_downstairs_doorbell_message
description: Sets a custom doorbell message based on person detection
mode: queued
id: e18ffbe8-61c7-4a7c-a698-7b9beeb6ec12

trigger:
  - platform: state
    entity_id:
      - binary_sensor.g4_doorbell_motion

action:
  - alias: "Display greeting based on the day or the time of day"
    choose:
      - conditions:
          - "{{ now().month == 12 and now().day > 23 }}"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.g4_doorbell_doorbell_text
              message: "🎄 FIJNE FEESTDAGEN!"
              duration: 2

      - conditions:
          - condition: time
            after: "18:00:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.g4_doorbell_doorbell_text
              message: "GOEDENAVOND!"
              duration: 2

      - conditions:
          - condition: time
            after: "12:00:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.g4_doorbell_doorbell_text
              message: "GOEDEMIDDAG!"
              duration: 2

      - conditions:
          - condition: time
            after: "06:00:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.g4_doorbell_doorbell_text
              message: "GOEDEMORGEN!"
              duration: 2

      - conditions:
          - condition: time
            after: "00:00:00"
        sequence:
          - service: unifiprotect.set_doorbell_message
            data:
              entity_id: select.g4_doorbell_doorbell_text
              message: "GOEDENACHT!"
              duration: 2

    default:
      - service: unifiprotect.set_doorbell_message
        data:
          entity_id: select.g4_doorbell_doorbell_text
          message: "WELKOM!"
          duration: 2
