---
alias: house_downstairs_doorbell_message
description: Sets a custom doorbell message based on person detection
mode: queued
id: e18ffbe8-61c7-4a7c-a698-7b9beeb6ec12

trigger:
  - platform: state
    entity_id:
      - binary_sensor.g4_doorbell_motion

action:
  - alias: "Display greeting based on the day or the time of day"
    choose:
      - conditions:
          - "{{ now().month == 12 and now().day > 23 }}"
        sequence:
          - service: text.set_value
            target:
              entity_id: text.g4_doorbell_doorbell
            data:
              value: "🎄 FIJNE FEESTDAGEN!"

      - conditions:
          - condition: time
            after: "18:00:00"
        sequence:
          - service: text.set_value
            target:
              entity_id: text.g4_doorbell_doorbell
            data:
              value: "GOEDENAVOND!"

      - conditions:
          - condition: time
            after: "12:00:00"
        sequence:
          - service: text.set_value
            data:
              entity_id: text.g4_doorbell_doorbell
              message: "GOEDEMIDDAG!"
              duration: 2

      - conditions:
          - condition: time
            after: "06:00:00"
        sequence:
          - service: text.set_value
            target:
              entity_id: text.g4_doorbell_doorbell
            data:
              value: "GOEDEMORGEN!"

      - conditions:
          - condition: time
            after: "00:00:00"
        sequence:
          - service: text.set_value
            target:
              entity_id: text.g4_doorbell_doorbell
            data:
              value: "GOEDENACHT!"

    default:
      - service: text.set_value
        target:
          entity_id: text.g4_doorbell_doorbell
        data:
          value: "WELKOM!"
