---
description: >
  Automatically select the light schedule that suits the situation
  or time of day
alias: house_light_schedule
id: 5840c714-45b1-4f4a-b805-023a268d0813
mode: single

trigger:
  - platform: state
    entity_id:
      - input_select.livingroom_room_mode

  - platform: time
    at:
      - "07:00:00"
      - "08:00:00"
      - "10:00:00"
      - "17:00:00"
      - "20:00:00"
      - "22:00:00"
      - "00:00:00"

  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

variables:
  anchors:
    - &select_schedule
      alias: "Select the schedule"
      service: input_select.select_option
      target:
        entity_id: input_select.current_light_schedule

action:
  - choose:
      - conditions:
          - condition: state
            entity_id:
              - input_select.livingroom_room_mode
            state: "Slaap"
        sequence:
          - <<: *select_schedule
            data:
              option: "nachtlampje"

      - conditions:
          - condition: time
            alias: "It is after 10pm"
            after: "22:00:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "rusten"

      - conditions:
          - condition: time
            alias: "It is after 8pm"
            after: "20:00:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "ontspannen"

      - conditions:
          - condition: time
            alias: "It is after 5pm"
            after: "17:00:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "lezen"

      - conditions:
          - condition: time
            alias: "It is after 10am"
            after: "10:00:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "concentreren"

      - conditions:
          - condition: time
            alias: "It is after 8am"
            after: "08:00:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "energie"

      - conditions:
          - condition: time
            alias: "It is after 7am"
            after: "07:00:00"
        sequence:
          - <<: *select_schedule
            data:
              option: "ontspannen"

    default:
      - <<: *select_schedule
        data:
          option: "rusten"
