---
description: >
  Automatically play some tunes in the house when we wake up
  on a weekend day or holiday
alias: house_play_music
id: 32df87f3-7bbb-4c20-b9e8-bf641ad8314c

trigger:
  - platform: state
    entity_id: binary_sensor.house_mode_someone_just_awake
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.house_mode_someone_asleep
    to: "off"

condition:
  condition: and
  conditions:
    - condition: state
      entity_id:
        - binary_sensor.house_mode_someone_asleep
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.weekend
          state: "on"
        - condition: state
          entity_id: binary_sensor.holiday
          state: "on"

action:
  - service: script.play_random_music
    data:
      sonos_entity: media_player.sonos_livingroom
      genre: "chill"
  - service: media_player.volume_set
    data:
      entity_id: media_player.sonos_livingroom
      volume_level: 0.08
