---
description: >
  Automatically fill the queue of the master media player
  with music that suits the music schedule of the day
alias: house_populate_music_queue
id: 7f94ed28-03ab-4dbf-b509-973f867931a9
mode: queued

trigger:
  - platform: state
    entity_id:
      - input_select.current_music_schedule
      - input_boolean.setting_automatic_music
      - input_select.music_source

  - platform: homeassistant
    event: start
    id: "ha_start"

variables:
  mass_entity: '{{ states("sensor.mass_media_entity") }}'
  just_awake_music:
    - "Classical Meditation"
    - "Tranquil spa day"
    - "ytmusic://playlist/RDCLAK5uy_nZJzoZEBYRptA2XXskbxGTvKkevapT_F4"
  early_morning_music:
    - "ytmusic://playlist/PLN_V7YvbzWCrFWD1vnmiXxsQPxnTyouT5"
    - "ytmusic://playlist/PLN_V7YvbzWCrr4ChmL43IHe-b-U_e1Ork"
    - "ytmusic://playlist/PLDKkQBH8I6JCwku89bRRI-Aq1IkXr4jIA"
  morning_music:
    - "ytmusic://playlist/PLN_V7YvbzWCrr4ChmL43IHe-b-U_e1Ork"
    - "ytmusic://playlist/PLN_V7YvbzWCpHsXNr6wKjwo_jRi-yx1Ye"
  day_music:
    - "ytmusic://playlist/PLN_V7YvbzWCpHsXNr6wKjwo_jRi-yx1Ye"
    - "ytmusic://playlist/PLN_V7YvbzWCrUeyO9haUxgUTo2jDDjDVM"
  evening_music:
    - "ytmusic://playlist/PLN_V7YvbzWCpHsXNr6wKjwo_jRi-yx1Ye"
  christmas_music:
    - "Christmas Hits"

  active_schedule: '{{ states("input_select.current_music_schedule") }}'
  music_to_play: >-
    {% if active_schedule == "just_awake" %}
      {{ just_awake_music }}
    {% elif active_schedule == "early_morning" %}
      {{ early_morning_music }}
    {% elif active_schedule == "morning" %}
      {{ morning_music }}
    {% elif active_schedule == "day" %}
      {{ day_music }}
    {% elif active_schedule == "evening" %}
      {{ evening_music }}
    {% endif %}
  radio_mode: >-
    {% if active_schedule == "just_awake" %}
      {{ false }}
    {% else %}
      {{ true }}
    {% endif %}
  anchors:
    - &replace_music
      service: mass.play_media
      data:
        media_id: "{{ music_to_play }}"
        enqueue: replace_next
        radio_mode: "{{ radio_mode }}"
      target:
        entity_id: "{{ mass_entity }}"
    - &add_music
      service: mass.play_media
      data:
        media_id: "{{ music_to_play }}"
        enqueue: add
        radio_mode: "{{ radio_mode }}"
      target:
        entity_id: "{{ mass_entity }}"

condition:
  - condition: state
    entity_id: input_boolean.setting_automatic_music
    state: "on"

action:
  - if:
      - condition: trigger
        id: "ha_start"
    then:
      - delay:
          minutes: 1
  - if:
      # Clear queue at the start of the day
      - "{{ not is_state(mass_entity, 'playing') }}"
      - "{{ active_schedule == 'just_awake' }}"
    then:
      - service: media_player.clear_playlist
        target:
          entity_id: "{{ mass_entity }}"
  - *replace_music
  - if:
      - "{{ now().month == 12 and now().day > 8 and now().day < 27 }}"
      - "{{ active_schedule in ['morning', 'day'] }}"
    then:
      # Dear Laura, 25% Christmas music is more than enough! /rant
      - *add_music
      - *add_music
      - *add_music
      - *add_music
      - *add_music
      - service: mass.play_media
        data:
          media_id: "{{ christmas_music }}"
          enqueue: add
        target:
          entity_id: "{{ mass_entity }}"
