---
description: >
  Automatically fill the queue of the master media player
  with music that suits the music schedule of the day
alias: house_populate_music_queue
id: 7f94ed28-03ab-4dbf-b509-973f867931a9
mode: queued

trigger:
  - trigger: state
    entity_id:
      - input_select.current_music_schedule
      - input_boolean.setting_automatic_music
      - input_select.music_source

  - trigger: homeassistant
    event: start
    id: "ha_start"

variables:
  mass_entity: '{{ states("sensor.mass_media_entity") }}'
  just_awake_music:
    - "radio_playlist://playlist/library://playlist/38"  # Classical Meditation
    - "radio_playlist://playlist/library://playlist/37"  # Tranquil spa day
    - "radio_playlist://playlist/library://playlist/28"  # Lofi
  early_morning_music:
    - "radio_playlist://playlist/library://playlist/35"  # Reflections
    - "radio_playlist://playlist/library://playlist/31"  # Chill
    - "radio_playlist://playlist/library://playlist/29"  # Chill step
  morning_music:
    - "radio_playlist://playlist/library://playlist/31"  # Chill
    - "radio_playlist://playlist/library://playlist/32"  # Ambient / Relax
  day_music:
    - "radio_playlist://playlist/library://playlist/32"  # Ambient / Relax
    - "radio_playlist://playlist/library://playlist/30"  # Anjuna
    - "ytmusic--RDQFfKiS://playlist/VLPLC800B9699743BD19"  # Top 40
  evening_music:
    - "radio_playlist://playlist/library://playlist/32"  # Ambient / Relax
  christmas_music:
    - "ytmusic://playlist/RDCLAK5uy_nwLjTxbhH7Ng3q4pCbUdtxascis5Adj5g"

  active_schedule: '{{ states("input_select.current_music_schedule") }}'
  music_to_play: >-
    {% if active_schedule == "just_awake" %}
      {{ just_awake_music }}
    {% elif active_schedule == "early_morning" %}
      {{ early_morning_music }}
    {% elif active_schedule == "morning" %}
      {{ morning_music }}
    {% elif active_schedule == "day" %}
      {{ day_music }}
    {% elif active_schedule == "evening" %}
      {{ evening_music }}
    {% endif %}
  anchors:
    - &replace_music
      action: music_assistant.play_media
      data:
        media_id: "{{ music_to_play }}"
        enqueue: replace
      target:
        entity_id: "{{ mass_entity }}"
    - &replace_next_music
      action: music_assistant.play_media
      data:
        media_id: "{{ music_to_play }}"
        enqueue: replace_next
      target:
        entity_id: "{{ mass_entity }}"
    - &add_music
      action: music_assistant.play_media
      data:
        media_id: "{{ music_to_play }}"
        enqueue: add
      target:
        entity_id: "{{ mass_entity }}"

condition:
  - condition: state
    entity_id: input_boolean.setting_automatic_music
    state: "on"

action:
  - if:
      - condition: trigger
        id: "ha_start"
    then:
      - delay:
          minutes: 1
  - if:
      # Clear queue at the start of the day
      - "{{ not is_state(mass_entity, 'playing') }}"
      - "{{ active_schedule == 'just_awake' }}"
    then:
      - *replace_music
    else:
      - *replace_next_music
  - if:
      - "{{ now().month == 12 and now().day > 8 and now().day < 27 }}"
      - "{{ active_schedule in ['morning', 'day'] }}"
    then:
      # Dear Laura, 25% Christmas music is more than enough! /rant
      - *add_music
      - *add_music
      - *add_music
      - *add_music
      - *add_music
      - action: music_assistant.play_media
        data:
          media_id: "{{ christmas_music }}"
          enqueue: add
        target:
          entity_id: "{{ mass_entity }}"
      - action: media_player.shuffle_set
        data:
          shuffle: true
        target:
          entity_id: "{{ mass_entity }}"
