---
description: Control the central ventilation based on several triggers
alias: house_ventilation
mode: queued
id: C90E1ED3-EF56-4F15-A5C7-47F1D75B1F85

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id: binary_sensor.bathroom_shower_detected
    to: "on"

  - platform: state
    entity_id: binary_sensor.bathroom_shower_detected
    to: "off"
    for:
      minutes: 15

  - platform: numeric_state
    entity_id:
      - sensor.bathroom_ble_humidity
    above: 80

  - platform: numeric_state
    entity_id:
      - sensor.bathroom_ble_humidity
    below: 75

  - platform: state
    entity_id:
      - light.wc
    to: "on"
    for:
      minutes: 4

  - platform: state
    entity_id:
      - light.wc
    to: "off"
    for:
      minutes: 10

  - platform: state
    entity_id:
      - input_boolean.house_mode_cooking

  - platform: state
    entity_id:
      - binary_sensor.sauna
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.sauna
    to: "off"
    for:
      minutes: 15

variables:
  anchors:
    - &turn_on
      alias: "Turns on the ventilation"
      service: fan.set_percentage
      data:
        percentage: 100
      target:
        entity_id: fan.itho

    - &turn_off
      alias: "Turns off the ventilation"
      service: fan.set_percentage
      data:
        percentage: 8
      target:
        entity_id: fan.itho

    - &shower_on
      alias: "When someone is taking a shower"
      condition: state
      entity_id: binary_sensor.bathroom_shower_detected
      state: "on"

action:
  choose:

    - alias: "Check if someone is cooking"
      conditions:
        - alias: "Cooking mode is on"
          condition: state
          entity_id:
            - input_boolean.house_mode_cooking
          state: "on"
      sequence:
        - *turn_on

    - conditions:
        - alias: "Someone is taking a shower or humidity is very high"
          condition: or
          conditions:
            - *shower_on
            - condition: numeric_state
              entity_id:
                - sensor.bathroom_ble_humidity
              above: 80
      sequence:
        - *turn_on

    - alias: "When there is some number 2 action going on"
      conditions:
        - alias: "When the restoom lights are on for longer than 4 minutes"
          condition: state
          entity_id: light.wc
          state: "on"
          for:
            minutes: 4
      sequence:
        - *turn_on

    - alias: "Turn on when we are using the sauna"
      conditions:
        - alias: "When the sauna is on"
          condition: state
          entity_id: binary_sensor.sauna
          state: "on"
      sequence:
        - *turn_on

  default:
    - *turn_off
