---
alias: areas_attic_lights
description: Turns the attic lights on when motion has been detected
mode: queued
id: 6d93c5dd-87e6-4a9b-9e99-b59edc035a97

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.pir_third_floor_stairs
    to: "on"
  - platform: state
    entity_id: binary_sensor.pir_third_floor_stairs
    to: "off"
    for:
      seconds: 90

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.pir_third_floor_stairs
            state: "on"

        sequence:
          - service: light.turn_on
            data:
              entity_id: light.fibaro_third_floor_stairs

    default:
      - service: light.turn_off
        data:
          entity_id: light.fibaro_third_floor_stairs
          transition: 5
