---
alias: areas_attic_lights
description: Turns the attic lights on when motion has been detected
mode: queued
id: 6d93c5dd-87e6-4a9b-9e99-b59edc035a97

variables:
  current_light_scene: 'scene.attic_lights_{{ states("input_select.current_light_schedule") }}'
  anchors:
    - &condition_is_presence_detected
      condition: state
      entity_id: binary_sensor.presence_attic
      state: "on"

    - &condition_is_light_schedule
      alias: "Check current light schedule"
      condition: state
      entity_id: input_select.current_light_schedule

    - &condition_light_schedule_change
      alias: "Check if the automation got triggered by a light schedule change"
      condition: trigger
      id: light_schedule_change

    - &turn_on
      alias: "Turn the lights on"
      service: scene.turn_on
      data:
        transition: 1

    - &turn_off
      alias: "Turn the lights off"
      service: light.turn_off
      data:
        entity_id:
          - light.attic_spot_left
          - light.attic_spot_right
        transition: 5

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id: binary_sensor.presence_attic
    to: "on"

  - platform: state
    entity_id: binary_sensor.presence_attic
    to: "off"
    for:
      seconds: 60

  - platform: state
    entity_id:
      - input_select.current_light_schedule

condition:
  - condition: state
    entity_id: input_boolean.setting_manual_lights
    state: "off"

action:
  - choose:
      - conditions:
          - *condition_is_presence_detected
          - or:
              - <<: *condition_is_light_schedule
                state: "nachtlampje"
              - alias: "Someone is sleeping"
                condition: state
                entity_id:
                  - binary_sensor.house_mode_someone_asleep
                state: "on"
                for:
                  minutes: 10
        sequence:
          - *turn_off

      - alias: "Very subtly change the lights when a light schedule change is detected."
        conditions:
          - *condition_is_presence_detected
          - *condition_light_schedule_change
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"
            data:
              transition: 120

      - conditions:
          - *condition_is_presence_detected
        sequence:
          - <<: *turn_on
            target:
              entity_id: "{{ current_light_scene }}"

    default:
      - *turn_off
