---
esphome:
  name: esphome-sauna-temperature

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  reboot_timeout: 15s
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.186
    gateway: 192.168.1.1
    subnet: 255.255.255.0

one_wire:
  - platform: gpio
    pin: D4

sensor:
  - platform: dallas_temp
    name: "Sauna Temperature"
    address: "0xd43c9df649f6e828"
