---
esphome:
  name: esphome-sauna-temperature

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid_zolder
  password: !secret wifi_password_zolder

dallas:
  - pin: D4
    update_interval: 10s

sensor:
  - platform: dallas
    name: "Sauna Temperature"
    address: "0xd43c9df649f6e828"
