---
# A binary sensor based on presence
# indicating whether someone is asleep
binary_sensor:
  name: house_mode_someone_asleep
  unique_id: a6d67947-01dc-419f-927f-c26c5ecfb9bc
  state: >
    {%- if states("sensor.num_people_at_home_asleep") | int > 0 -%}
      on
    {%- else -%}
      off
    {%- endif -%}
