---
# A binary sensor based on presence
# indicating whether everyone home is also asleep
binary_sensor:
  name: house_mode_everyone_asleep
  unique_id: b2ccf31e-d06f-4b54-ad40-878c65b6555f
  state: >
    {%-
      if states("sensor.num_people_at_home_asleep") | int
      == states("sensor.num_people_at_home") | int
      and states("sensor.num_people_at_home") | int > 0
      and is_state("binary_sensor.house_mode_someone_awake", "off")
      and is_state("binary_sensor.house_mode_someone_just_awake", "off")
    -%}
      on
    {%- else -%}
      off
    {%- endif -%}
