---
binary_sensor:
  - name: bathroom_humidity_high
    unique_id: f38b9a1d-51a3-43c8-bec2-670857321e88
    state: >
      {% set humidity = states('sensor.bathroom_ble_humidity') | float(none) %}
      {% if humidity is none %}
        off
      {% elif this.state == 'on' %}
        {{ humidity >= 75 }}
      {% else %}
        {{ humidity > 80 }}
      {% endif %}
